### ISSUE TITLE
[控制台]视频详情页选择昨日显示的数据却是今日

### ISSUE THREAD

**Issue by analyst004** [Venvy-dev/demand#1000]

**Comment by analyst004** [comment]
测试地址：
http://test-05.videojj.com/console/projects/56e6a7b883d88c2a017a2cd2/videos/574b1389480f52ca016d9f43

**Comment by lihaiye** [comment]
测试通过

**Comment by lihaiye** [comment]
http://dev.videojj.com/ 测试通过

**Comment by lihaiye** [comment]
http://videojj.com/  测试通过
