### ISSUE TITLE
官网灵知数据页面开发

### ISSUE THREAD

**Issue by summernini** [Venvy-dev/demand#1006]
### 需求描述：
官网灵知页面需要显示24小时前地域调用API的情况（如果当前是10点看页面的话，应该显示10点往前推的24小时的数据情况。）

### 人员安排：
@analyst004 麻烦教授提供数据API接口 
@riverlight 麻烦老何提供spark的含有地域的数据给@vickymin 做后端，然后vicky再给 @kuangzhibin 前端调用。

### 排期安排：
7月5日 @kuangzhibin 你可以开始完善页面

![1](https://cloud.githubusercontent.com/assets/17739064/16439689/58034f10-3ded-11e6-9bf8-294094dea48d.png)

### 设计稿
![2 pic_hd](https://cloud.githubusercontent.com/assets/17739064/16439591/a63e985c-3dec-11e6-8a69-2bafc327ab16.jpg)

**Comment by riverlight** [comment]
spark 数据统计已完成

**Comment by vickymin** [comment]
api已提供给 @kuangzhibin
