### ISSUE TITLE
乐视需求：控制台-热点管理中增加定量投放功能（点播）

### ISSUE THREAD

**Issue by summernini** [Venvy-dev/demand#1010]
### 排期安排 Deadline:7月7日：
![1](https://cloud.githubusercontent.com/assets/17739064/16476467/547874a6-3eba-11e6-890c-2bdfb06f1d7b.png)

### 产品经理：
@VignyDragon

### 开发人员：
数据 @analyst004 
后端+后台页面 @bpceee

**Comment by summernini** [comment]
### 华丽丽的延期了 :)
![1](https://cloud.githubusercontent.com/assets/17739064/16726623/cbbf7fb8-478f-11e6-8bdf-4b7ead714cbe.png)

**Comment by shixiaoyanjj** [comment]
- [ ] 今日曝光完成量>=每日曝光量上限时热点未下线

**Comment by lihaiye** [comment]
建议： @VignyDragon 
当同时设置了日限额和总限额时，建议日限额量应小于总限额量

**Comment by VignyDragon** [comment]
原型中提到，在热点总总曝光量上限文本框失去焦点后需要校验，是否大于每日曝光量上限。
需要增加：
在每日曝光量上限文本框失去焦点后也需要校验，是否小于热点总曝光量上限。

**Comment by bpceee** [comment]
@vickymin 昨天看还有数据的，今天又变0了
http://linz.videojj.com/api/videojj/tag/5785e6706ad2f4180105d988/total?start=0&end=1468462829923

**Comment by VignyDragon** [comment]
刚刚和 @bpceee 讨论了下，应该允许运营人员随时修改每日曝光上限和热点总曝光上限的增大或减小，故对这两个文本框的校验规则作如下修改：
1.每日曝光上限：每5min判断是否大于每日曝光完成量，如否，热点下线，次日凌晨0点热点重新上线。修改时，判断是否大于热点总曝光上限，如是，提示“每日曝光量上限不能大于热点总曝光量上限。”
修改每日曝光上限小于或等于今日曝光完成量，则热点下线。再次修改每日曝光上限大于今日曝光完成量，热点再次上线。

2.热点总曝光上限：每小时判断是否大于热点总曝光完成量，如否，热点下线。修改时，判断是否大于或等于每日曝光上限，如否，提示“热点总曝光量上限不能小于每日曝光量上限。”
修改热点总曝光上限小于或等于热点曝光完成量，则热点下线。再次修改热点总曝光上限大于热点曝光完成量，热点再次上线。


原型已更新，地址：http://yx.tech.videojj.com/Guiwenlong/videojj%E6%8E%A7%E5%88%B6%E5%8F%B0/%E7%83%AD%E7%82%B9%E6%8A%95%E6%94%BE%E6%8E%A7%E5%88%B6/#p=%E7%83%AD%E7%82%B9%E7%AE%A1%E7%90%86

**Comment by shixiaoyanjj** [comment]
# 更新时间 7月15日
测试环境
http://videojj.com/
http://demo.tech.videojj.com/2016/01/29/On-line-Demand/?videojjhost=videojj.com

## 问题汇总
- [x] 1、日完成量>=日限额时，热点未下线
>应下线，0：00后清空日完成量，重新上线

- [  ] 2、日限额<日完成量，填写时未校验
>应提示“每日曝光量上限不能小于今日曝光完成量。”

- [x] 3、总限额<日限额，填写时未校验
>应提示“热点总曝光量上限不能小于每日曝光量上限。”

- [ ] 4、总限额<日完成量，填写时未校验
>应提示“热点总曝光量上限不能小于热点曝光完成量。”

- [ ] 5、总限额<总完成量，填写时未校验
>应提示“热点总曝光量上限不能小于热点曝光完成量。”

- [ ] 6、日限额未完成，总限额完成时，热点仍显示


## 测试结果
功能已实现

## 注意
1、热点状态不会改变
>完成定量投放的热点，前端不显示，但控制台仍显示已上线状态

2、不能清空已配置的限额
>已配置的限额清空后保存，会导致热点不显示

3、日限额不能为空
>总限额不影响热点显示，由日限额控制

4、校验提示未按需求实现

**Comment by shixiaoyanjj** [comment]
@VignyDragon @summernini 测试已完成，请确认是否达到上线标准

**Comment by VignyDragon** [comment]
目前待解决问题：
1.投放控制开关：
a.热点为上线状态
开启投放控制，根据每日投放限额及热点总限额当即判断一次，热点是否需要下线；
关闭投放控制，应该恢复热点上线状态。
场景一：今日投放达标热点下线，此时关闭投放控制，应该上线热点。（热点原状态是上线，设置了投放控制后，人为加了限定条件并导致热点下线，去掉投放控制，应该恢复热点原来“上线”状态）
场景二：热点总限额达标且今日限额达标热点下线，此时关闭投放控制，应该上线热点。（此时关闭投放控制代表该热点恢复自由投放状态）

b.热点为下线状态
开启投放控制，热点保持下线状态；
关闭投放控制，热点保持下线状态。

此问题修复后，麻烦 @shixiaoyanjj 再测一下，没有其他逻辑问题，即可告知莉敏该需求可上线。

**Comment by bpceee** [comment]
当即判断没必要吧，还是等计划任务执行好了，5分钟一次。

**Comment by vickymin** [comment]
现在当日和总量缓存都为10分钟了，望知晓

**Comment by VignyDragon** [comment]
为求精准，应该当即判断，不过目前可以先不做这个判断，优先满足开启和关闭投放控制的需求。

**Comment by shixiaoyanjj** [comment]
## 热点状态：已上线

- [ ] 日完成量未达标，总完成量未达标热点显示，关闭投放功能，热点显示
- [ ] 日完成量未达标，总完成量达标热点不显示，关闭投放功能，热点显示
- [ ] 日完成量达标，总完成量未达标热点不显示，关闭投放功能，热点显示
- [ ] 日完成量达标，总完成量达标热点不显示，关闭投放功能，热点显示

## 热点状态：已下线

- [ ] 开启投放功能，日完成量未达标，热点不显示
- [ ] 关闭投放功能，日完成量未达标，热点不显示

**Comment by shixiaoyanjj** [comment]
## BUG

- [ ] 热点隐藏时关闭投放功能，热点不显示

@bpceee
