### ISSUE TITLE
【前台】打点优化

### ISSUE THREAD

**Issue by Gracebaby** [Venvy-dev/demand#1011]
亲爱滴朱朱 @hzzhujf 

由于资源归于项目，项目授权的多个账号下资源一并归属于该项目，导致资源管理中的热点图标库会产生多个相同的热点图标

解决方式：前台打点时，在打点面板的选择图标处，新增图标名称
交互逻辑：当鼠标hover至图标上时，显示图标名称

麻烦朱朱尽快处理，解决运营问题，谢谢：）
@chndyyang  老杨请知晓 ：）
@summernini   请知晓 ：）

**Comment by Gracebaby** [comment]
@hzzhujf  朱朱实现后记得提测：）
 @shixiaoyanjj  麻烦小乌龟跟进测试：）

**Comment by shixiaoyanjj** [comment]
## 测试结果
- [ ] hover图标较长时间后显示标题，建议优化为即时显示
![image](https://cloud.githubusercontent.com/assets/16204026/16557129/a6eaa156-4210-11e6-8563-d5aef8ae4c27.png)
