### ISSUE TITLE
红包支持批量打点功能（根据北京时间设定）

### ISSUE THREAD

**Issue by iEricKoh** [Venvy-dev/demand#1018]
@summernini @hzzhujf 

This branch adds support for sending a redenvelope to multiple videos via ``channel ID`` and `` video ID``

**Comment by summernini** [comment]
### 产品原型：
http://yx.tech.videojj.com/Guiwenlong/videojj%E6%8E%A7%E5%88%B6%E5%8F%B0/%E6%89%B9%E9%87%8F%E7%BA%A2%E5%8C%85%E6%89%93%E7%82%B9_console_20160701/#p=%E6%89%B9%E9%87%8F%E6%89%93%E7%82%B9

### 产品经理：
猛龙

### 排期：Deadline:7/14
![1](https://cloud.githubusercontent.com/assets/17739064/16575470/04dc69a2-42bb-11e6-901d-f49de3c94fc7.png)

**Comment by hzzhujf** [comment]
更新到测试环境了
调用popPreviewGift函数，创建红包预览，如下
```javascript
var ivaInstance = new Iva('playerCnt', {
  appkey: '410idWDt',
  video: 'test',
  audit: true,
  loaded: function () {
    this.popPreviewGift({
      _id: '56f20ae629de6def00386f02',
      cat: 104,
      pic: [
          {
            url: "http://static.cdn.videojj.com/redPacket.png",
            _id: "56f20ae629de6def00386f06",
            type: 0,
            id: "56f20ae629de6def00386f06"
          }
        ],
        link: [
          {
            url: "http://baidu.com",
            _id: "56f20ae629de6def00386f05"
          }
        ],
        desc: "复制口令到支付宝打开"
    })
  }
})
```
具体调用方式可以当面交流 @iEricKoh

**Comment by iEricKoh** [comment]
调用IVA之后，submit时候调用的API：


* **URL**

  `/api/tags`

* **Method:**

  `POST`

**Comment by iEricKoh** [comment]
@hzzhujf 除了以下的参数意外，我还会传递给你三个参数，麻烦到时候你也传递过来：

1. ``channels``  // 数组，包含了所有的 channel id
2. ``videos``  // 数组，包含了所有 video id
3. ``multiPublish`` // 布尔值， 只要是批量打点的，值为 true

````
var ivaInstance = new Iva('playerCnt', {
  appkey: '410idWDt',
  video: 'test',
  audit: true,
  loaded: function () {
    this.popPreviewGift({
      _id: '56f20ae629de6def00386f02',
      cat: 104,
      pic: [
          {
            url: "http://static.cdn.videojj.com/redPacket.png",
            _id: "56f20ae629de6def00386f06",
            type: 0,
            id: "56f20ae629de6def00386f06"
          }
        ],
        link: [
          {
            url: "http://baidu.com",
            _id: "56f20ae629de6def00386f05"
          }
        ],
        desc: "复制口令到支付宝打开"
    })
  }
})
````

**Comment by iEricKoh** [comment]
@hzzhujf 

IP: ``192.168.2.217``

**Comment by iEricKoh** [comment]
等待 fixes task

- [ ] 按项目发送红包

**Comment by iEricKoh** [comment]
@chndyyang @hzzhujf 
 
测试链接:
``http://test-03.videojj.com/``

测试方法:
``进入控制台 - 热点列表 - 添加项目热点 - 选择 test btn``

![video video _ _](https://cloud.githubusercontent.com/assets/8081074/16729215/96b80d2c-479d-11e6-92a3-1ae6c671b556.png)

**Comment by iEricKoh** [comment]
等待 fixes task

- [ ] 允许选择项目发送
- [ ] 允许全选栏目

**Comment by iEricKoh** [comment]
@hzzhujf 

除了上面提到的 `channels`, `videos`,

我会再传递给你一个 `selectedProject`, 请在post tag的时候回传过来给我。 这个值就是一个project id, string 类型，代表了用户选择了全项目的投放。

所以当前的逻辑允许：
1. 按项目投放
2. 按栏目投放
3. 按视频投放

**Comment by VignyDragon** [comment]
需求补充说明：
1.根据目前开发的实现方式，我们把所有未选择栏目的视频归类为“未分类视频”，“未分类视频”和“栏目”层级一致。可以展开栏目选择栏目内视频，或者展开未分类视频选择没有归到任何栏目的独立视频。

2.关于全选：
a.全选项目or栏目，指按项目id或者栏目id批量打点，此后该项目or栏目中新建视频时会默认打上本次操作的红包热点；
b.项目内or栏目内全选，指选中项目内or栏目内当下存在的所有视频并批量打点，此后该项目or栏目中新建视频不会默认打点。

**Comment by iEricKoh** [comment]
@shixiaoyanjj @lihaiye 

你们现在可以访问 `http://test-03.videojj.com/`测试红包批量投放的功能，步骤见下图：
![video video _ _](https://cloud.githubusercontent.com/assets/8081074/16754439/4879d45a-4825-11e6-8e83-19a5ad3081ab.png)

之后在弹出来的modal中，依次选择``红包`` -> ``项目/栏目/视频`` -> ``确认投放``
麻烦请先重点测试功能性的问题，比如选择多个视频/栏目，确认所选的栏目跟视频中能够出现相应的红包。
请让我知道如果你们有什么问题，thanks.

![video video _ _](https://cloud.githubusercontent.com/assets/8081074/16754487/bbfce2a0-4825-11e6-9672-5c66abab0e23.png)
![video video _ _](https://cloud.githubusercontent.com/assets/8081074/16754536/0c40af94-4826-11e6-8a05-4534734a7442.png)

**Comment by hzzhujf** [comment]
@shixiaoyanjj  Iva 测试代码：http://7xjfim.com2.z0.glb.qiniucdn.com/test_Iva.js
@iEricKoh  参数可以传一个cb，值为function,创建成功的回调

**Comment by iEricKoh** [comment]
@hzzhujf Ok.

@netpi 

两个事情需要跟你确认一下：

### 问题一
假设用户选择了按``项目A``批量投放红包。之后我 ``mqttClient.publish('videojj/project/123456)``.
此时成功向 ``projectId == 123456`` 的所有视频投放红包。

**问题：**之后当用户又在``项目A``里**新增一个视频**，想要实现新增的这个视频也能够收到这个红包，这时候我需要再做什么事情吗？

### 问题二
2. 当用户选择了按``栏目``投放，也是类似上面的问题。

**Comment by iEricKoh** [comment]
@hzzhujf @VignyDragon @Zard1096 

以下是mqtt publish时候对应的key，你们监听的时候应该会用到:

按项目投放
````
mqttClient.publish('videojj/project/' + projectId)
````
按栏目投放
````
mqttClient.publish('videojj/channels/' + channelId)
````
按视频投放
````
mqttClient.publish('videojj/' + videoId)
````

**Comment by shixiaoyanjj** [comment]
# 更新时间 7月12日
测试环境
http://test-03.videojj.com/
http://demo.tech.videojj.com/2016/03/11/Test-Demand-Page/?videojjhost=dev.videojj.com

## 问题汇总
- [ ] 批量打点后视频显示红包，刷新视频重连后不显示红包【videojj/p2p消息未推送】

- [ ] modal中选择红包页面未显示项目下所有红包资源【所有帐号下创建的资源关联该项目都应显示】

**Comment by lihaiye** [comment]
- [ ] 1、添加项目热点，改为批量添加热点，需求未实现
- [ ] 2、选择资源界面，页面可输入不存在的页面数字  
- [ ] 3、选择红包时，鼠标点中红包时建议增加hover效果 @VignyDragon 
- [ ] 4、打点界面返回上一步会打开空白页，建议返回至上一级视频/栏目选项页面

**Comment by iEricKoh** [comment]
@shixiaoyanjj 

> 批量打点后视频显示红包，刷新视频重连后不显示红包【videojj/p2p消息未推送】

 这个问题是指哪个platform的问题，desktop? mobile ?
 然后是按什么投放产生的问题？按项目？按栏目？按视频？

> modal中选择红包页面未显示项目下所有红包资源【所有帐号下创建的资源关联该项目都应显示】

@VignyDragon 请你确认一下这个问题，红包资源的显示问题。

目前我实现的是，用户在红包库管理页面下有多少个资源，在选择批量投放红包的modal中，相应的就会显示多少个。

**Comment by iEricKoh** [comment]
@lihaiye 

> 添加项目热点，改为批量添加热点，需求未实现

修复中

> 选择资源界面，页面可输入不存在的页面数字

我不觉得这个是问题。当你知道一共只有两页的时候，你故意输入了一个100页。我的程序并没有跳转到第100页也没有出现任何奇怪的问题，你只是可以输入，但是没有发生任何奇怪的结果。以及这是全站甚至绝大多数网站都存在的情况，有问题请另开ticket.

*这个问题我不会在这个issue中修复。*

> 打点界面返回上一步会打开空白页，建议返回至上一级视频/栏目选项页面

@hzzhujf 这个问题的话，需要你提供一个callback的接口，当``上一步``button被点击的时候，或者我觉得你可以当被点击的时候，直接调用之前已经pass过给你的cb，那个cb就是用来close掉弹出来的iva modal.

**Comment by shixiaoyanjj** [comment]
@iEricKoh 
>这个问题是指哪个platform的问题，desktop? mobile ?
然后是按什么投放产生的问题？按项目？按栏目？按视频？

按资源的适用平台投放
platform是老的参数，现在仍用来兼容desktop Web iOS Android
![image](https://cloud.githubusercontent.com/assets/16204026/16790378/fefaa994-48e7-11e6-9733-5387aac49822.png)
具体情况可以问老毕

**Comment by iEricKoh** [comment]
@shixiaoyanjj 

> 批量打点后视频显示红包，刷新视频重连后不显示红包【videojj/p2p消息未推送】

Sorry, 我重新更正一下我的疑问。

## 批量打点后视频显示红包：

这里的批量，你是按照批量按栏目投放？批量按视频投放？还是按全项目投放？

## 刷新视频重连后不显示红包：

刷新视频的操作，我刚刚问的关于platform的意思是，你是在什么设备上执行刷新操作的？是在手机上刷新？还是桌面的浏览器上刷新？

因为红包能够投放出去，说明我这边的消息已经推动出去了，请告诉我是在什么设备上执行操作的，我帮你锁定问题。

以下是针对不同的投放方式，可能会推送出去的消息。

按项目投放
````
mqttClient.publish('videojj/project/' + projectId)
````
按栏目投放
````
mqttClient.publish('videojj/channels/' + channelId)
````
按视频投放
````
mqttClient.publish('videojj/' + videoId)
````

**Comment by iEricKoh** [comment]
@shixiaoyanjj 

btw, 我刚刚看到上面有条comment里面，你写了：
# 更新时间 7月12日

意思是日后你还会再来修改更新这条comment对吗？
请不要这样，对于之前发过的comment，日后有更新，请重新发一条新的comment，而不要修改编辑它们。

原因是，你发了一条新的comment, 我email会收到通知。
但是你编辑了一条comment, 我是无法收到任何通知的。

**Comment by iEricKoh** [comment]
红包modal中应该出现的红包应该满足以下条件：

1. 当前用户创建的
2. 未关联栏目的

**Comment by iEricKoh** [comment]
> modal中选择红包页面未显示项目下所有红包资源【所有帐号下创建的资源关联该项目都应显示】

关于这个问题，与@VignyDragon讨论之后有了以下的结论

红包modal中应该出现的红包应该满足以下条件：

1. 当前用户创建的
2. 未关联栏目的

**Comment by shixiaoyanjj** [comment]
@iEricKoh 
测试地址
http://demo.tech.videojj.com/2016/03/11/Test-Demand-Page/?videojjhost=dev.videojj.com

批量打点后web视频显示红包【videojj/p2p消息推送成功】
相同地址，刷新视频重连后不显示该红包【videojj/p2p消息未推送】
投放的同一个红包，我不明白刷新前后和投放方式有什么关联
另：http://test-03.videojj.com/地址现在连不上，现在无法重现你的问题

github确实不适合测试提交BUG，由于现在没有固定的规范，所以我们在不断配合程序习惯来使用一套比较合理的方案，或者你可以提出一些更好的方案，谢谢

**Comment by iEricKoh** [comment]
@shixiaoyanjj 你说的刷新之后红包不出现的问题，等下我会看一下，有结果我让你知道。

麻烦你再帮我按照下面的路径测试一下：

1. 按项目投放
期望结果：选择按照项目投放，这个项目下的所有视频中，都会出现红包
![1](https://cloud.githubusercontent.com/assets/8081074/16793208/b849729a-4901-11e6-8e80-ed7d17e474b5.png)


2. 按栏目投放
期望结果：所选的N个栏目中，这N个栏目下的视频，都会出现红包
![2](https://cloud.githubusercontent.com/assets/8081074/16793231/e127f498-4901-11e6-8101-9c9d90c77a64.png)


3. 按视频投放
期望结果：所选的N个视频中，都会出现红包
![3](https://cloud.githubusercontent.com/assets/8081074/16793280/56b46af2-4902-11e6-89b2-725d2e1fdd69.png)


4. 按栏目与视频投放
期望结果：同时选择N个栏目与M个视频，N个栏目下的视频，与M个视频，都会出现红包
![video video _ _](https://cloud.githubusercontent.com/assets/8081074/16793308/865cf42c-4902-11e6-89d7-e9c243eaf244.png)

**Comment by iEricKoh** [comment]
@shixiaoyanjj @lihaiye 

Hi All,

刚刚上线了两个新的features:

1. 允许全选视频
2. 选择栏目modal中，会显示出来一个``未分组``的栏目(如果当前项目中，存在视频A，但是它不属于任何栏目，我们会在该modal中，将视频A放进这个``未分组``的栏目里)

@VignyDragon 

对于这个特殊栏目(``未分组``)的名字，还有tooltip中出现的text，有需要修改的话请让我知道。

你可以访问testing server查看最新的改动：
http://test-03.videojj.com/

![screenshot_2016-07-13_14-34-37](https://cloud.githubusercontent.com/assets/8081074/16793912/1e7f93b4-4907-11e6-8dbe-f49a6e11def7.png)

**Comment by iEricKoh** [comment]
@lihaiye 

> 添加项目热点，改为批量添加热点，需求未实现
已修复，请测试再次。

![video video _ _](https://cloud.githubusercontent.com/assets/8081074/16794622/95e03ec8-490b-11e6-8e14-f169073082e1.png)

**Comment by iEricKoh** [comment]
@shixiaoyanjj 红包刷新之后消失的问题，我刚刚咨询过@netpi。

这个问题应该是所有消息推送的资源都会出现的问题，不是这次批量投放红包才出现的。
具体解决方法之后他会跟@summernini讨论。

目前先麻烦你测试前面comment中我提到的几种情况，确保红包批量投放的功能，功能上是都已经没问题的。

**Comment by lihaiye** [comment]
- 选择视频时，由于测试栏目中包含大量标题为**defult**的视频，在读取视频列表时比较慢且列表特别长，建议优化  @VignyDragon 
![image](https://cloud.githubusercontent.com/assets/17242849/16794735/2fa8a3ce-490c-11e6-9744-814d98b8a51a.png)

**Comment by VignyDragon** [comment]
目前我发现的一些问题：
1.全选项目时，未选中未分组的视频
2.未分组视频无需onmouseover提示语
3.选中的栏目名称改为蓝色字体
4.标题改为“请选择投放视频”
5.点击栏目名称，进入栏目内视频列表时，不应该有“确定”button，只留“上一步”就好
![default](https://cloud.githubusercontent.com/assets/20216906/16794836/b0c0985e-490c-11e6-8a39-3bd6d686e251.png)

**Comment by iEricKoh** [comment]
@lihaiye 谢谢你的反馈，这是UI问题，我会尽快修复。

btw, 方便提供给我你的测试帐号吗？因为我的帐号没有这么多的data，所以我在开发中我就没有发现到这个问题

**Comment by lihaiye** [comment]
@iEricKoh 
帐号：lihaiye@videopls.com    密码：a123123
项目：芒果TV  视频比较多

**Comment by iEricKoh** [comment]
@lihaiye Thank you.

**Comment by lihaiye** [comment]
- [ ] 勾选了**全选项目**时，**未分组**当中的视频未选中

**Comment by shixiaoyanjj** [comment]
@iEricKoh @summernini 
>刷新之后红包不出现的问题不解决，无法充分测试，目前只能测试打开数个视频后做红包批量打点操作

根据要求
按项目、按栏目、按视频的测试结果如下

## 全选整个项目，整个栏目打点，红包不显示
![image](https://cloud.githubusercontent.com/assets/16204026/16796992/01bcbab6-4918-11e6-98c3-93f1c204c81f.png)


@VignyDragon 
1、建议视频筛选增加标题搜索功能
2、确认无栏目的视频添加方式

**Comment by iEricKoh** [comment]
@shixiaoyanjj 感谢你的测试结果，红包刷新丢失的问题，有一些难度，我们正在尝试寻找解决方法。

全选整个项目，整个栏目打点，红包不显示

这个问题我怀疑是消息发送出去了，但是没人监听，我会发一封email出来通知大家。

**Comment by shixiaoyanjj** [comment]
红包modal中应该出现的红包应该满足以下条件：
当前用户创建的
未关联栏目的

@VignyDragon 

- 请确认该需求是否要实现，目前测试结果

>用户创建红包资源关联栏目，在红包modal显示红包

- 请确认已推送的红包

>1、修改资源后是否同步
2、是否可以重复推送

- 建议在选择视频后确认时增加二次确认框

>![image](https://cloud.githubusercontent.com/assets/16204026/16799055/8f47b364-4921-11e6-8d5b-d3f20de1792b.png)

**Comment by iEricKoh** [comment]
@lihaiye 

> 选择视频时，由于测试栏目中包含大量标题为defult的视频，在读取视频列表时比较慢且列表特别长，建议优化

Hey, 视频过多导致分页显示异常的问题，已解决。请再次测试，thanks.
![video video _ _](https://cloud.githubusercontent.com/assets/8081074/16799222/4d10b88c-4922-11e6-8d37-b5a64a6ca111.png)

**Comment by iEricKoh** [comment]
@shixiaoyanjj 

> 用户创建红包资源关联栏目，在红包modal显示红包

Sorry, 关于这个修改我刚刚才更新到test-03, 麻烦你再次test一下，有问题让我知道，cheers.

**Comment by shixiaoyanjj** [comment]
- [ ] 已选择栏目和视频没有删除按钮，与原型不符

![image](https://cloud.githubusercontent.com/assets/16204026/16799188/1f7e4bf0-4922-11e6-9341-7596b17e8b43.png)

**Comment by iEricKoh** [comment]
@shixiaoyanjj 红包刷新丢失的问题，我跟@netpi一起修复了一下，明天你可以测试一下，thanks.

**Comment by shixiaoyanjj** [comment]
>用户创建红包资源关联栏目，在红包modal显示红包
已测试通过 :ok:

**Comment by iEricKoh** [comment]
Hi @shixiaoyanjj @lihaiye 

只是想让你们知道关于这个的最新修改已经完成，你们可以访问http://test-03.videojj.com/查看最新的修改。
> 全选项目时，未选中未分组的视频

@shixiaoyanjj 红包刷新丢失的问题，有任何更新吗？

**Comment by Zard1096** [comment]
@summernini @shixiaoyanjj iOS已添加

**Comment by shixiaoyanjj** [comment]
>红包刷新丢失的问题，有任何更新吗？
已测试通过 :ok: 

- [ ] 批量红包打点后，将热点删除未通知前端下线

**Comment by shixiaoyanjj** [comment]
@iEricKoh 

- [ ] 勾选项目打点后，视频显示红包，刷新该视频，未推送红包
- [ ] 勾选栏目打点后，视频显示红包，刷新该视频，未推送红包

>- [x] 勾选视频打点，视频显示红包，刷新该视频，成功推送红包

**Comment by iEricKoh** [comment]
@shixiaoyanjj 

> 批量红包打点后，将热点删除未通知前端下线

这个问题我尝试了修复并且更新到了[test 03](http://test-03.videojj.com/), 明天你可以测试，有任何结果请让我知道，thx.

**Comment by lihaiye** [comment]
### FLASH测试结果：

- [ ] 勾选项目打点后，**视频不显示红包**
- [ ] 勾选栏目打点后，视频显示红包，**刷新视频，红包不显示**
- [ ] 勾选视频打点后，视频显示红包，刷新视频，红包显示

**Comment by chndyyang** [comment]
@iEricKoh @lihaiye project的红包推送后，重新上线后并未推送p2p的个人频道，所以刷新后看不到红包

**Comment by iEricKoh** [comment]
Hey @chndyyang , 红包刷新丢失的问题，我跟@netpi会一起再检查一下。

但是 project 的红包不仅仅是刷新有问题，当选择发送project红包的时候，都不会出现，不仅仅是刷新才不会出现，确认一下你有监听project范围的吗？`` mqttClient.publish('videojj/project/' + projectId)``

**Comment by iEricKoh** [comment]
@lihaiye @shixiaoyanjj 项目级别跟栏目级别红包，刷新丢失的问题，我跟@netpi又修复了一下。

麻烦你们访问我的机器test, 因为现在test-03上面经常crash...
[http://192.168.2.217/](http://192.168.2.217/)

@shixiaoyanjj 同时热点删除的问题，有结果请记得让我知道，thanks.

**Comment by iEricKoh** [comment]
@chndyyang 红包刷新丢失的问题，你可以测试一下， http://test-03.videojj.com/

**Comment by iEricKoh** [comment]
@shixiaoyanjj @VignyDragon 

> 已选择栏目和视频没有删除按钮，与原型不符

删除button我等到下一次做编辑页面的时候再一起做，目前还有一些功能上的bug以及着急上线，我只能先专注以修复功能性的bug优先。

**Comment by iEricKoh** [comment]
@shixiaoyanjj @lihaiye 

关于下面两个问题的最新修复刚刚更新到了[test-03.videojj.com](test-03.videojj.com), 请帮忙测试，有结果请让我知道。

1. 红包刷新之后丢失问题
2. 控制台delete一个tag之后，红包不消失的问题

**Comment by shixiaoyanjj** [comment]
@iEricKoh 

## H5

测试环境
http://demo.tech.videojj.com/2016/03/11/Test-Demand-Page/?videojjhost=dev.videojj.com
http://7xjfim.com2.z0.glb.qiniucdn.com/test_Iva.js

## 测试结果
>1、红包刷新之后丢失问题

测试未通过，项目和栏目打点刷新仍未显示红包


>2、控制台delete一个tag之后，红包不消失的问题

控制台删除视频红包 前端红包消失 热点显示已下线  :ok: 
控制台删除栏目红包 前端红包消失 热点显示已下线   :ok: 
控制台删除项目红包 前端红包消失 热点显示已下线   :ok: 
- [ ] 前端删除红包，只删除了该视频ID内的红包，但控制台热点显示已下线

**Comment by lihaiye** [comment]
@iEricKoh     
Flash测试结果与H5一样~

**Comment by iEricKoh** [comment]
Hey @VignyDragon,

当前我们一共有两种方式可以*删除*一个tag:

1. 控制台系统
2. 前端player

当前在``控制台系统``中删除一个tag，是按全局方式删的。
删除掉一个tag之后，这个tag会变成``已下线``的状态。

当在``前端player``中删除一个tag，也是按照全局方式删的。
虽然好像你在某个正在播放的视频中删除了一个tag，直觉会觉得自己只是在当前视频中删除了这个tag.
但是由于这个tag是全局投放的，所以无论在``控制台系统``还是``前端player``中删除一个tag，意义都是同样的，都是全局删除。

以上，解释@shixiaoyanjj的疑问，也希望让你@VignyDragon知道。

> 前端删除红包，只删除了该视频ID内的红包，但控制台热点显示已下线

**Comment by summernini** [comment]
@iEricKoh 
我认为应该是在「控制台」删除tag时，是按全局方式删的；而在「前端player」删除时，应该删除这个视频对应的tag。

由于此功能开发已经延期，20日是对外交付日，请评估下如果要改成我说的逻辑需要多久时间？如果太久的话暂时按照你说的方案做，但是之后我们还得做优化。

**Comment by iEricKoh** [comment]
Hey @summernini,

短期内，当前我们的数据结构无法实现你想要的效果。

比如下面的场景：

当你``按项目``投放了一个红包A，对程序来说，就只知道某个``project id``下面会投放红包A.
当你在视频J试图删除掉红包A，我们最多可以实现这一次删除发生之后，视频J不出现红包A。

_但是当用户再次播放，或者刷新播放的时候，视频J中的红包A还是会重新出现的._
_原因：红包A是``按项目``投放的，对程序来说，只有``project id``可见，视频J的 id 对程序是不可见的。_

**Comment by summernini** [comment]
@iEricKoh 前端IVA删全局热点时我让老朱加个提示，提示用户必须去控制台删除，此需求已经另外建Issue了。 

@shixiaoyanjj 此票如果没有问题，请提上线，谢谢~

**Comment by shixiaoyanjj** [comment]
>前端删除红包后，删除全局红包
前端删除视频红包 前端全局热点删除，控制台全局热点显示已下线   :ok: 
前端删除栏目红包 前端全局热点删除，控制台全局热点显示已下线   :ok: 
前端删除项目红包 前端全局热点删除，控制台全局热点显示已下线   :ok:

**Comment by iEricKoh** [comment]
@hzzhujf 这里点击上一步button的时候，可以再添加允许传递一个callback吗？用来让我关掉modal, cheers.

![video video _ _](https://cloud.githubusercontent.com/assets/8081074/16912412/7ef05716-4d16-11e6-9f89-f31f245254ca.png)

**Comment by VignyDragon** [comment]
@iEricKoh  @shixiaoyanjj 上线前需要解决的问题：
1.打点界面返回上一步会打开空白页，建议返回至上一级视频/栏目选项页面
2.点击栏目名称，进入栏目内视频列表时，不应该有“确定”button，只留“上一步”就好（此举避免用户在进入栏目内选择视频后误点确定，跳至设置红包显示条件页面）

**Comment by hzzhujf** [comment]
加了一个参数pre作为点击“返回上一步”的回调 @iEricKoh

**Comment by iEricKoh** [comment]
@hzzhujf Okay, 没问题了，thanks.

@shixiaoyanjj @lihaiye @VignyDragon 你们可以从[http://test-03.videojj.com/](http://test-03.videojj.com/)看到关于下面两条的最新修改。

>
1.打点界面返回上一步会打开空白页，建议返回至上一级视频/栏目选项页面
2.点击栏目名称，进入栏目内视频列表时，不应该有“确定”button，只留“上一步”就好（此举避免用户在进入栏目内选择视频后误点确定，跳至设置红包显示条件页面）

**Comment by iEricKoh** [comment]
Hi @hzzhujf,

当前两个button，``返回上一步``与``确认``，在Firefox下面会出现``event is not defined``的错误，麻烦你看一下。

>
OS: Arch Linux 4.x & OS X
Firefox: 47.0.1


![screenshot_2016-07-19_12-09-42](https://cloud.githubusercontent.com/assets/8081074/16938383/c9dc34e6-4da9-11e6-90b3-5e80fc492fb6.png)

**Comment by lihaiye** [comment]
测试环境：test-03.videojj.com

### Android测试结果：

>勾选项目打点，红包正常显示，刷新视频后显示
勾选栏目打点，红包正常显示，刷新视频后显示
勾选视频打点，红包正常显示，刷新视频后显示

**Comment by lihaiye** [comment]
@iEricKoh 

Android端目前碰到有以下问题：
>1. 勾选栏目打点后，红包未及时显示，刷新视频后才显示
2.控制台将热点下线后，红包未及时消失，刷新视频后才消失

**Comment by iEricKoh** [comment]
@lihaiye 你说的下面这个问题，之前我看过你上上条测试是好的对吗？后来你编辑了内容修改掉了？

因为我要确认这个问题是一直存在，还是突然间才发生的。

> 勾选栏目打点后，红包未及时显示，刷新视频后才显示 2.控制台将热点下线后，红包未及时消失，刷新视频后才消失

之前我发送过email通知各个平台的同事了，让他们添加MQTT的监听。

当前我看到本 ticket 里面收到了 flash, H5，iOS已经完成添加的comment.
唯独没有看到Android。

**Comment by hzzhujf** [comment]
@iEricKoh  问题已经解决
![screenshot_2016-07-19_12-09-42](https://cloud.githubusercontent.com/assets/8081074/16938383/c9dc34e6-4da9-11e6-90b3-5e80fc492fb6.png)

**Comment by iEricKoh** [comment]
@hzzhujf 我测试没问题，thanks.

@VignyDragon 早上你反应的问题，在firefox下会有error产生的问题已经被修复了。你可以访问[http://test-03.videojj.com](http://test-03.videojj.com)查看最新修改。

**Comment by androidlgf** [comment]
@iEricKoh android 也添加，只不过我没回复

**Comment by iEricKoh** [comment]
@lihaiye

所以Android也已经完成添加了。

麻烦你确认一下你刚刚反应的问题是一直存在，还是突然间，比如今天刚刚才出现的。

**Comment by VignyDragon** [comment]
#firefox下返回报错问题已修复，我这边没有其他问题，麻烦测试同学再过一下，没有其他问题，我们提上线。

**Comment by shixiaoyanjj** [comment]
## iOS

测试环境
http://test-03.videojj.com

## 测试结果
>1、
- [ ] 添加项目红包，前端显示红包
- [ ] 添加栏目红包，前端显示红包
- [ ] 添加视频红包，前端显示红包
>2、
- [ ] 添加项目红包，前端播放视频，显示红包
- [ ] 添加栏目红包，前端播放视频，显示红包
- [ ] 添加视频红包，前端播放视频，显示红包

>3、
- [ ] 控制台删除视频红包 前端红包消失 
- [ ] 控制台删除栏目红包 前端红包消失
- [ ] 控制台删除项目红包 前端红包消失

**Comment by lihaiye** [comment]
@VignyDragon @iEricKoh 

以下问题测试通过：
>1.打点界面返回上一步会打开空白页，建议返回至上一级视频/栏目选项页面🆗
2.点击栏目名称，进入栏目内视频列表时，不应该有“确定”button，只留“上一步”就好🆗
3.firefox下会有error产生的问题🆗

移动端红包是今天才测试的，选择栏目打点的问题前端已在修改中

**Comment by lihaiye** [comment]
Android端按栏目打点的红包问题测试已修复 ：

- [ ] 1、勾选栏目打点后，红包未及时显示，刷新视频后才显示🆗
- [ ] 2、控制台将热点下线后，红包未及时消失，刷新视频后才消失🆗

**Comment by shixiaoyanjj** [comment]
test-03.videojj.com测试通过
可以更新dev环境

**Comment by iEricKoh** [comment]
@shixiaoyanjj Okay，我会让你知道当它们被merged到dev.

@lihaiye test-03目前已经重启完成

**Comment by iEricKoh** [comment]
@shixiaoyanjj 该ticket中的改动已经merged进dev branch, 明天你们可以看一下。

**Comment by shixiaoyanjj** [comment]
@iEricKoh 
请确认批量红包功能合并已到dev
目前打点选择红包后，下一步无法继续
![image](https://cloud.githubusercontent.com/assets/16204026/16973330/69d8d790-4e65-11e6-8d51-7a6f91284f38.png)

**Comment by iEricKoh** [comment]
@shixiaoyanjj 对，我这边也发现线上的dev环境有点问题。我会尽快让你知道当我解决完这个问题。

**Comment by iEricKoh** [comment]
@shixiaoyanjj dev环境目前看起来似乎好了，你可以尝试一下。

**Comment by iEricKoh** [comment]
@lihaiye 你可以尝试清空一下你的cache或者cookie, 我这边访问dev可以看到最新的iva.

![screenshot_2016-07-20_11-57-34](https://cloud.githubusercontent.com/assets/8081074/16974627/4217aeb4-4e71-11e6-82c4-af00ec15827e.png)

**Comment by lihaiye** [comment]
@iEricKoh   目前dev环境可以访问到最新iva了，谢谢~

**Comment by iEricKoh** [comment]
@shixiaoyanjj @lihaiye 所以红包批量打点的功能到目前为止还有什么问题吗？
@shixiaoyanjj 刚刚你过来找我的，提到说热点无法删除的问题，当前正式环境也存在该问题，所以不是这个issue当中影响的。

如果这个issue中没有问题，今天应该会上线。麻烦你们确认一下。

**Comment by shixiaoyanjj** [comment]
dev.videojj.com环境正在做最后的回归测试，下班前会有结果。

**Comment by iEricKoh** [comment]
好的，辛苦你们了。

**Comment by shixiaoyanjj** [comment]
## dev.videojj.com

- H5测试通过
- iOS测试通过

**Comment by lihaiye** [comment]
测试环境：dev.videojj.com

- Android测试通过

**Comment by iEricKoh** [comment]
@lihaiye @shixiaoyanjj 听说现在 flash 平台会出现重复收到两条 mqtt 的消息对吗？请问这个问题是从一开始就存在，还是最近突然间才发生的？

**Comment by lihaiye** [comment]
@iEricKoh  Flash目前在dev.videojj.com环境下测试现象是这样的：

>1、批量红包，项目打点、栏目打点、视频打点后，以及刷新视频后，前端表现正常
2、推送红包后，收到一条MQTT消息，
刷新视频，会收到两条一样的MQTT消息，但是前端表现红包是只有一个的。

![image](https://cloud.githubusercontent.com/assets/17242849/17013065/59870d46-4f4e-11e6-8202-d80c366a7dbb.png)

**Comment by iEricKoh** [comment]
@lihaiye 谢谢反馈。

那之前呢，就是在dev.videojj.com的环境之前？一样也发生上述的情况吗？
因为我想确定这个问题是始终一直存在，还是突然才产生的。

**Comment by lihaiye** [comment]
@iEricKoh 
因为之前没有截MQTT消息，是昨天上dev环境测试FLASH红包才发现这个问题的。

**Comment by iEricKoh** [comment]
- [ ] 程序中会重复多次执行redis的``keys()``方法

**Comment by pipi32167** [comment]
merge进来的commit貌似会自动close掉一个issue orz

**Comment by lihaiye** [comment]
### 目前在正式环境上videojj.com，H5的测试结果为：
>勾选项目的红包热点，添加后项目下视频红包展示，刷新视频后红包不显示
勾选栏目的红包热点，添加后栏目下视频红包展示，刷新视频后红包不显示
勾选视频的红包热点，添加后对应视频红包展示，刷新视频后红包显示

**Comment by iEricKoh** [comment]
@lihaiye 这个问题是由于上周上线 cytron 的时候因为性能的原因注释掉了红包批量投放中相关功能的代码。

等待 [PR#722](https://github.com/Venvy-dev/videojj/pull/722) merged 之后应该可以解决上述你提到的问题。

**Comment by lihaiye** [comment]
@iEricKoh  
好的，谢谢~
还有请问下：**勾选项目的红包热点，有概率未收到MQTT推送消息** 的情况是否和722有关系呢

**Comment by iEricKoh** [comment]
@lihaiye 目前应该按项目，按栏目投放的逻辑都受到影响。等PR被merged之后我会再通知让，到时候你再看一下。

**Comment by iEricKoh** [comment]
@pipi32167 不知道为什么你4天之前 reopen 这个 ticket 的原因是什么，这个 ticket 原本就应该是 closed 状态。没问题的话请 close.
