### ISSUE TITLE
单个红包打点支持根据视频时间打点功能

### ISSUE THREAD

**Issue by summernini** [Venvy-dev/demand#1019]
### 需求描述：
现在打单个红包仅支持绝对时间（即按北京时间来的），新需求是需要增加根据视频时间打点。

**Comment by iEricKoh** [comment]
@summernini  目前我在做 [#1018](https://github.com/Venvy-dev/demand/issues/1018)，
@nekronhuang 说这里面也有我的工作，如果这个事情的优先级比[#1018](https://github.com/Venvy-dev/demand/issues/1018)高，请让我知道。

**Comment by summernini** [comment]
1080和1019排期时间一样的。都要在本周五下班前完成开发。

**Comment by nekronhuang** [comment]
@iEricKoh 我把想象中我的部分工作完成了，请完成开发后通知我，我们联调下，看看是否还存在预想外的问题

**Comment by summernini** [comment]
恩，eric可以先做这个，让一工先联调起来

**Comment by iEricKoh** [comment]
@nekronhuang Sorry, 麻烦你文字重新说一下这个issue里面你希望我在后台完成什么样的修改， thanks.

**Comment by nekronhuang** [comment]
@iEricKoh 我尽力说明
#### 现有逻辑
当判断`dgCat = 104`的情况时，全部都走了特殊的处理逻辑
#### 期望逻辑
优先判断`req.body.islive`当为true时，依然使用原有逻辑；为false以后直接跳入
```
updateVideoTagsCdnStatus(videoId);
```
#### 修改猜想
将`islive == 'true' || islive == true || tag.cat == 104`的判断条件修改为`islive == 'true' || islive == true`即可以

**Comment by iEricKoh** [comment]
@nekronhuang 谢谢。

总结就是对于 ``dgCat = 104`` 的，你希望它们走``updateVideoTagsCdnStatus(videoId);``的方法。

但是对于 ``dgCat = 104``，并且有``startDt``的呢？应该还是继续走mqtt的逻辑，对吗？
还是走``updateVideoTagsCdnStatus(videoId);``的逻辑？

**Comment by nekronhuang** [comment]
@iEricKoh 不是的哈
总结来说
`dgCat = 104`且`islive = true` 依然使用原来的全部逻辑，包括有`startDt`
`dgCat = 104`且`islive = false` 走`updateVideoTagsCdnStatus(videoId);`逻辑

**Comment by iEricKoh** [comment]
@nekronhuang 

Okay, 修改了原来的逻辑，对于``cat == 104``的条件，新增了当它是live的时候才会进mqtt，否则走cdn.
``islive = true || (dgCat = 104 && islive = true) ``

你可以访问[testing server](http://test-03.videojj.com/)测试，thanks.

**Comment by nekronhuang** [comment]
@iEricKoh 
报错：`isLive is not defined`
原来代码里的变量好像是小写的`islive`

**Comment by iEricKoh** [comment]
@nekronhuang Sorry，上周一直在忙#1018，确实是拼写错了。已经修复，你可以访问[http://test-03.videojj.com/](http://test-03.videojj.com/)查看最新修改。

**Comment by nekronhuang** [comment]
@iEricKoh test-03宕机了，接口502了都。。。

**Comment by iEricKoh** [comment]
Hey @nekronhuang, 谢谢提醒。已经重启，目前好了。不过03还是会经常坏掉，由于testing server资源非常有限。

**Comment by summernini** [comment]
@iEricKoh 这个问题麻烦你和振宇反应一下哈

**Comment by nekronhuang** [comment]
`测试iva地址`: http://7xj85s.com1.z0.glb.clouddn.com/issue-1019.js
`测试环境`: http://test-03.videojj.com

**Comment by lihaiye** [comment]
测试iva地址: http://7xj85s.com1.z0.glb.clouddn.com/issue-1019.js
测试环境: http://test-03.videojj.com

**Comment by lihaiye** [comment]
测试iva地址: http://7xj85s.com1.z0.glb.clouddn.com/issue-1019.js
测试环境: http://test-03.videojj.com

### 问题反馈：
- [ ] 1、普通投放的红包，展示时间可按天和小时设置，但普通热点最大展示时间为3600秒
- [ ] 2、普通红包投放后，在展示时间内拖动视频进度条，会生成一个新的红包热点

**Comment by iEricKoh** [comment]
Hey @nekronhuang,

@lihaiye 上面反馈的两个问题，你知道吗？需要我再因此进行什么修改吗？

------------------

Hi @summernini & @VignyDragon,

目前我们已经有两个红包button, 位于热点投放modal里面，见下图。
请问要同时保留``红包``跟``批量红包``两个button吗？
还是跟原型一样，保留``红包``button, 但是点击之后出现的是批量投放的功能？



![video video _ _](https://cloud.githubusercontent.com/assets/8081074/16936700/80887cfe-4d9b-11e6-8105-aed49f195e46.png)

![default](https://cloud.githubusercontent.com/assets/8081074/16936735/b4ee0540-4d9b-11e6-876b-c8f90bb6515e.png)

**Comment by nekronhuang** [comment]
@iEricKoh 那2个bug都是我这边的，后端那边应该ok了

**Comment by iEricKoh** [comment]
@nekronhuang Okay, 了解了。

**Comment by summernini** [comment]
@iEricKoh 请把「红包」删除，保留「批量红包」

**Comment by iEricKoh** [comment]
Hi @lihaiye,

@nekronhuang _好像_应该已经修复好了以下的两个问题了？你可以测试一下。

>
 红包普通投放后，在展示时间内拖动视频进度条，视频中会生成一个新的红包热点
 添加普通投放红包后，有概率出现不显示红包热点，但有showtag统计

**Comment by lihaiye** [comment]
### H5目前测试结果如下：

**控制台热点：**
>视频内删除普通红包热点，热点显示已下线
控制台删除普通红包热点，刷新视频热点不显示
控制台修改红包显示时间，刷新视频显示时间改变
控制台修改红包展示时长，刷新视频展示时长改变

**普通投放热点逻辑：**
>1、普通投放，打点进展示时间最长3600秒
2、到达tag点时间，红包正常展示
3、展示时间小于等于60秒时不再显示倒计时
4、打开红包信息层后热点隐藏不再显示，推进进度条至展示时间内，热点显示
5、展示时间结束，红包正常消失

@summernini   请确认以上逻辑是否符合需求，其他端是否都需要实现。

### 问题：

- [ ] 使用同一个红包资源，在同 一个视频中添加普通投放和即时投放(定时投放)，进放视频后，拖动视频进度条，即时投放(定时投放)的红包不再显示

**Comment by summernini** [comment]
需求确认无误。
问题答复：逻辑正确

麻烦小叶最终验收无误通知开发上线！

**Comment by summernini** [comment]
关于「使用同一个红包资源，在同一个视频中同时添加普通投放和即时投放(定时投放)，进入视频后，拖动视频进度条，即时投放(定时投放)的红包不再显示」这个Bug目前通过运营层面解决吧，针对不同红包的投放模式建不同的资源。 @VignyDragon 麻烦猛龙和运营培训的时候告知他们。

另外这个Bug后面还是需要解决的，麻烦 @lihaiye 重新建票吧。

**Comment by androidlgf** [comment]
@lihaiye android添加完成

**Comment by Zard1096** [comment]
@shixiaoyanjj iOS 完成

**Comment by lihaiye** [comment]
### Android测试结果：

**普通投放红包热点逻辑：**
>1、到达tag点时间，红包正常展示
2、展示时间小于等于60秒时不显示倒计时
3、点击红包后热点隐藏不再显示，拖动进度条至展示时间内，热点不显示；拖进进度条至热点展示时间前，达到tag点热点正常显示
4、展示时间结束，红包正常消失

**Comment by shixiaoyanjj** [comment]
## iOS 测试结果：

>
- [x] 1、到达tag点时间，红包正常展示
- [x] 2、展示时间小于等于60秒时不显示倒计时
- [x] 3、点击红包后热点隐藏不再显示，拖动进度条至展示时间内，热点不显示；拖进进度条至热点展示时间前，达到tag点热点正常显示
- [x] 4、展示时间结束，红包正常消失

**Comment by iEricKoh** [comment]
resolved.
