### ISSUE TITLE
超级管理员页面新增漏斗图及圆环图

### ISSUE THREAD

**Issue by vickymin** [Venvy-dev/demand#1020]

**Comment by vickymin** [comment]
另会统一替换后台各图表的颜色

**Comment by vickymin** [comment]
测试地址：
http://test-07.videojj.com/admin/#/
实时数据-选择具体视频

**Comment by lihaiye** [comment]
1、实时数据页面，名称**热点圆环图** 应改为：**热点条形对比图**
2、部分视频的条形对比图中，所显示的数据与漏斗图中数据差1（如：天天向上20160325期，热点点击量数量差1）
![image](https://cloud.githubusercontent.com/assets/17242849/16801921/1e21c936-4930-11e6-9f13-f2a7f2202b4c.png)

**Comment by lihaiye** [comment]
http://test-07.videojj.com/ 测试通过

**Comment by lihaiye** [comment]
http://dev.videojj.com/ 测试通过

**Comment by lihaiye** [comment]
http://videojj.com/ 测试通过
