### ISSUE TITLE
官网灵知页面更新迭代

### ISSUE THREAD

**Issue by virgoone** [Venvy-dev/demand#1023]
[测试地址](http://front.test.videojj.com:10081/vdap/)

**Comment by shixiaoyanjj** [comment]
整个页面文字和图片在浏览器100%缩放比例中显示不清晰，需要优化

![image](https://cloud.githubusercontent.com/assets/16204026/16614489/24c914f6-43a4-11e6-811e-f0243ec34e04.png)

**Comment by lihaiye** [comment]
- [ ] 部分浏览器：实时数据分析的导航栏显示异常（360极速、百度、猎豹）

![image](https://cloud.githubusercontent.com/assets/17242849/16722365/a518bc06-4778-11e6-86e9-b50107f5511e.png)

**Comment by Delicate-lee** [comment]
1.按钮链接已修改
2.部分图片已更换
3.部分功能已修改
请重新测试  [测试地址](http://front.test.videojj.com:10081/vdap/)

**Comment by lihaiye** [comment]
建议：
1、顶部的内容在滚动时会出现信息重叠，建议优化； 案例按钮建议有边框或者底色强化可点击效果
![image](https://cloud.githubusercontent.com/assets/17242849/16726926/4705a30e-4791-11e6-939d-faf27684c426.png)

2、打开界面时，导航栏初始没有默认选中效果，建议打开页面后显示选中效果
![image](https://cloud.githubusercontent.com/assets/17242849/16726997/7eb1e18c-4791-11e6-95c6-3d3b9a13cb70.png)

**Comment by Delicate-lee** [comment]
1.顶部问题以及按钮问题暂时不用修改
2.已修改该bug

**Comment by Delicate-lee** [comment]
现在上边涉及的问题解决了，请测试下还有其他问题吗，等会一并调整。

**Comment by lihaiye** [comment]
@Delicate-lee  浏览器兼容相关（Edge\搜狗高速\猎豹浏览器）还是有问题

**Comment by Delicate-lee** [comment]
@lihaiye edge解决，搜狗 猎豹我这边显示没问题
