### ISSUE TITLE
接口返回值改动 #1022

### ISSUE THREAD

**Issue by hzzhujf** [Venvy-dev/demand#1030]
api     /api/users/getCurrentUser
这个接口返回的字段里面，以下3个属性涉及到客户隐私，但是前端暂时又用着，请老毕去掉
email、phone、username

**Comment by bug-cai** [comment]
测试结果，email、phone在前端已不再显示，username仍显示,但username影响不大，且能随时更改，如若可以保留username，则测试通过。 @hzzhujf

**Comment by bpceee** [comment]
@iEricKoh 
分支1022-addVideo，测试通过的话帮忙合并到dev

**Comment by iEricKoh** [comment]
@shixiaoyanjj @lihaiye 测试通过请让我知道。

@summernini 测试通过后需要上线请再让我知道，我再进行合并操作。

**Comment by shixiaoyanjj** [comment]
@iEricKoh @summernini test-04.videojj.com测试通过

**Comment by shixiaoyanjj** [comment]
@iEricKoh 合并dev后请让我们知道哦，谢谢

**Comment by shixiaoyanjj** [comment]
dev.videojj.com测试通过

**Comment by shixiaoyanjj** [comment]
videojj.com测试通过

**Comment by iEricKoh** [comment]
resolved.
