### ISSUE TITLE
【后台】热点列表：修改热点后，该热点会显示为全局热点

### ISSUE THREAD

**Issue by lihaiye** [Venvy-dev/demand#1033]
测试地址：
>http://videojj.com/console/

问题描述：
>热点列表页面：
修改热点信息后保存，该热点会显示为全局热点； 刷新后显示正常

修改后显示：
![image](https://cloud.githubusercontent.com/assets/17242849/16682741/95a3baa6-452e-11e6-8b8b-17de02e0850e.png)

正常显示：
![image](https://cloud.githubusercontent.com/assets/17242849/16682753/a2b14c36-452e-11e6-8b43-46ff1783421f.png)

**Comment by bpceee** [comment]
branch issue-1033, 测的时候跟我说

**Comment by shixiaoyanjj** [comment]
test-04.videojj.com测试通过

**Comment by lihaiye** [comment]
http://dev.videojj.com/ 测试通过

**Comment by lihaiye** [comment]
http://videojj.com/ 测试通过
