### ISSUE TITLE
创建热点时 添加第三方监测(曝光、点击)的需求申请

### ISSUE THREAD

**Issue by williamling** [Venvy-dev/demand#1037]
目前在热点上有需求加上第三方监测的时候 必须先新建好热点 然后在控制台的热点列表中 再去找到那个创建好的热点 点击添加  才能完成创建 
1.在直播服务这块 由于一个热点的时效性可能很短 当运营这边打完一个点 到去控制台加完第三方监测 这段时间本身就容易丢失监测数据 
2.如果是平台方 甚至主播需要打点的时候 如果需要加上第三方监测 那他们就必须进入我们的控制台才行 这样对于他们来说也是很麻烦的一个步骤
由上述2点 我希望能在打点的时候 有需要的话 能直接加完第三方监测 

需求部分：
在新建一个热点的时候 flash这里是通过请求 /api/tags  这个接口来完成打点的 
需要后台这里可以和 api/tags/forConsole/[tagid] 这个接口一样 新增加2个字段 show 和 click  然后把第三方的曝光和点击链接放进去 在新建tag的时候也可以加上第三方监测

**Comment by williamling** [comment]
@summernini

**Comment by summernini** [comment]
@VignyDragon

**Comment by netpi** [comment]
```sh
http --json POST http://localhost/api/tags \
    'Cookie':'token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJfaWQiOiI1NTc2Njc3NTdjZjdjNDY3N2E2NTVhOTciLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE0NjgzOTU3MDEsImV4cCI6MTQ2OTAwMDUwMX0.wRxvCLu2g0O0rQsRpibf7v1QQ-hfdcPBCpyamLTvjvk' \
    'appkey':'TkpWeC1uNmFidA==' \
    'referer':'http://videojj.com' \
    'Content-Type':'application/json' \
    ="" \
    cat="2" \
    x="0.1" \
    islive="true" \
    y="0.1" \
    time="100001" \
    width="0.7" \
    dg="563179898d0528ba4ac1c1f8" \
    title="tag-title-云图" \
    tags="" \
    click:="{
  \"admster\": {
    \"url\": \"http://admster.com/xxx\"
  },
  \"miaozhen\": {
    \"url\": \"http://miaozhencom/xxx\"
  }
}" \
    height="0.7" \
    duration="1000000" \
    v="56c7eeb977895b4c37aef57c"

```

**Comment by williamling** [comment]
@lihaiye  功能已经上线 明天请小叶子一起测一下

**Comment by williamling** [comment]
test环境下测试已经ok 请泽哥部署到正式环境上 @netpi

**Comment by lihaiye** [comment]
测试环境：
http://videojj.com
http://flash.videojj.com/test/index1.html

测试结果：
>前端打点时：添加监控代码功能正常
前端打点添加监控代码，热点列表正常显示监控代码信息
前端打点添加监控代码，监控统计正常
热点列表中修改监控信息，监控统计正常
