### ISSUE TITLE
platform字段被篡改

### ISSUE THREAD

**Issue by hzzhujf** [Venvy-dev/demand#1043]
芒果现在的移动端热点，platform字段值为2。在正常运行了一段时间后，这个字段值被改成了-1。
推测是7月11号或者7月12号被篡改的。老毕看看是不是代码问题。 @bpceee

**Comment by bpceee** [comment]
修改tab列表里的tag会出现此问题，已修复验证上线，测试可以再验证一下。

**Comment by nekronhuang** [comment]
@bpceee 
> 修改tab列表里的tag会出现此问题

`tab列表`是什么？看不懂，差评

**Comment by bpceee** [comment]
@nekronhuang 👎🏽

**Comment by lihaiye** [comment]
测试结果：
>添加移动端热点后，在热点列表中修改tag标题，platform正常
添加移动端热点后，在热点列表中修改热点时间及展示时间，platform正常
添加移动端热点后，在热点列表中填写第三方统计监测代码，platform正常
