### ISSUE TITLE
Ios

### ISSUE THREAD

**Issue by summernini** [Venvy-dev/demand#1045]

**Comment by Zard1096** [comment]
@summernini @shixiaoyanjj 云图点击无响应完成

**Comment by shixiaoyanjj** [comment]
## iOS点播
云图无链接
>
- [ ] 1、到达tag展示时间，云图显示
- [ ] 2、tag显示时间结束，云图消失
- [ ] 3、点击云图，点击无效，视频继续播放，云图不消失
- [ ] 4、拖动进度条至云图出现时间点前，到达tag展示时间，云图显示
