### ISSUE TITLE
Flash

### ISSUE THREAD

**Issue by summernini** [Venvy-dev/demand#1047]

**Comment by lihaiye** [comment]
### Flash：

云图不填写外链时：

- [x] 到达tag展示时间，云图展示正常，showTag统计正常
- [x] 展示时间结束，云图正常消失
- [x] 点击云图，云图不消失，视频继续播放
- [x] 点播：拖动进度条至云图出现时间点前，到达tag点云图继续展示
- [x] 直播：展示时间内刷新视频，云图正常显示
