### ISSUE TITLE
批量打点前端iva删除tag加提醒

### ISSUE THREAD

**Issue by summernini** [Venvy-dev/demand#1055]
对于批量打的tag，在前端IVA删除tag时请加提示，提示用户去控制台进行删除。 #1018

**Comment by hzzhujf** [comment]
因为前端没法判断是否是批量打点，所以我将删除确认的对话框文案从“确认删除？”改成“建议去控制台删除，确认在前端删除吗？”
更新到http://7xjfim.com2.z0.glb.qiniucdn.com/test_Iva.js

**Comment by summernini** [comment]
这样修改不太好，问下eric是否可以传值告诉你是否是全局

**Comment by hzzhujf** [comment]
这里对全局红包做了判断，如果是全局红包，删除时提示改为“该热点为全局热点，如果删除则所有关联视频的热点都将删除。确认删除？”
其他热点类型暂时不做判断

**Comment by summernini** [comment]
需求重新描述一下：前端IVA删除全局热点时，提示用户去控制台删除，并且前端IVA删除功能失效。

**Comment by hzzhujf** [comment]
前端删除去掉了，提示改为“'该热点为全局热点，如果删除则所有关联视频的热点都将删除,请去控制台热点列表删除。'”

**Comment by shixiaoyanjj** [comment]
测试环境
http://7xjfim.com2.z0.glb.qiniucdn.com/test_Iva.js
Iva update at: Mon Jul 18 2016 18:35:53 GMT+0800 (CST)
http://demo.tech.videojj.com/2016/03/11/Test-Demand-Page/?videojjhost=test-03.videojj.com

- [ ] 前端删除非全局热点的红包，仍提示：该热点为全局热点

**Comment by hzzhujf** [comment]
- [x] 前端删除非全局热点的红包，仍提示：该热点为全局热点

**Comment by lihaiye** [comment]
@summernini   Flash是否需要加呢

**Comment by summernini** [comment]
Flash要

**Comment by shixiaoyanjj** [comment]
测试环境
http://7xjfim.com2.z0.glb.qiniucdn.com/test_Iva.js
Iva update at: Tue Jul 19 2016 20:39:30 GMT+0800 (CST)

点击有标题的热点类型的删除按钮报错
![image](https://cloud.githubusercontent.com/assets/16204026/16974004/fec1fd78-4e6a-11e6-8c64-22696dc62567.png)

**Comment by williamling** [comment]
我怎么知道这个tag是全局热点 有什么字段判断么

**Comment by shixiaoyanjj** [comment]
@summernini 
H5前端iva已实现需求，测试通过
需要flash实现需求可另开issues跟踪
