### ISSUE TITLE
[控制台]数据统计下新增视频统计

### ISSUE THREAD

**Issue by vickymin** [Venvy-dev/demand#1060]

**Comment by vickymin** [comment]
[测试地址](http://test-07.videojj.com/)

A 选择所有栏目
![image](https://cloud.githubusercontent.com/assets/14046993/17162796/bd494bea-53eb-11e6-96a8-fd19e3d1c20c.png)
[ ] 8个彩色框数据显示正常
[ ] table数据显示正常
[ ] 图表显示正常

B 选择特定栏目，不选择特定视频
![image](https://cloud.githubusercontent.com/assets/14046993/17162854/37aeb4a6-53ec-11e6-920a-3e15af8a9425.png)
[ ] 8个彩色框数据显示正常
[ ] table数据显示正常
[ ] 图表显示正常

C 选择特定栏目，选择特定视频
![image](https://cloud.githubusercontent.com/assets/14046993/17162865/4e926ece-53ec-11e6-9e52-702d7f092118.png)
[ ] 8个彩色框数据显示正常
[ ] table数据显示正常
[ ] 图表显示正常

D 选择指定日期
![image](https://cloud.githubusercontent.com/assets/14046993/17162877/5f6b29c0-53ec-11e6-89d0-56c82d8e5142.png)
[ ] 8个彩色框数据显示正常
[ ] table数据显示正常
[ ] 图表显示正常

E tab之间切换
![image](https://cloud.githubusercontent.com/assets/14046993/17162887/7a0a751a-53ec-11e6-8235-ff4522a0d0a6.png)
[ ] 可正常切换

**Comment by lihaiye** [comment]
http://test-07.videojj.com/  测试通过
在实时数据页面，选择了栏目以及视频后，切换至信息层统计页面，未保留已选的视频 的问题，已经重新提交ISSUES，不影响上线。
