### ISSUE TITLE
官网主页改版

### ISSUE THREAD

**Issue by virgoone** [Venvy-dev/demand#1061]
测试地址：[http://front.test.videojj.com:10081/](http://front.test.videojj.com:10081/)

**Comment by lihaiye** [comment]
- [ ] 1、合作平台/APP中：凤凰网、虎扑体育、雷锋网、游久网的外跳地址不匹配
- [ ] 2、浏览器：firefox 46.0.1，顶部的DEMO视频无法打开
- [ ] 3、傲游云浏览器，顶部示例内容显示未居中

**Comment by virgoone** [comment]
3可以打开 

![image](https://cloud.githubusercontent.com/assets/8540582/17014047/dbe9a694-4f54-11e6-98d6-374243713caa.png)
这个情况是因为浏览器没有装flash
