### ISSUE TITLE
[Mqtt]点播视频内红包打点后从控制台删除无效

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#1063]
测试环境
http://dev.videojj.com/
http://demo.tech.videojj.com/2016/03/11/Test-Demand-Page/?videojjhost=dev.videojj.com

问题描述
>在视频内添加mqtt红包
在控制台删除红包
红包显示已下线
前端红包仍显示，未删除

**Comment by iEricKoh** [comment]
resolved
