### ISSUE TITLE
红包支持批量打点功能 - redis keys()方法重复调用多次

### ISSUE THREAD

**Issue by iEricKoh** [Venvy-dev/demand#1066]
related ticket #1018

**Comment by pipi32167** [comment]
昨天想了个方案，可以尝试使用redis hash来处理这个问题，不过改动会比较大：

1、创建tag：hset live_tag:[videoId] [tagId] [expireTime]，并将live_tag:[videoId]加入到一个live_tag_set里面去。
2、获取video的所有tag：hgetall live_tag:[videoId]，然后检查对应的expireTime
3、启动一个定时任务，定时检查live_tag_set，清理失效的tag：hdel live_tag:[videoId] [tagId]

**Comment by pipi32167** [comment]
@alanyang @zhenkunou @netpi @iEricKoh

**Comment by iEricKoh** [comment]
@pipi32167 谢谢你提供的解决方法。

只是目前对于live_tag的这个key, 后面不仅仅可以接``videoId``。

当前的live_tag, 可能会有如下的形式：
````
// 此处的id，可能为video id, channel id, project id.
live_tag: [id] [tagId]
````

对于批量投放的红包来说，也可能存在同时``按视频(video id)``，``按栏目(channel id)``，``按项目(project id)``投放。

所以我们不得不，重复执行``keys()``方法三次，分别检索上面提到的三种情况。

目前我已经做了修改，把 `` keys()``方法修改到最多调用三次。

**Comment by pipi32167** [comment]
修改为这样呢？只需要hgetall 3次
```
live_tag:[videoId|projectId|channelId] [tagId] [expireTime]
```

**Comment by iEricKoh** [comment]
@pipi32167 谢谢，但是我大不明白你说的方法。可以等有空我们讨论一下。

**Comment by iEricKoh** [comment]
fixed
