### ISSUE TITLE
解决缓存KEYS *策略

### ISSUE THREAD

**Issue by netpi** [Venvy-dev/demand#1070]

**Comment by netpi** [comment]
### 本次更新解决缓存性能问题

* 修正打点/通投 刷新后不现实bug ,该项目已发布到 test-13.videojj.com


> 请 @shixiaoyanjj 测试  --  @summernini

**Comment by shixiaoyanjj** [comment]
![image](https://cloud.githubusercontent.com/assets/16204026/17128282/23f4e8e4-533e-11e6-8725-77740b8c40cf.png)
![image](https://cloud.githubusercontent.com/assets/16204026/17128283/27ec34ca-533e-11e6-8708-cc9aeca15ad0.png)
test-13.videojj.com请求失败

**Comment by netpi** [comment]
@shixiaoyanjj 已修复 再试下

**Comment by shixiaoyanjj** [comment]
问题描述
>1、前端添加mqtt红包，刷新视频，mqtt推送两个红包
>2、前端删除mqtt红包后（控制台热点已下线），刷新视频，mqtt仍推送红包

![image](https://cloud.githubusercontent.com/assets/16204026/17134693/4b7c8a78-535e-11e6-92eb-30865cec7d4b.png)

**Comment by netpi** [comment]
删除问题已修复 请测试 @shixiaoyanjj

**Comment by shixiaoyanjj** [comment]
## 批量红包测试结果
>1、
- [ ] 添加项目红包，前端显示红包
- [ ] 添加栏目红包，前端显示红包
- [ ] 添加视频红包，前端显示红包

>2、
- [ ] 添加项目红包，前端播放视频，显示红包
- [ ] 添加栏目红包，前端播放视频，显示红包
- [ ] 添加视频红包，前端播放视频，显示红包

>3、
- [ ] 控制台删除视频红包 前端红包消失 
- [ ] 控制台删除栏目红包 前端红包消失
- [ ] 控制台删除项目红包 前端红包消失

## 前端红包测试结果
- [ ] 前端添加红包，前端显示红包
- [ ] 前端添加红包，刷新视频，前端显示红包
- [ ] 前端删除红包，前端红包消失

**Comment by shixiaoyanjj** [comment]
剩余问题
>同一视频添加两个红包，刷新视频后只推送一个红包

**Comment by shixiaoyanjj** [comment]
剩余问题
>同视频添加2个红包，删除1个红包，刷新视频所有红包不显示

**Comment by shixiaoyanjj** [comment]
http://test-13.videojj.com/
测试通过
