### ISSUE TITLE
PPTV需求：定制开发抽奖功能（Flash）

### ISSUE THREAD

**Issue by summernini** [Venvy-dev/demand#1078]
### 原型
https://modao.cc/app/f33e7187714952c3b7008daffd83bf49f93105ad

### 产品
@chndyyang 

### 说明
http://note.youdao.com/share/?id=2e883a13fa52337de2164e6438cc4695&type=note

### 排期，Deadline:8/5
![1](https://cloud.githubusercontent.com/assets/17739064/17172502/fda2ed0e-5427-11e6-8802-9576a043ad6b.png)

@iEricKoh 由于这个功能客户要的紧需要在8月6日之前做好，麻烦你先帮忙做下这个吧~感谢~ 有疑问请咨询老杨。

@edward32tnt 淳煜做下投票的后端

**Comment by iEricKoh** [comment]
@chndyyang 关联投票是什么？这个 dropdown 中数据的来源是投票云窗库中的资源？

![screenshot_2016-07-27_16-24-45](https://cloud.githubusercontent.com/assets/8081074/17168757/bf91c000-5416-11e6-97a1-c499eaed68c2.png)

**Comment by iEricKoh** [comment]
@chndyyang 请再让我知道抽奖底图、抽奖奖品图这两张图片的 width, height.

**Comment by iEricKoh** [comment]
> 关联投票是什么？这个 dropdown 中数据的来源是投票云窗库中的资源？

是的，dropdown 中的数据来源是投票云窗库中的资源。

> 抽奖底图、抽奖奖品图这两张图片的 width, height?

暂时无法决定，目前先任意设定

**Comment by iEricKoh** [comment]
@edward32tnt @williamling @alanyang 以下是关于抽奖model的字段。有发生修改会让你们知道。

````
{
  cat: 11,
  title // 抽奖标题
  pic: [ { url: 'http://' } ] //抽奖奖品图
  desc // 抽奖描述
  lotto: {
    backgroundPic: { // 抽奖底图
      url: {
        type: String
      }
    },
    winnerNum: { // 抽奖人数
      type: Number
    },
    vote: { // 关联投票
      type: Schema.Types.ObjectId, ref: 'Dg'
    } 
  }
}
````

**Comment by iEricKoh** [comment]
Hey @williamling @edward32tnt @shixiaoyanjj @lihaiye,

你们可以访问 [test-03 server](http://test-03.videojj.com/console/projects/55ae1949830906a824970643/resource_lottos) 查看创建抽奖资源的效果。

![video video _ _](https://cloud.githubusercontent.com/assets/8081074/17285088/fce0f9d2-57f2-11e6-84e8-56056b1cd12c.png)

**Comment by lihaiye** [comment]
- [ ] 中奖人数可输入负值或非整数数字，需加校验
![image](https://cloud.githubusercontent.com/assets/17242849/17286257/fe952b74-57fa-11e6-8d83-ede9fd124fa8.png)

**Comment by chndyyang** [comment]
@iEricKoh 如果没关联投票，请不让用户建立抽奖资源

**Comment by shixiaoyanjj** [comment]
测试结果

- 如已结束的投票是否需要过滤
![image](https://cloud.githubusercontent.com/assets/16204026/17286752/0b47a48e-57fe-11e6-8966-dc72f1c954c5.png)

**Comment by iEricKoh** [comment]
@chndyyang 已修复。

![screenshot_2016-08-01_16-26-44](https://cloud.githubusercontent.com/assets/8081074/17288006/5bf8e698-5805-11e6-8d18-e0b3bff5818e.png)

**Comment by iEricKoh** [comment]
> 没有中奖名单按钮

@shixiaoyanjj 我不知道还有这个 feature.
@chndyyang 刚刚创建好的资源如何知道中奖名单？

**Comment by iEricKoh** [comment]
> 没有中奖名单按钮

@shixiaoyanjj 已添加，访问[test-03](http://test-03.videojj.com/)查看最新修改

![video video _ _](https://cloud.githubusercontent.com/assets/8081074/17352091/82e07a84-5966-11e6-8e45-7e4f9a49574f.png)

**Comment by williamling** [comment]
@iEricKoh  如果已经抽奖完成 
/api/dgs?cat=11&project=55c1d80a958842b46ccee1df
请求的dg数据里能否带上中奖数据 并且加上已经抽过奖的状态

**Comment by williamling** [comment]
@iEricKoh 新建抽奖底图和抽奖奖品图时 能不能去掉上传图片后 裁剪这步骤 
目前裁剪的限制导致上传图片的大小和比例都达不到设计的要求

**Comment by iEricKoh** [comment]
Hi William,

你提的要求已经完成，现在图片 upload 时不要求用户 crop.

Thanks,
Eric

2016-08-04 17:02 GMT+08:00 williamling <notifications@github.com>:

**Comment by iEricKoh** [comment]
- [ ] 导出中奖名单 CSV

**Comment by williamling** [comment]
@lihaiye  eric和Edward已经合到dev上了 请测完 然后让泽哥合到master上
