### ISSUE TITLE
【后台-数据】切换数据页面，已选视频信息未保留

### ISSUE THREAD

**Issue by lihaiye** [Venvy-dev/demand#1079]
#1060 

测试地址：
>http://test-07.videojj.com/

问题描述：
>数据统计页面：在实时数据页面，选择了栏目以及视频后；切换至信息层统计页面，未保留已选的视频

期望表现：
>切换页面时，保留上次的视频选择信息

![image](https://cloud.githubusercontent.com/assets/17242849/17173477/aa6973e6-542d-11e6-91ae-323ccc123720.png)

**Comment by vickymin** [comment]
[测试地址](http://test-07.videojj.com/)
@lihaiye

**Comment by lihaiye** [comment]
http://test-07.videojj.com/  测试通过

**Comment by lihaiye** [comment]
http://dev.videojj.com/  测试通过

**Comment by lihaiye** [comment]
正式环境测试通过
