### ISSUE TITLE
【控制台】云泡功能开关未屏蔽，且新建应用后默认为开启状态

### ISSUE THREAD

**Issue by lihaiye** [Venvy-dev/demand#1080]
测试环境：
http://videojj.com/

问题描述：
#898 中要求暂时屏蔽动泡功能
但目前控制台仍然显示 云泡开关按钮，且新建应用后，云泡功能默认为开启状态

![image](https://cloud.githubusercontent.com/assets/17242849/17205883/88d9a36a-54df-11e6-908f-f9a18719295f.png)

**Comment by bpceee** [comment]
test-04已部署

**Comment by lihaiye** [comment]
http://test-04.videojj.com/  
测试通过，应用管理中已屏蔽云泡功能开关

（PS：若以前已开启云泡的应用，屏蔽后也会将云泡功能关闭）

**Comment by lihaiye** [comment]
http://dev.videojj.com/  测试通过

**Comment by lihaiye** [comment]
正式环境测试通过
