### ISSUE TITLE
管理员和实时数据页面：条形图增加百分比

### ISSUE THREAD

**Issue by vickymin** [Venvy-dev/demand#1081]

**Comment by vickymin** [comment]
[测试地址](http://test-07.videojj.com/)

A 超级管理员页面
- [] 百分比和热点类型正常显示

B 实时数据（可选择所有栏目及具体视频）
- [] 百分比和热点类型显示正常
- [] 选择所有栏目正常显示
- [] 选择不同项目，不同栏目下的视频正常显示

**Comment by lihaiye** [comment]
http://test-07.videojj.com/ 测试通过
#1085不影响上线，已提交新issues

**Comment by lihaiye** [comment]
测试通过

**Comment by lihaiye** [comment]
正式环境测试通过
