### ISSUE TITLE
【后台-数据】实时数据页面：实时热点条形对比图中，部分信息层名称不显示

### ISSUE THREAD

**Issue by lihaiye** [Venvy-dev/demand#1085]
#1081
测试环境：http://test-07.videojj.com/

问题描述：
>数据统计-实时数据页面：实时热点条形对比图中，部分信息层名称不显示，需要鼠标点上去才显示
（可能是由于空间不足）

![image](https://cloud.githubusercontent.com/assets/17242849/17292298/aec42bec-581b-11e6-9140-516f9388d152.png)

**Comment by vickymin** [comment]
[测试地址](http://test-07.videojj.com)
@lihaiye

**Comment by lihaiye** [comment]
http://test-07.videojj.com/ 测试通过

**Comment by lihaiye** [comment]
http://dev.videojj.com/  测试通过

**Comment by lihaiye** [comment]
正式环境测试通过
