### ISSUE TITLE
ued revision  －－ ued改版

### ISSUE THREAD

**Issue by 794485409** [Venvy-dev/demand#1092]
改版后的ued采用统一框架，不同内容的形式，所以6个页面除了内容不同，其他都一样，推荐重点测下zealer页面就可以，其他页面过一下就行。
zealer页面比其它5个页面多了一个颜色配置

http://front.test.videojj.com:10081/ued/zealer/
http://front.test.videojj.com:10081/ued/red/
http://front.test.videojj.com:10081/ued/vote/
http://front.test.videojj.com:10081/ued/card/
http://front.test.videojj.com:10081/ued/cartoon/
http://front.test.videojj.com:10081/ued/energy/

@shixiaoyanjj

**Comment by shixiaoyanjj** [comment]
- [ ] 热门应用排行的主题和功能不应有hover变成小手的效果

![image](https://cloud.githubusercontent.com/assets/16204026/17353253/84ec0dca-5970-11e6-976f-b618b14fae0f.png)

**Comment by shixiaoyanjj** [comment]
- [ ] 缩放浏览器，页面未自适应显示

![image](https://cloud.githubusercontent.com/assets/16204026/17353407/dcf4f2a6-5971-11e6-892c-3d80e7cc8171.png)

![image](https://cloud.githubusercontent.com/assets/16204026/17353350/6e24c6da-5971-11e6-8a09-1ee1055a601e.png)

**Comment by shixiaoyanjj** [comment]
- [ ] 遨游浏览器，预览窗口从页面顶部出现

![image](https://cloud.githubusercontent.com/assets/16204026/17354184/a897c2b6-5978-11e6-8ef1-3d944a51c1cf.png)

**Comment by shixiaoyanjj** [comment]
@794485409  修复后请通知测试验证哦

**Comment by 794485409** [comment]
这个页面不要自适应

**Comment by 794485409** [comment]
@shixiaoyanjj 快来测试!!!

**Comment by shixiaoyanjj** [comment]
![image](https://cloud.githubusercontent.com/assets/16204026/17519096/108750ae-5e7d-11e6-9d8a-0d338e0d7b76.png)

## 重现方法
>滚动页面，应用名称隐藏后，点击预览
![image](https://cloud.githubusercontent.com/assets/16204026/17518986/afc83440-5e7c-11e6-89af-941b409062a9.png)

**Comment by 794485409** [comment]
这不是bug，是你太挑！
