### ISSUE TITLE
[控制台]超级管理员新增指标

### ISSUE THREAD

**Issue by vickymin** [Venvy-dev/demand#1098]

**Comment by vickymin** [comment]
[测试地址](http://test-07.videojj.com/admin/#/)

- [ ] 右上角时间选择，显示正常
- [ ] 更新ui颜色，显示正常

**Comment by lihaiye** [comment]
http://test-07.videojj.com/  测试通过

**Comment by lihaiye** [comment]
http://dev.videojj.com/ 测试通过
