### ISSUE TITLE
投票抽奖 - 导出中奖名单csv

### ISSUE THREAD

**Issue by iEricKoh** [Venvy-dev/demand#1099]
related ticket https://github.com/Venvy-dev/demand/issues/1078

http://note.youdao.com/share/?id=2e883a13fa52337de2164e6438cc4695&type=note

**Comment by iEricKoh** [comment]
@lihaiye @shixiaoyanjj 你们可以访问[http://test-03.videojj.com/](http://test-03.videojj.com/)查看到关于最新修改。

![screenshot_2016-08-08_17-21-48](https://cloud.githubusercontent.com/assets/8081074/17476637/9ba1e356-5d93-11e6-9980-08936cdd9e3f.png)

**Comment by lihaiye** [comment]
http://test-03.videojj.com/ 测试通过
