### ISSUE TITLE
[控制台]tag编辑后保存坐标被修改为默认值

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#1101]
测试环境
>http://videojj.com/

问题描述
>添加热点后，在控制台热点管理中编辑tag后保存
保存后坐标默认为：（x: 0.05, y: 0.05）

由于影响线上运营，需要紧急修复上线
已通知运营不要做编辑热点的操作

**Comment by iEricKoh** [comment]
问题原因: tag 中的信息在调用``iva.previewTag(tag)``的时候会被修改。
解决方法：调用 ``iva.previewTag(copy(tag))``时，传递一份新 clone 的 tag 信息给 iva.

**Comment by shixiaoyanjj** [comment]
dev.videojj.com测试通过
