### ISSUE TITLE
[控制台]新增栏目统计

### ISSUE THREAD

**Issue by vickymin** [Venvy-dev/demand#1102]

**Comment by vickymin** [comment]
[测试地址](http://test-07.videojj.com/) 控制台--新增项目统计
@lihaiye 

- [ ] 切换栏目数据正常变化
- [ ] 切换视频数据正常变化
- [ ] 选择时间数据正常变化

**Comment by lihaiye** [comment]
测试地址：http://test-07.videojj.com/

**问题：**
- [ ] 视频播放来源地域分布图中，”上海“地区在图中不显示

![image](https://cloud.githubusercontent.com/assets/17242849/17884743/7fd1ce1a-694c-11e6-9c5c-957035253387.png)

**Comment by vickymin** [comment]
@lihaiye 问题已经修复，在dev环境中

**Comment by lihaiye** [comment]
http://dev.videojj.com/测试通过

**Comment by lihaiye** [comment]
http://videojj.com/ 测试通过
