### ISSUE TITLE
[控制台]视频管理-热点列表新增时间选项

### ISSUE THREAD

**Issue by vickymin** [Venvy-dev/demand#1104]

**Comment by vickymin** [comment]
[测试地址](http://test-07.videojj.com/) 控制台--视频管理--选择具体视频--底部视频内热点列表
@lihaiye 

- 新增时间选择
- [ ] 切换时间，热点展示数正常变动
- [ ] 切换时间，热点点击数正常变动
- [ ] 切换时间，外链点击数正常变动

- 修复bug：
- [ ] 选择信息层类型，正常显示

**Comment by lihaiye** [comment]
http://test-07.videojj.com/  测试通过

**Comment by lihaiye** [comment]
http://dev.videojj.com/ 测试通过
