### ISSUE TITLE
[控制台]统一指标

### ISSUE THREAD

**Issue by vickymin** [Venvy-dev/demand#1105]

**Comment by vickymin** [comment]
[测试地址](http://test-07.videojj.com/)
@lihaiye 

- 超级管理员顶部指标更新，页面中部新增热点曝光uv
- 项目概览指标更新
- 数据统计顶部指标更新
- 视频统计顶部指标更新

**Comment by lihaiye** [comment]
**测试结果：**
- [ ] 超级管理员顶部指标更新，页面中部新增热点曝光uv显示正常
- [ ] 项目概览指标更新 显示正常
- [ ] 数据统计顶部指标更新 显示正常
- [ ] 视频统计顶部指标更新 显示正常

其他问题：
数据统计、视频统计页面顶部指标更新后，下方的明细表指标名称没有修改。大林确认本次暂不修改明细表内容，等之后再修改。

http://test-07.videojj.com/ **测试通过**

**Comment by lihaiye** [comment]
http://dev.videojj.com/ 测试通过
