### ISSUE TITLE
封禁帐号功能

### ISSUE THREAD

**Issue by netpi** [Venvy-dev/demand#1108]

**Comment by netpi** [comment]
帐号封禁之后
无法操作所有和权限有关的功能
比如`打点` `编辑` 等等

测试地点 test-12.videopls.com

@shixiaoyanjj

**Comment by netpi** [comment]
### 测试流程 @shixiaoyanjj 
1 , 通知 netpi 要封禁帐号的邮箱
2 , 封禁之后 测试打点 编辑等需要权限的功能

**Comment by netpi** [comment]
逻辑已经改成 无法登录

**Comment by lihaiye** [comment]
测试地址：
http://test-13.videojj.com/

**测试结果：**
帐号被封禁后：
>无法登陆该帐号，提示：帐号不存在
原来已添加的热点不受影响

封禁的帐号解封后：可正常进行打点，编辑，添加资源等操作

**Comment by lihaiye** [comment]
### 8月16日WEB端测试结果：

测试地址：http://test-13.videojj.com/

被封禁后：
>1、对应应用下，封禁前添加的热点不显示
2、管理员帐号无法打点，资源不显示（报错：{"status":500,"msg":"error base64 appkey :undefined"}）
3、编辑帐号无法打点，资源不显示
4、控制台其他页面均可查看使用（资源管理、数据统计、应用设置等）
