### ISSUE TITLE
封禁用户 

### ISSUE THREAD

**Issue by netpi** [Venvy-dev/demand#1113]
#1108
TODO
- [x] **后端**接口实现  被封禁用户无法 `打点` `登录` 等
- [ ] 产品经理需要考虑 被封禁用户在客户端的 提示方式
- [ ] 4端端实现产品设计

封禁用户目前**后端**已经完成

### 实现原理

* `user` 表中新增字段 
```
deny:{
   type :Number,
   default:0 // 1 封禁
}
```
* 程序中加入了中间件 deny.js
   * 实现通过appkey获得帐号中deny 实现封禁
   * `post api/video`  `get api/tag` `parse` 等接口都加入了该中间件

* 在auth.service的中间件中加入了 `deny` 字段校验
   * getCurrentUser等需要用户信息接口 会返回 403 

即 : getCurrentUser 接口返回 http status  `403` 表示用户被封禁 .

**Comment by Mancy1011** [comment]
目前的方案是，用简单的提示信息通知用户【后期允许用户登录，并能够操作一部分功能】
封禁用户无法登录，在登录页面显示提示“您的账号试用期已过，请联系support@videopls.com恢复账号功能”，提示不消失
![2016-08-17 1 23 40](https://cloud.githubusercontent.com/assets/17489618/17725420/db8af8b8-647d-11e6-8304-8ccc3332c4f3.png)
请 @summernini 安排一下开发人员和排期，谢谢~

**Comment by summernini** [comment]
@iEricKoh 请eric优先做一下

**Comment by iEricKoh** [comment]
@summernini Okay.

**Comment by iEricKoh** [comment]
Hi @lihaiye @shixiaoyanjj,

你们可以访问 [test-03](http://test-03.videojj.com/account/login/) 查看到最新的修改。

![screenshot_2016-08-18_15-00-27](https://cloud.githubusercontent.com/assets/8081074/17768511/df8786ea-6566-11e6-8a6a-d0052e60795c.png)

**Comment by lihaiye** [comment]
@iEricKoh @netpi    test-03上是否有已封禁的帐号可以进行测试呢，如果没有的话麻烦封禁 hehe4522@163.com 这个帐号方便测试，谢谢~~

**Comment by iEricKoh** [comment]
@lihaiye Yes. 这个用户已经是禁止登录的状态了。你可以访问test-03重新尝试一下。

**Comment by lihaiye** [comment]
**测试结果：**
>用户被封禁后无法登录，提示：您的账号试用期已过，请联系support@videopls.com恢复账号功能

**其他问题：**
- [ ] 该管理员帐号对应的应用下，封禁之前所添加的热点仍然展示
- [ ] 使用应用授权过的编辑帐号，仍然可以在应用下添加热点

**Comment by iEricKoh** [comment]
@summernini 这个 ticket 里面，需要我完成的部分，应该只是@Mancy1011提到的在登录页面中，增加禁止登录的提醒而已吧？

@lihaiye 这一部分如果没问题测试通过请让我知道。

**Comment by summernini** [comment]
@netpi 麻烦回答海叶和eric的问题

**Comment by lihaiye** [comment]
@iEricKoh   被封禁的帐号登录页面中增加禁止登录提醒**测试通过**

编辑帐号以及老的热点目前封禁后暂时不做处理，只限制已封禁的帐号无法登陆、打点

**Comment by iEricKoh** [comment]
Hi Haiye,

修改已经被 merged 进到了 dev branch, 就在两分钟以前。
你可以访问 dev server 查看到最新的修改，也许再过 5 ~ 10 mins 之后。

Thanks,
Eric

2016-08-23 17:08 GMT+08:00 lihaiye <notifications@github.com>:

**Comment by lihaiye** [comment]
测试环境：http://dev.videojj.com/
@iEricKoh DEV环境下，被封禁的帐号登陆时，缺少上方的提示内容 ：**您的账号试用期已过，请联系support@videopls.com恢复账号功能** 


![image](https://cloud.githubusercontent.com/assets/17242849/17887256/33e32628-6958-11e6-8c40-99697d4e521a.png)

**Comment by iEricKoh** [comment]
@lihaiye 我想是因为需要 server 重启的原因。

@netpi  请你重启 dev server.

**Comment by iEricKoh** [comment]
@lihaiye Sorry, 我找到另外一个原因了，麻烦5分钟后重试。

**Comment by lihaiye** [comment]
http://dev.videojj.com/ 测试通过
