### ISSUE TITLE
在控制台接入“美洽”

### ISSUE THREAD

**Issue by hzzhujf** [Venvy-dev/demand#1114]
@iEricKoh 
在控制台所有页面接入美洽，例如
http://front.test.videojj.com:10081/
具体接入请咨询 @794485409 
该功能接入没什么开发成本，请在周四上线，周五外出团建，老板要看到远程接客的效果。

**Comment by iEricKoh** [comment]
@summernini 如果这个的 priority 高于 VideoOS, 请让我知道，thx.

**Comment by summernini** [comment]
@iEricKoh 听老朱说接入一下10分钟，如果时间真的很短，可以今天先做这个。
另外 @794485409 志博请把你接入官网的代码提供给eric做参考~

**Comment by 794485409** [comment]
代码在此：
(function(m, ei, q, i, a, j, s) {
      m[a] = m[a] || function() {
          (m[a].a = m[a].a || []).push(arguments)
      };
      j = ei.createElement(q),
          s = ei.getElementsByTagName(q)[0];
      j.async = true;
      j.charset = 'UTF-8';
      j.src = i + '?v=' + new Date().getUTCDate();
      s.parentNode.insertBefore(j, s);
  })(window, document, 'script', '//static.meiqia.com/dist/meiqia.js', '_MEIQIA');
  _MEIQIA('entId', 27418);

这串js代码贴进去自己就会生成dom,如果需要隐藏下面的文字，下面有一个样式：
#MEIQIA-PANEL-HOLDER::after{
    content: "";
    position: absolute;
    bottom:0;
    width: 100%;
    height: 30px;
    background-color: white;
  }
@iEricKoh @summernini

**Comment by iEricKoh** [comment]
@794485409 Thank you.

**Comment by iEricKoh** [comment]
Close cause the change was already available online
