### ISSUE TITLE
[控制台]一跳二跳与全局对比

### ISSUE THREAD

**Issue by vickymin** [Venvy-dev/demand#1119]

**Comment by vickymin** [comment]
[测试地址](http://test-07.videojj.com/console/projects/564d93bfe2b63738009d9ea1/stat)
@lihaiye

**Comment by lihaiye** [comment]
http://test-07.videojj.com/  测试通过 

>数据统计页面：
热点点击率  显示全局对比数据正常
外链点击率  显示全局对比数据正常

**Comment by lihaiye** [comment]
测试地址：http://dev.videojj.com/

- [ ] 风行网：数据统计页面，切换栏目时，页面崩溃

**Comment by lihaiye** [comment]
http://dev.videojj.com/  测试通过
