### ISSUE TITLE
[控制台]管理员页面：新增指标列表

### ISSUE THREAD

**Issue by vickymin** [Venvy-dev/demand#1121]
- 新增项目数
- 新增视频数

**Comment by vickymin** [comment]
[项目列表](http://test-05.videojj.com/admin/#/projects)
- [ ] 刚进入页面的时候，默认是全平台所有项目，按播放量由高到底排列
- [ ] 选择日期，显示在该时间范围内创建的项目列表

[视频列表](http://test-05.videojj.com/admin/#/videos)
- [ ] 刚进入页面的时候，默认是全平台所有项目，按播放量由高到底排列
- [ ] 选择日期，显示在该时间范围内创建的项目列表
- [ ] 可能会存在的问题：每一页的数据显示不全，这是因为测试数据库并不是最新的数据，线上不会存在该问题

**Comment by lihaiye** [comment]
http://dev.videojj.com/  测试通过
