### ISSUE TITLE
【数据】风行网-数据统计页面：切换栏目时，页面崩溃

### ISSUE THREAD

**Issue by lihaiye** [Venvy-dev/demand#1126]
测试地址：
http://dev.videojj.com/
http://videojj.com/

问题描述：
>由于风行网全网上线（移动端8月23日已上线），新增视频数据量大增；在数据统计页面，切换栏目时，页面崩溃

![image](https://cloud.githubusercontent.com/assets/17242849/17961266/4ecad28e-6add-11e6-8cf4-3698caa75acb.png)

**Comment by lihaiye** [comment]
http://dev.videojj.com/  测试通过

（选择测试栏目时，不读取视频列表）

**Comment by vickymin** [comment]
不止风行存在这个问题，目前解决方案，在选择测试栏目时，不读取视频列表
