### ISSUE TITLE
ADMIN 页面的分页不正确

### ISSUE THREAD

**Issue by iEricKoh** [Venvy-dev/demand#1133]
问题反馈来自 @hzzhujf 

ADMIN 的项目列表下，分页页码显示不正确.

当点击最后一页的时候，会发生最后 n 页无任何数据的情况。

例如假设当前页面上显示总共有5000页，会出现可能其实只有4980页存在数据，但是页面却显示当前一共有5000页。

@lihaiye @shixiaoyanjj

**Comment by vickymin** [comment]
@iEricKoh ，看到这个ticket，我觉得问题可能与linz有关，因为分页和获取列表具体数据是分开的api，而在获取列表具体信息的时候，我是将无效的数据排除的，但可能这部分无效的数据是计入count中，我会看下我这里是否可以修改，再告诉你，谢谢！

**Comment by iEricKoh** [comment]
@vickymin 谢谢你的回复。

是的，目前我也看到从 linz 返回数据之后，控制台的代码中有逻辑会把 project 为 null 的数据 exclude 掉，导致页数显示不正确。

这部分剔除数据的逻辑，应该要 linz 那边处理，否则会导致分页的问题。

**Comment by vickymin** [comment]
@iEricKoh , 好的，我会尽快跟进这张ticket，完成后告诉你

**Comment by vickymin** [comment]
@iEricKoh ,问题已经修复，现在在正式环境和测试环境都应该是正确的分页，请确认下

**Comment by iEricKoh** [comment]
@vickymin 谢谢，测试了一下，主要的问题解决了。
hmmm...但是还有一个小问题，如果不好实现的话也可以暂时不修复。

当从 linz 返回了正确的 project list(length = 20)  与 count 之后，控制台的代码有一处逻辑：

我们会根据 project list 中 的 project id 去查询 project 表，此时如果某个 project id 在 project 表中不存在了，就会被剔除掉，导致的结果就是某一页上显示的数据会少于20条。
非常极端的情况下，可能出现返回 linz 返回了 20条 projects 信息，但是实际这 20 条的 projects 中的 id, 在当前 project 都查询不到。

所以如果 linz 在返回 project list 的时候，能够再增加一个条件，判断所有的project id 在 project 表是存在的，应该可以解决问题。

如果修复难度比较大，也可以暂时放一下。
目前看到的问题就是某些页数下，页面上的数据并不一定总是20条而已，例如19条。

**Comment by vickymin** [comment]
@iEricKoh 
能告诉我，比如哪一页存在这个问题吗？方便我调试，谢谢！

**Comment by iEricKoh** [comment]
@vickymin 

比如当前 dev  环境下的 ADMIN 页面，项目列表。第一页，数据只有19条。

**Comment by vickymin** [comment]
@iEricKoh 
我看了下，导致这个问题的原因是dev环境使用的是videojj的测试数据库，其中的project的信息并不是最新的
理论上linz能查询到的project，videojj的正式数据库都应该有对应的数据
videojj的正式环境应该不存在这个问题，如果有的话请告诉我

**Comment by iEricKoh** [comment]
Hi Vicky,

Okay, 应该是你说的，数据库的问题，那这个问题就暂时忽略，谢谢你的修复。

Thanks,
Eric

2016-08-26 17:32 GMT+08:00 Jiepei Min <notifications@github.com>:

**Comment by iEricKoh** [comment]
resolved.
