### ISSUE TITLE
项目列表优化建议

### ISSUE THREAD

**Issue by summernini** [Venvy-dev/demand#1134]
需求描述：对查询项目列表的 API，新增一个查询参数，支持可以通过按照项目名称查询。

**Comment by vickymin** [comment]
@iEricKoh @lihaiye @shixiaoyanjj 

请在该[地址](http://test-05.videojj.com/admin/#/projects)
测试Venvy-dev/demand#1134，Venvy-dev/demand#1132

如果有问题，请及时与我沟通，谢谢

**Comment by shixiaoyanjj** [comment]
搜索关键字超时失败
![image](https://cloud.githubusercontent.com/assets/16204026/18624009/270f2fea-7e76-11e6-8128-1795a1b0ccfe.png)


### TV
> curl "http://test-05.videojj.com/api/projects/all?dateSpan="%"7B"%"7D&kw=TV&pn=0&ps=20&sortParam="%"7B"%"22vv"%"22:-1"%"7D" -H "Pragma: no-cache" -H "Accept-Encoding: gzip, deflate, sdch" -H "Accept-Language: zh-CN,zh;q=0.8" -H "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJfaWQiOiI1Njc4ZWEyODdkOGM5N2RjMDQ0OGYxYzYiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE0NzQyNjYwNDYsImV4cCI6MTQ3NDg3MDg0Nn0.TLODm7IGnr42L6ycqawgu5GcXIPF9f-NtA73r24AVaw" -H "Accept: application/json, text/plain, */*" -H "Referer: http://test-05.videojj.com/admin/" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36" -H "Cookie: gr_user_id=05b5c298-fe3c-45df-aa2a-06fe79057557; _gat=1; _ga=GA1.2.919942047.1473411530; token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJfaWQiOiI1Njc4ZWEyODdkOGM5N2RjMDQ0OGYxYzYiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE0NzQyNjYwNDYsImV4cCI6MTQ3NDg3MDg0Nn0.TLODm7IGnr42L6ycqawgu5GcXIPF9f-NtA73r24AVaw; attemps=0; Hm_lvt_2ede15e90c9e9195590577aefe09db08=1473411529,1473653057,1474167271; Hm_lpvt_2ede15e90c9e9195590577aefe09db08=1474266051; gr_session_id_a07d7b426cc291f1=8a8d8118-60c8-468c-9128-d37b95ae900f" -H "Connection: keep-alive" -H "Cache-Control: no-cache" --compressed




### 视频
> curl "http://test-05.videojj.com/api/projects/all?dateSpan="%"7B"%"7D&kw="%"E8"%"A7"%"86"%"E9"%"A2"%"91&pn=0&ps=20&sortParam="%"7B"%"22vv"%"22:-1"%"7D" -H "Pragma: no-cache" -H "Accept-Encoding: gzip, deflate, sdch" -H "Accept-Language: zh-CN,zh;q=0.8" -H "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJfaWQiOiI1Njc4ZWEyODdkOGM5N2RjMDQ0OGYxYzYiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE0NzQyNjYwNDYsImV4cCI6MTQ3NDg3MDg0Nn0.TLODm7IGnr42L6ycqawgu5GcXIPF9f-NtA73r24AVaw" -H "Accept: application/json, text/plain, */*" -H "Referer: http://test-05.videojj.com/admin/" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36" -H "Cookie: gr_user_id=05b5c298-fe3c-45df-aa2a-06fe79057557; _gat=1; _ga=GA1.2.919942047.1473411530; token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJfaWQiOiI1Njc4ZWEyODdkOGM5N2RjMDQ0OGYxYzYiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE0NzQyNjYwNDYsImV4cCI6MTQ3NDg3MDg0Nn0.TLODm7IGnr42L6ycqawgu5GcXIPF9f-NtA73r24AVaw; attemps=0; Hm_lvt_2ede15e90c9e9195590577aefe09db08=1473411529,1473653057,1474167271; Hm_lpvt_2ede15e90c9e9195590577aefe09db08=1474266051; gr_session_id_a07d7b426cc291f1=8a8d8118-60c8-468c-9128-d37b95ae900f" -H "Connection: keep-alive" -H "Cache-Control: no-cache" --compressed

**Comment by shixiaoyanjj** [comment]
- [ ] 搜索结果未包含统计数量

![image](https://cloud.githubusercontent.com/assets/16204026/18624038/5ee44e0a-7e76-11e6-933d-343d7ca422aa.png)

**Comment by shixiaoyanjj** [comment]
- [ ] 仅筛选日期结果为空 

![image](https://cloud.githubusercontent.com/assets/16204026/18624059/a62a7640-7e76-11e6-9ac1-9941a8fbdc49.png)

**Comment by vickymin** [comment]
@shixiaoyanjj 
筛选日期结果为空，是因为测试和正式数据库不同步导致，线上没有这个问题

**Comment by vickymin** [comment]
@shixiaoyanjj  搜索关键字超时失败 已修复

**Comment by vickymin** [comment]
@shixiaoyanjj 搜索结果未包含统计数量, 这个再提个issue吧，其他的修复了麻烦再看下，今天上线一起上了~

**Comment by vickymin** [comment]
@shixiaoyanjj 修复了，并增加了带关键字搜索时，也可筛选时间

**Comment by shixiaoyanjj** [comment]
http://test-05.videojj.com/测试通过
