### ISSUE TITLE
新增ued页面，market应用添加

### ISSUE THREAD

**Issue by 794485409** [Venvy-dev/demand#1135]
地址：front.test.videojj.com:10081/ued/gray
front.test.videojj.com:10081/ued/tvc
front.test.videojj.com:10081/ued/fun
front.test.videojj.com:10081/ued/abv
front.test.videojj.com:10081/ued/abcard
front.test.videojj.com:10081/ued/h5
front.test.videojj.com:10081/ued/baike
front.test.videojj.com:10081/ued/poster
front.test.videojj.com:10081/ued/carousel
front.test.videojj.com:10081/ued/imgvote
front.test.videojj.com:10081/ued/actimg
front.test.videojj.com:10081/ued/shop

front.test.videojj.com:10081/market
新增热门功能

**Comment by 794485409** [comment]
![image](https://cloud.githubusercontent.com/assets/11987764/18003276/390cf66a-6bbf-11e6-98d9-e2057c3a9ea5.png)
@shixiaoyanjj

**Comment by lihaiye** [comment]
- [ ] 1、热门应用中：手机卡牌，打开后显示的是”收集卡牌“
![image](https://cloud.githubusercontent.com/assets/17242849/18075079/5ea0df4e-6ea4-11e6-9f87-65733feeaa91.png)
