### ISSUE TITLE
【控制台】热点管理页面，搜索功能缺失

### ISSUE THREAD

**Issue by lihaiye** [Venvy-dev/demand#1138]
测试地址：
http://videojj.com/console

问题描述：
>热点管理页面，搜索功能没有了（原来有的），请排查~

![image](https://cloud.githubusercontent.com/assets/17242849/18164601/6225467a-7073-11e6-9f5c-c0babf22251c.png)

**Comment by iEricKoh** [comment]
@vickymin 我看到这是16天之前你在完成 [#1110](https://github.com/Venvy-dev/videojj/blame/dev/client/console/project/tagList/tagList.jade) 的时候把 search 的 东西注释掉了。

你可以回忆一下当初为什么会有这个[操作](https://github.com/Venvy-dev/videojj/commit/179d26dbaa0c05820d53b9f065d3d77d1460f877#diff-96fae72d5462c80a943fee14d04ff205R25)，如果是误操作请修改回来。如果是有这样的一个需求修改，麻烦跟 @lihaiye 讲一下，thanks. @summernini

**Comment by vickymin** [comment]
@iEricKoh @lihaiye ,不好意思，应该是误操作，我今天会修改回来
麻烦你们了

**Comment by vickymin** [comment]
@iEricKoh @lihaiye ，已经修复回来，并上正式环境了，这个bug可以close了，谢谢！

**Comment by lihaiye** [comment]
正式环境测试通过
