### ISSUE TITLE
[控制台]管理员页面：新增指标列表

### ISSUE THREAD

**Issue by vickymin** [Venvy-dev/demand#1139]
- 新增热点数
- 新增资源数

**Comment by vickymin** [comment]
[测试地址](http://test-05.videojj.com/admin/#/videos)

[ ] 刚进入页面的时候，默认是全平台所有视频，按播放量由高到底排列
[ ] 选择日期，显示在该时间范围内创建的视频列表

暂时没搜索功能

**Comment by lihaiye** [comment]
http://test-05.videojj.com/测试通过

测试环境下有出现页面没有内容的情况，由于是测试服数据，需要等更新到正式环境后再观察~
![image](https://cloud.githubusercontent.com/assets/17242849/18466315/cb511de6-79cd-11e6-9361-ba3e9d449103.png)

**Comment by lihaiye** [comment]
http://dev.videojj.com/ 测试通过
