### ISSUE TITLE
控制台投票新增上传图片功能

### ISSUE THREAD

**Issue by summernini** [Venvy-dev/demand#1140]
原型：http://yx.tech.videojj.com/Mushroom/Videojj%E6%8E%A7%E5%88%B6%E5%8F%B0_%E6%B7%BB%E5%8A%A0%E6%8A%95%E7%A5%A8_%E9%80%89%E9%A1%B9%E5%9B%BE%E7%89%87_20160907/#p=添加投票

Deadline:9/15

**Comment by summernini** [comment]
#1082 #1083 #1057 后台配置后记得把接口传给前端三端

**Comment by iEricKoh** [comment]
@Mancy1011 新版SDK跟旧版SDK是什么意思？

![screenshot_2016-09-12_10-25-39](https://cloud.githubusercontent.com/assets/8081074/18422986/6797980c-78d3-11e6-992a-0dd14096a122.png)

**Comment by Mancy1011** [comment]
@iEricKoh 芒果TV新版的app能显示图片投票样式，而之前的版本只能显示无图片样式，这个主要是移动端前端要注意的地方

**Comment by iEricKoh** [comment]
@Mancy1011 Thanks.

另外一个问题：

> 勾选“显示选项图片”，并且上传了图片，前端显示有选项图片样式的投票

有选项图片样式的投票，长什么样子？当前我无法在你的原型里面找到。

**Comment by iEricKoh** [comment]
@lihaiye @shixiaoyanjj 

你们可以访问 [test-03](http://test-03.videojj.com/) 查看本次的修改，谢谢

![screenshot_2016-09-12_18-12-12](https://cloud.githubusercontent.com/assets/8081074/18432455/a138c84c-7914-11e6-927d-a2a3b71290e9.png)

**Comment by iEricKoh** [comment]
@JackeyChen1015 

````
dg.vote.enablePic // 判断投票是否带图片


var optionSchema = new Schema({
  title: String,
  count: { 
    type: Number,
    default: 0
  },
  real: {
    type: Number,
  },
  pic: {  // 新增字段，每个选项对应的图片URL
    type: String 
  },
  base: Number,
  step: Number,
})
````

**Comment by Mancy1011** [comment]
@iEricKoh 有选项图片投票样式如下
![2016-09-13 11 44 50](https://cloud.githubusercontent.com/assets/17489618/18460843/8ba56d3a-79a7-11e6-9abe-8660e43e221c.png)

**Comment by shixiaoyanjj** [comment]
![image](https://cloud.githubusercontent.com/assets/16204026/18502597/7ab85152-7a8a-11e6-978b-5fbf1773fb3b.png)
@图片上传没有剪裁功能吗？

**Comment by iEricKoh** [comment]
@Mancy1011 当前图片无支持 裁剪 功能，如果需要添加请让我知道，thanks.

@shixiaoyanjj

**Comment by Mancy1011** [comment]
@iEricKoh  好的
由于裁剪图片是创建资源的通用功能，所以需要等设计给到所有图片比例后统一开发

**Comment by LSerena21** [comment]
/***
	 * 获取投票 点赞数量
	 */
	"http://test-03.videojj.com/api/dgs/vote/";

Android移动端需要请求这个接口拿到pic（也就是每个投票选项的图片地址），期望后台小伙伴帮忙添加，谢谢。 @iEricKoh

**Comment by iEricKoh** [comment]
@LSerena21 请再让我知道一下你是以什么方式请求该接口的，POST？GET？

**Comment by shixiaoyanjj** [comment]
@Mancy1011 老控制台的图片裁剪功能早已有了，你是理解成video OS了吗？

**Comment by iEricKoh** [comment]
@shixiaoyanjj 她的意思应该是裁剪功能已经有了，但是裁剪功能需要一个比例，当前这个比例未知，哪怕我增加了裁剪功能，也无法确定正确的比例。

**Comment by LSerena21** [comment]
@iEricKoh GET

**Comment by shixiaoyanjj** [comment]
@iEricKoh @Mancy1011 比例在原型中确定是14：15，如果有变化请让我们知道，谢谢

**Comment by iEricKoh** [comment]
@LSerena21 Sorry, 请确定一下你的接口是下面的 1 还是 2？

1. GET http://test-03.videojj.com/api/dgs/vote/
2. GET http://test-03.videojj.com/api/dgs/vote/:id

**Comment by LSerena21** [comment]
是2 @iEricKoh

**Comment by iEricKoh** [comment]
@LSerena21 Okay. 请访问 test-03 再次测试。有问题请让我知道，thanks.

**Comment by iEricKoh** [comment]
> @iEricKoh @Mancy1011 比例在原型中确定是14：15，如果有变化请让我们知道，谢谢

@Mancy1011 需要你确定好图片的 width & height，确定好再让我知道，cheers.

**Comment by iEricKoh** [comment]
> @iEricKoh @Mancy1011 比例在原型中确定是14：15，如果有变化请让我们知道，谢谢

@Mancy1011 需要你确定好图片的 width & height，确定好再让我知道，cheers.

**Comment by Mancy1011** [comment]
@iEricKoh 是我弄错了，是videoOS没有做图片裁剪的功能
请按原型中的图片比例开发，谢谢

**Comment by iEricKoh** [comment]
@Mancy1011 Sorry, 原型中的图片比例是什么，请告诉我，以及你应该告诉我高度与宽度，不需要比例。

**Comment by Mancy1011** [comment]
@iEricKoh 选项图片的宽高比为14:15
由于图片尺寸会在不同的设备上显示不同的大小，所以很难给出具体的高度和宽度

**Comment by iEricKoh** [comment]
@Mancy1011  请问14：15是怎么算出来的？？？

**Comment by Mancy1011** [comment]
@iEricKoh 在效果图中，图片的宽是70，高是75

**Comment by iEricKoh** [comment]
@shixiaoyanjj @Mancy1011 支持 crop 图片的要求已经添加，访问 test-03 查看最新修改，thanks.
![screenshot_2016-09-21_10-20-36](https://cloud.githubusercontent.com/assets/8081074/18695547/21605036-7fe5-11e6-838b-28d13f76437e.png)

**Comment by shixiaoyanjj** [comment]
http://test-03.videojj.com/测试通过

**Comment by iEricKoh** [comment]
resolved.

**Comment by shixiaoyanjj** [comment]
dev.videojj.com上合并后请通知测试验证，谢谢
