### ISSUE TITLE
[控制台]全局项目列表新增指标

### ISSUE THREAD

**Issue by vickymin** [Venvy-dev/demand#1142]
在上方加两个指标：
- 新建用户数
- 新建用户其中的打过热点的用户数

**Comment by vickymin** [comment]
[测试地址](http://test-05.videojj.com/admin/#/projects)
@lihaiye 

![image](https://cloud.githubusercontent.com/assets/14046993/18501851/e382d37e-7a85-11e6-8b67-ba933a3c3c20.png)
页面上方，如上图，选择时间范围后，下划线部分的数字会相应变化

@hzzhujf ，该功能会在中秋之后上线

**Comment by lihaiye** [comment]
http://test-05.videojj.com/   
（Ps:测试环境下近一个月下无数据，需要到线上环境上再观察）

**Comment by vickymin** [comment]
@lihaiye 已上dev，麻烦再看下~

**Comment by lihaiye** [comment]
http://dev.videojj.com/  测试通过
