### ISSUE TITLE
[控制台]管理员页面ui更新

### ISSUE THREAD

**Issue by vickymin** [Venvy-dev/demand#1144]

**Comment by vickymin** [comment]
[测试地址: 控制台--总览--过往数据](http://test-05.videojj.com/admin/#/)
[测试地址: 控制台--总览--实时数据](http://test-05.videojj.com/admin/#/realtime)
@lihaiye 

ui更新

设计稿：
![image](https://cloud.githubusercontent.com/assets/14046993/18613799/5a8783da-7db4-11e6-9832-5a3599ea6bab.png)

**Comment by lihaiye** [comment]
http://test-05.videojj.com/  测试通过

**Comment by vickymin** [comment]
@lihaiye 已上dev，麻烦再看下~

**Comment by lihaiye** [comment]
http://dev.videojj.com/ 测试通过
