### ISSUE TITLE
[控制台]时间范围缺少全部时间的选项

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#1147]
## 问题描述
videojj控制台所有筛选时间范围中都缺少全部时间的选项，导致每次筛选时间后无法选择全部时间，必须刷新页面

![image](https://cloud.githubusercontent.com/assets/16204026/18624248/a2606f0e-7e78-11e6-83a4-194a6e114a26.png)

## 期望
增加全部时间的选项

**Comment by vickymin** [comment]
@shixiaoyanjj 
[测试地址](http://test-05.videojj.com/admin/#/projects)

**Comment by shixiaoyanjj** [comment]
http://test-05.videojj.com/测试通过
注意：仅管理员项目列表增加全部时间选项
