### ISSUE TITLE
【控制台】管理员总览页面：切换时间筛选时有报错

### ISSUE THREAD

**Issue by lihaiye** [Venvy-dev/demand#1148]
测试地址：
http://videojj.com/admin/#/

描述：
管理员-过往数据页面：选择时间段筛选时，出现以下报错

![image](https://cloud.githubusercontent.com/assets/17242849/18696411/72ca5f1a-7feb-11e6-8bf5-36612421878f.png)

![image](https://cloud.githubusercontent.com/assets/17242849/18696404/66820d8e-7feb-11e6-880d-6f7e38c4a5b3.png)

**Comment by vickymin** [comment]
@lihaiye ,该bug没法复现，估计是由于线上的图标库版本更新，所以该bug不存在了。麻烦再验证下，如果的确没了，请close
