### ISSUE TITLE
管理员的项目列表筛选后的页码不正确

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#1151]
测试环境
>http://test-05.videojj.com/admin/#/projects

问题描述
>筛选后数量与页码不一致，如图

![image](https://cloud.githubusercontent.com/assets/16204026/18742122/2d7d67a4-80e5-11e6-93a9-a782d62b7563.png)

**Comment by vickymin** [comment]
@shixiaoyanjj ,正式环境没有这个问题，可能是由于数据库不同步导致的

麻烦你在正式环境再验证下，如果确认不存在这个bug，就把这个issue close掉吧，如果依然有问题，再告诉我

**Comment by shixiaoyanjj** [comment]
问题未重现，关闭此issue
