### ISSUE TITLE
[中国蓝TV]播放视频，未编辑完的IVA窗口未关闭

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#172]
测试地址：
>http://tv.cztv.com/vplay/122670.html
>账号：654805438@qq.com  密码：123456

测试视频：
>

重现位置：
>

重现步骤：
>1.添加云链
2.在编辑窗口打开时
3.播放视频（点击播放或按键盘空格）

期望结果：
>播放视频时，关闭所有IVA互动编辑窗口

相关截图：

**Comment by hzzhujf** [comment]
先关了
确认出现情况再打开吧
