### ISSUE TITLE
[中国蓝TV]暂停视频云链不显示

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#176]
测试地址：
>http://tv.cztv.com/vplay/97343.html

测试视频：
>

重现位置：
>

重现步骤：
>1.云链出现时暂停视频

期望结果：
>暂停视频，IVA层显示

相关截图：

**Comment by hzzhujf** [comment]
按照芒果的需求，暂停广告时不要显示热点，我觉得还是挺合理的，新蓝也按照这个逻辑走吧
