### ISSUE TITLE
[IVA]自定义特效波纹和声波播放时切换进度特效播放后云链显示且不消失

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#213]
测试地址：
>http://tech.videojj.com/test/mongotv_test02/

重现位置 ：
>波纹 02：05
声波 06：06

问题描述：
>1.当波纹或声波特效开始播放时向后拖动进度条
2.云链仍将显示且不消失，但无法打开

![qq 20160202154854](https://cloud.githubusercontent.com/assets/16204026/12743063/f54ed8b2-c9c5-11e5-95c1-29d0a22e69c3.jpg)

![qq 20160202154652](https://cloud.githubusercontent.com/assets/16204026/12743059/ec7187b2-c9c5-11e5-8e5f-c8d74db2cc04.jpg)

**Comment by hzzhujf** [comment]
修复

**Comment by lihaiye** [comment]
Iva version：http://7xjfim.com2.z0.glb.qiniucdn.com/test_Iva.js
Iva update at: Wed Apr 27 2016 11:59:05 GMT+0800 (CST)
验证通过

**Comment by lihaiye** [comment]
**正式环境**
测试地址：http://www.mgtv.com/v/1/1/f/3241543.html
声波显示性出现时间：15:28
Iva update at: Thu Jun 02 2016 15:40:50 GMT+0800 (CST)
声波特效播放时 往前 拖动进度条，热点未消失（能打开信息层）

![image](https://cloud.githubusercontent.com/assets/17242849/15892019/f867ba08-2da9-11e6-8243-be358059a02e.png)

**测试未通过**

**Comment by hzzhujf** [comment]
由于芒果的播放器的bug，这个极端情况修复不了。
