### ISSUE TITLE
[芒果]投票的滚动条样式优化需求

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#216]
![image](https://cloud.githubusercontent.com/assets/16204026/12745769/05ccc61c-c9d6-11e5-9d33-44db7b629cc9.png)

**Comment by shixiaoyanjj** [comment]
![image](https://cloud.githubusercontent.com/assets/16204026/14381824/df83539e-fdbb-11e5-906a-de6be383c5e4.png)
加了广告banner投票结果仍会出现滚动条，客户反馈不认同滚动条的样式，需要UI优化
建议：http://www.htmleaf.com/Demo/201507252297.html

**Comment by summernini** [comment]
现在只要满足能放下4个不出滚动条，撑满即可。优先度高4月11日要给到测试 @hzzhujf

**Comment by shixiaoyanjj** [comment]
芒果仍然要求美化滚动条 @hzzhujf

**Comment by shixiaoyanjj** [comment]
测试点：

- 大于四个投票显示滚动条
- 注意投票前和投票结果两种情况

>点播投票下拉菜单兼容性
- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] IE11
- [ ] IE10
- [ ] 360安全浏览器
- [ ] 360极速浏览器
- [ ] QQ浏览器
- [ ] 猎豹安全浏览器
- [ ] 百度浏览器
- [ ] 搜狗高速浏览器
- [ ] 傲游云浏览器
- [ ] Opera

>直播投票侧滑菜单兼容性
- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] IE11
- [ ] IE10
- [ ] 360安全浏览器
- [ ] 360极速浏览器
- [ ] QQ浏览器
- [ ] 猎豹安全浏览器
- [ ] 百度浏览器
- [ ] 搜狗高速浏览器
- [ ] 傲游云浏览器
- [ ] Opera
