### ISSUE TITLE
无追踪框的隐链ICON为自定义图标时未显示白点

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#229]
问题描述：
>1、编辑热点
2、设置自定义ICON
3、设置为隐链（无追踪框）
4、ICON未显示白点

期望结果：
>隐链的ICON保持显示白点

![qq 20160204120119](https://cloud.githubusercontent.com/assets/16204026/12805531/160ecab8-cb37-11e5-933c-a7abb4ae973c.jpg)

![qq 20160204120137](https://cloud.githubusercontent.com/assets/16204026/12805581/97c2a4e4-cb37-11e5-950e-1122ba7ec915.jpg)

**Comment by lihaiye** [comment]
test环境测试未通过，隐链的ICON未保持显示白点
http://7xjfim.com2.z0.glb.qiniucdn.com/test_Iva.js
Iva update at: Wed Apr 06 2016 17:40:51 GMT+0800 (CST)

![image](https://cloud.githubusercontent.com/assets/17242849/14318300/be8d0e7e-fc3e-11e5-8c52-d3248b31c5bc.png)

**Comment by hzzhujf** [comment]
确实有问题，没考虑到用户设置了自定义icon。

**Comment by shixiaoyanjj** [comment]
测试通过
Iva version：http://7xjfim.com2.z0.glb.qiniucdn.com/test_Iva.js
Iva update at: Mon Apr 11 2016 13:30:49 GMT+0800 (CST)
