### ISSUE TITLE
[爱奇艺III]关闭卡牌云窗，dg展示时间统计接口未实现

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#236]
测试地址：
>http://tech.videojj.com/test/iqy_hero3/

重现位置：
>05：18

问题描述：
>关闭卡牌云窗，dg展示时间统计接口未实现

**Comment by hzzhujf** [comment]
爱奇艺的《康师傅辣味英雄传》是定制代码，不更新了。
