### ISSUE TITLE
[爱奇艺III]卡牌出现时光环形状与卡牌图片不相符

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#237]
测试地址：
>http://tech.videojj.com/test/iqy_hero3/

重现位置：
>05：18

![qq 20160215151220](https://cloud.githubusercontent.com/assets/16204026/13041908/8e2060e4-d3f6-11e5-89e6-f946ad067fd8.jpg)

**Comment by hzzhujf** [comment]
爱奇艺的《康师傅辣味英雄传》是定制代码，不更新了。
