### ISSUE TITLE
[点播]滚动窗口IVA互动层出框

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#307]
测试地址：
>http://honey.hunantv.com/imgotv-mini/template/page/play/play-default.html

问题描述：
>往下滚动页面风车到播放器外面去了
![qq 20160222004330](https://cloud.githubusercontent.com/assets/16204026/13203966/872f9518-d8fe-11e5-9842-9132b67ca019.jpg)

期望结果：
>- [x] 风车
- [x] 广告热点
- [x] 广告信息层
- [x] 投票banner
- [x] 隐性热点追踪框
- [x] 导航广告信息层

**Comment by shixiaoyanjj** [comment]
![qq 20160427111531](https://cloud.githubusercontent.com/assets/16204026/14917685/d5b361e0-0e52-11e6-95c7-29f2748525db.jpg)

**Comment by hzzhujf** [comment]
加了hack，等下次芒果线上更新再测试吧。
下次线上更新我和你说 @shixiaoyanjj

**Comment by shixiaoyanjj** [comment]
- [ ] 风车
- [ ] 广告热点
- [ ] 广告信息层
- [ ] 投票banner
- [ ] 隐性热点追踪框
- [ ] 导航广告信息层
