### ISSUE TITLE
声波显链出现前隐藏视频页面，tag点结束后再回到视频还会出现声波特效

### ISSUE THREAD

**Issue by lihaiye** [Venvy-dev/demand#367]
测试地址：
http://z-tron.cn/play/mgKeyPlay.html?title=xfxz&k=E1yzuXJrg&url=http://7xr5j6.com1.z0.glb.clouddn.com/hunantv0129.mp4

描述：
>声波显链出现之前切换页面，将视频页隐藏
等tag点结束后再回到视频界面，还会出现声波特效

![z5](https://cloud.githubusercontent.com/assets/17242849/13393562/31c5ead0-df1d-11e5-83d1-c429e0440757.png)

**Comment by hzzhujf** [comment]
http://7xjfim.com2.z0.glb.qiniucdn.com/test_Iva.js   已经更新

**Comment by lihaiye** [comment]
Iva update at: Wed Apr 06 2016 17:40:51 GMT+0800 (CST)

测试环境测试通过

**Comment by lihaiye** [comment]
正式环境测试通过
