### ISSUE TITLE
搜狗、Edge浏览器，在视频中拉一个框后点击灵悟一下报错

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#380]
测试地址：
>http://videojj.com/vor/

问题描述：
>搜狗浏览器，在视频中拉一个框后点击灵悟一下报错
Edge浏览器，在视频中拉一个框后截的图是黑的点了灵悟后没有灵悟成功的返回结果

![image](https://cloud.githubusercontent.com/assets/16204026/13457704/7c794940-e0a4-11e5-9021-1812e9da65bb.png)

![image](https://cloud.githubusercontent.com/assets/16204026/13457825/115388be-e0a5-11e5-85f6-b1db70d96448.png)

**Comment by edward32tnt** [comment]
一工这里还没修
