### ISSUE TITLE
混合广告编辑窗口分类的下拉菜单选项字体显示白色

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#386]
![qq 20160309112428](https://cloud.githubusercontent.com/assets/16204026/13624559/45590450-e5ea-11e5-94cf-124d79b8d386.jpg)

**Comment by hzzhujf** [comment]
请用http://z-tron.cn/play/page/TestPlayer.html 测试

**Comment by shixiaoyanjj** [comment]
未通过测试
http://z-tron.cn/play/page/TestPlayer.html
http://7xjfim.com2.z0.glb.qiniucdn.com/test_Iva.js
Iva update at: Wed Apr 06 2016 17:40:51 GMT+0800 (CST)
![image](https://cloud.githubusercontent.com/assets/16204026/14343387/2c030f96-fcd3-11e5-9be4-e31cb11133e7.png)

**Comment by hzzhujf** [comment]
修复

**Comment by shixiaoyanjj** [comment]
测试通过
Iva version：http://7xjfim.com2.z0.glb.qiniucdn.com/test_Iva.js
Iva update at: Mon Apr 11 2016 13:30:49 GMT+0800 (CST)
