### ISSUE TITLE
[video++]侧滑菜单中‘商务合作’信息点击出现的是无标题页面

### ISSUE THREAD

**Issue by lihaiye** [Venvy-dev/demand#407]
测试地址：
>http://videojj.com/help/

描述：
>侧滑菜单中‘商务合作’信息点击出现的是无标题页面
![image](https://cloud.githubusercontent.com/assets/17242849/13657735/7e04a9e0-e6ac-11e5-86e7-7d9c262c23f2.png)

**Comment by WalterGuo** [comment]
[测试地址](http://front.test.videojj.com:10081)

**Comment by lihaiye** [comment]
http://front.test.videojj.com:10081/  验证通过
