### ISSUE TITLE
[video++]已登录状态底部的开始使用栏需优化

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#408]
测试地址：
>http://videojj.com/

问题描述：
>已登录状态，底部的邮箱输入栏没有作用，建议优化底部的功能
![image](https://cloud.githubusercontent.com/assets/16204026/13657720/665df062-e6ac-11e5-90d8-baf239ba9658.png)

**Comment by virgoone** [comment]
此section以取消，请关掉问题

**Comment by lihaiye** [comment]
主页已改版，此section已取消，此单关闭
