### ISSUE TITLE
[video++]邮箱已注册提示中有外链的文字不显示可点击状态

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#409]
测试地址：
>http://videojj.com/

问题描述：
>忘记密码和直接登录字样未显示可点击状态
![qq 20160310105131](https://cloud.githubusercontent.com/assets/16204026/13657928/12ce737a-e6ae-11e5-85ac-e4339a9a3db3.png)

**Comment by WalterGuo** [comment]
已修改为：
![image](https://cloud.githubusercontent.com/assets/8540582/14875034/06779c80-0d39-11e6-8f4e-31e8216b9f7e.png)

**Comment by lihaiye** [comment]
test环境和正式环境都测试通过
