### ISSUE TITLE
[video++]Firefox打开灵眸页面显示异常

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#423]
测试地址：
>http://videojj.com/vcr/

测试环境：
>Firefox 44.0.2

![qq 20160310161815](https://cloud.githubusercontent.com/assets/16204026/13663324/b9367474-e6db-11e5-8da1-3b125455be3d.png)
![qq 20160310161820](https://cloud.githubusercontent.com/assets/16204026/13663325/b9374fca-e6db-11e5-87e4-054923aba1b0.jpg)

**Comment by WalterGuo** [comment]
灵眸页面在新的前端项目中已经移除，等待新版设计

**Comment by lihaiye** [comment]
灵眸页面在新的前端项目中已经移除，等待新版设计
