### ISSUE TITLE
[后台]资源创建后不可以改变关联项目

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#427]
问题描述：
>1、资源创建后选择关联项目A
2、资源通过审核后热点上线
3、资源改变关联项目B后
4、由于该资源不在项目A下，导致项目A已上线的热点未受到资源审核的限制未下线

建议：
>资源选择关联项目后不能修改，如不同项目请新建资源

**Comment by shixiaoyanjj** [comment]
test环境已测试通过

**Comment by shixiaoyanjj** [comment]
videojj.com测试未通过

**Comment by lihaiye** [comment]
http://videojj.com/ 正式环境验证通过
其中：红包库为新增后台功能，创建后不能改变项目的要求 暂未更新到正式环境
在#565中跟进

**Comment by shixiaoyanjj** [comment]
测试环境：
>http://test.videojj.com/console/resource/redPackets

- [ ] 优惠券红包关联项目后保存设置，再次打开无法修改关联项目
- [x] 口令红包关联项目后保存设置，再次打开无法修改关联项目
