### ISSUE TITLE
PC端云链默认ICON需求

### ISSUE THREAD

**Issue by lihaiye** [Venvy-dev/demand#433]
需求描述：
>默认ICON需求
云链未选择自定义ICON时，使用以下默认ICON

![image](https://cloud.githubusercontent.com/assets/17242849/13694903/c2d09eec-e794-11e5-905a-43708b297561.png)

**Comment by Mancy1011** [comment]
PC点播
百科的默认icon是百科icon
混合的默认icon是人物icon

PC直播
广告默认ICON是广告icon

**Comment by hzzhujf** [comment]
同 #740

**Comment by lihaiye** [comment]
H5目前百科、混合、广告统一使用广告默认ICON
