### ISSUE TITLE
移动端自定义设置实现需求

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#470]
PC端已实现的配色和展示特效需求，移动端未实现部分
所有配色：移动端只实现透明色
展示特效：移动端只实现声波
![image](https://cloud.githubusercontent.com/assets/16204026/13765627/f782d674-ea95-11e5-803f-da001b80adb1.png)

**Comment by androidlgf** [comment]
@lihaiye  遗漏的波纹特效加上啦

**Comment by lihaiye** [comment]
Android已实现
