### ISSUE TITLE
[后台]添加全局热点时不填写云链出现时间，提交后看不到该热点

### ISSUE THREAD

**Issue by lihaiye** [Venvy-dev/demand#478]
测试地址：
>http://test.videojj.com/console/projects/564d93bfe2b63738009d9ea1/tags

问题描述：
>热点列表界面：点击添加项目热点
编辑热点信息时，不填写‘出现时间’ 确认提交，线上未出现对应热点

建议：
>后台添加项目热点时，强制要求 填写 云链出现时间

![d9](https://cloud.githubusercontent.com/assets/17242849/13768658/a19daa7c-eab3-11e5-863e-003d589bdb22.png)

**Comment by hzzhujf** [comment]
更新到http://7xjfim.com2.z0.glb.qiniucdn.com/test_Iva.js
请登录http://test.videojj.com验证
默认填了0，不填的话会报错

**Comment by lihaiye** [comment]
test环境测试通过
打全局热时，不填写出现时间或出现时间为0时 无法提交，添加提示：出现时间不能为空

**Comment by lihaiye** [comment]
正式环境测试通过
