### ISSUE TITLE
[后台]添加项目热点时，选择广告地点&广告物品资源打开的是广告人物资源

### ISSUE THREAD

**Issue by lihaiye** [Venvy-dev/demand#479]
测试地址：
>http://test.videojj.com/

问题描述：
>1、添加项目热点时，选择广告物品or广告地点资源
打开的是广告人物资源
2、添加混合广告时筛选类别名称未正常显示

建议及期望表现：
>1、广告人物、广告地点、广告物品  三个资源可合并成为：混合广告，或者是正确显示对应的资源信息
2、混合广告界面筛选类别名称正常显示

![d10](https://cloud.githubusercontent.com/assets/17242849/13769599/c8a4e088-eabb-11e5-9168-2b649575c28f.png)

**Comment by hzzhujf** [comment]
打点优化后，这个还得改，容我改下

**Comment by hzzhujf** [comment]
修复

**Comment by lihaiye** [comment]
test环境测试通过

**Comment by lihaiye** [comment]
正式环境测试通过
