### ISSUE TITLE
[后台]全局热点需要确认是否添加 投票 类型

### ISSUE THREAD

**Issue by lihaiye** [Venvy-dev/demand#480]
问题描述：
>全局热点 目前没有投票，需要确认是否添加 投票 类型

![d11](https://cloud.githubusercontent.com/assets/17242849/13769812/6905a322-eabd-11e5-9d64-6b359f0ce5bc.png)

**Comment by hzzhujf** [comment]
投票之类代码的实现方式，加全局有问题。
要加的话改动有点大。
这个如果有客户需求再说吧，到时候把点播投票得重构一下。
