### ISSUE TITLE
热点列表中的热点栏目显示资源关联的栏目

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#481]
问题描述：
>当资源关联了栏目时，打点后，热点列表中的热点栏目显示资源关联的栏目

期望结果：
>添加热点，热点列表中热点的栏目只关联视频栏目

![image](https://cloud.githubusercontent.com/assets/16204026/13770577/1673a586-eac3-11e5-9d3b-f869090e0b88.png)

![qq 20160315152528](https://cloud.githubusercontent.com/assets/16204026/13770486/4d54d1f2-eac2-11e5-89f7-4a3173d0ca26.jpg)

@summernini

**Comment by hzzhujf** [comment]
/api/dgs/searchUserDg
这个接口的参数pub，加一个值3，表示当前视频所属栏目下的资源

**Comment by bpceee** [comment]
@hzzhujf 
3已经被占用了啊 3表示我的&项目下的
所以我用4了

**Comment by bpceee** [comment]
搞定，上test了，你继续～

**Comment by shixiaoyanjj** [comment]
http://test.videojj.com/
test环境测试未通过，请确认更新版本

**Comment by hzzhujf** [comment]
看需求描述貌似是 @iEricKoh 的活

**Comment by hzzhujf** [comment]
刚才在test上测试了下，确实有问题。
@bpceee 看下

**Comment by bpceee** [comment]
@hzzhujf 之前他们把commit弄丢掉了一些；现在test环境好了 试下

**Comment by shixiaoyanjj** [comment]
测试结果：
- [ ] 视频关联栏目与资源关联栏目相同时，在视频中打点可在栏目分类中看到对应资源（权限帐号）
- [ ] 视频关联栏目与资源关联栏目相同时，在视频中打点可在栏目分类中看到对应资源（资源帐号）
- [ ] 资源更改栏目对应热点即下线，显示未审核状态
