### ISSUE TITLE
[后台]数据统计界面：时间选择的按钮点击无效

### ISSUE THREAD

**Issue by lihaiye** [Venvy-dev/demand#502]
测式地址：
>http://videojj.com/

问题描述：
>数据统计界面：时间选择的按钮功能点击无效

![image](https://cloud.githubusercontent.com/assets/17242849/13809320/36594256-eba5-11e5-95a0-8b1cd10b50db.png)

**Comment by iEricKoh** [comment]
@lihaiye @shixiaoyanjj 改动在testing上了已经，你们可以test, thanks.

**Comment by lihaiye** [comment]
**test环境测试结果：**
数据统计页面和信息层统计页面，点按钮选择时间段正常

测试通过

**Comment by iEricKoh** [comment]
@lihaiye 为什么要 reopen???

**Comment by lihaiye** [comment]
@iEricKoh 按照测试流程，test环境测试通过后，上线以后还需要在正式环境验证后再关闭~
目前正式环境还未测试通过哦

**Comment by iEricKoh** [comment]
@lihaiye 

现在的 issue 都是 自动 closed，如果当它们被上线的话。

我觉得你们是不是应该上线以后去 test，发现有问题的话再回来重新创建一个 ticket 报告问题？

按你们现在的流程的话，上线之后 ticket 会被自动 closed，然后你们又回来 manually reopen，如果这时候上线没问题，你们又要回来 manually close.

如果你们能一直记得住这样的步骤，倒也 okay.

**Comment by iEricKoh** [comment]
@lihaiye 这个问题目前也是一个已经上线的状态，麻烦你确认一下。
没问题请close.

**Comment by lihaiye** [comment]
正式环境OK
