### ISSUE TITLE
后台卡牌提示语功能失效

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#507]
问题描述：
>由于卡牌在三端的样式更新，卡牌提示语设置后已不显示，需要确认后台是否删该项

![default](https://cloud.githubusercontent.com/assets/16204026/13841695/6505f8a4-ec65-11e5-8de0-7d6e6f3dc836.jpg)

**Comment by summernini** [comment]
对的不要了 @bpceee

**Comment by shixiaoyanjj** [comment]
test环境测试通过

**Comment by shixiaoyanjj** [comment]
videojj.com测试通过
