### ISSUE TITLE
卡牌显示描述的功能优化需求

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#508]
问题描述：
>PC：打开卡牌显示描述功能有效显示
IOS：打开卡牌显示描述功能不显示
Android：打开卡牌显示描述功能不显示

卡牌显示描述的功能是否需要？需确认该需求并统一三端的规则

![default](https://cloud.githubusercontent.com/assets/16204026/13842008/f8b6af52-ec66-11e5-9e7e-9b15a050897c.jpg)

**Comment by shixiaoyanjj** [comment]
IVA编辑界面已取消显示功能，测试通过
http://7xjfim.com2.z0.glb.qiniucdn.com/test_Iva.js
Iva update at: Wed Apr 06 2016 17:40:51 GMT+0800 (CST)
![image](https://cloud.githubusercontent.com/assets/16204026/14343296/889aff62-fcd2-11e5-915b-f66edd889be6.png)

**Comment by lihaiye** [comment]
Iva update at: Thu Jun 02 2016 15:40:50 GMT+0800 (CST)
正式环境测试通过
