### ISSUE TITLE
卡牌云窗大图不显示边框

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#516]
测试环境：
>后台：https://test.videojj.com
帐号：shixiaoyan@videopls.com 密码：123456
>测试地址：http://demo.tech.videojj.com/2016/03/11/Test-Xinlan-Page/
>Iva version：http://7xjfim.com2.z0.glb.qiniucdn.com/test_Iva.js
>APPKEY：V16OlFxul>
>视频地址：http://7xr5j6.com1.z0.glb.clouddn.com/zjws-wpdwp.mp4>
>重现位置：`00：11`

问题描述：
>卡牌云窗大图不显示边框

期望结果：
>大图显示边框，与设计样式一致且支持颜色适配

![qq 20160318161754](https://cloud.githubusercontent.com/assets/16204026/13872385/57ee48ea-ed25-11e5-93e3-f70bd4e612fd.jpg)

![image](https://cloud.githubusercontent.com/assets/16204026/13872257/27505daa-ed24-11e5-9bb4-fa4a3f5d4324.png)

**Comment by hzzhujf** [comment]
和土豆讨论了下，卡牌主KV就做成无边框的，这样比较适应主KV是半透明的异形图
![image](https://cloud.githubusercontent.com/assets/6982728/14778047/5de37c4c-0b03-11e6-8a14-29720eabe063.png)
