### ISSUE TITLE
灵悦 云链云窗显示逻辑

### ISSUE THREAD

**Issue by Mancy1011** [Venvy-dev/demand#520]
> 逻辑
- 直播/点播：热点点击后打开信息层，热点隐藏
- 直播/点播：关闭信息层继续播放，点击过的热点不再出现
- 点播：关闭信息层但没有超过热点的显示时间，拖动进度条到该热点出现及出现之前的时间点，播放时显示该热点
- 点播：关闭信息层且热点显示时间结束，拖动进度条到该热点的显示时间内，播放时都显示该热点

**Comment by Mancy1011** [comment]
现在直播要按点播逻辑，关闭云窗后点击过的云链不显示

**Comment by nekronhuang** [comment]
https://github.com/Venvy-dev/venvy_iva2/commit/787ef9942bd4524067596241c8c3b565bca1c805

在非编辑者状态下该逻辑已实现，编辑者状态下由于历史原因改动较大，暂未开工

**Comment by shixiaoyanjj** [comment]
IOS直播逻辑
关闭信息层后点击过的热点不显示，重新进入视频显示-Passed
PC直播逻辑
关闭信息层后点击过的热点不显示，重新进入视频显示-Passed

**Comment by lihaiye** [comment]
Android直播逻辑
关闭信息层后点击过的热点不显示，重新进入视频显示-Passed

**Comment by shixiaoyanjj** [comment]
测试结果：
隐性热点为云链云窗显示逻辑
有追踪框的隐性热点未实现云链云窗显示逻辑

**Comment by Mancy1011** [comment]
隐形热点暂不实现显性热点逻辑

**Comment by shixiaoyanjj** [comment]
- [ ] 有追踪框的显性热点不实现云链云窗显示逻辑
- [ ] 有追踪框的隐性热点不实现云链云窗显示逻辑
