### ISSUE TITLE
百科云窗和编辑页面优化规则

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#531]
**百科编辑页面样式太旧，需要更新**

**百科外链按钮是否可编辑需要确认需求**
PC端显示按钮名称
移动端显示查看更多，需要统一规则

![image](https://cloud.githubusercontent.com/assets/16204026/13920292/348784fe-efad-11e5-9c01-b5e77548342a.png)

![image](https://cloud.githubusercontent.com/assets/16204026/13920505/49b8295e-efae-11e5-9e6d-b219d21367ec.png)

![image](https://cloud.githubusercontent.com/assets/16204026/13920515/603bf34a-efae-11e5-8eed-5b02435fe3c3.png)

**Comment by hzzhujf** [comment]
链接的文字是可以编辑的，如果想显示“查看更多”，只要在后台写成“查看更多”即可

**Comment by summernini** [comment]
后台没有地方配置呀

**Comment by bpceee** [comment]
![image](https://cloud.githubusercontent.com/assets/4188573/15645781/089f0a3a-268d-11e6-9383-2911d12005fa.png)

没疑问久关掉吧 @summernini
