### ISSUE TITLE
[后台管理]移动端app通用配置

### ISSUE THREAD

**Issue by Gracebaby** [Venvy-dev/demand#541]
### 移动端 api/apps/me 获取通用配置接口需要加上tomyapp即用户可配置应用内跳转外链还是由SDK打开外链

请在 后台管理-应用管理-播放器设置中加入一栏“信息层设置” 并添加“外链打开功能”，详见以下图示！（注：该功能仅移动端使用）

##### **图示说明：**
<img width="460" alt="2016-03-22 7 14 20" src="https://cloud.githubusercontent.com/assets/14867684/13949875/921c6ebc-f062-11e5-8385-ac970a5796af.png">

**Comment by androidlgf** [comment]
@lihaiye 完成
