### ISSUE TITLE
芒果 口令红包&Pin-code优惠码红包方案

### ISSUE THREAD

**Issue by Mancy1011** [Venvy-dev/demand#546]
> PC端

http://7xs6gl.com1.z0.glb.clouddn.com/v%EF%BC%8B%EF%BC%8B%E6%89%8B%E6%9C%BA%E7%AB%AF%E7%BA%A2%E5%8C%85&%E4%BC%98%E6%83%A0%E5%88%B80322final%20.pdf

> 移动端

http://7xs6gl.com1.z0.glb.clouddn.com/v%EF%BC%8B%EF%BC%8Bpc%E7%AB%AF%E7%BA%A2%E5%8C%85&%E4%BC%98%E6%83%A0%E5%88%B80322final.pdf

**Comment by nekronhuang** [comment]
基本完成，等待测试

**Comment by shixiaoyanjj** [comment]
PC直播
口令红包&优惠码红包：点击广告banner外链未统计clicklink接口

**Comment by shixiaoyanjj** [comment]
PC直播
热点ICON与标题未对齐
![image](https://cloud.githubusercontent.com/assets/16204026/14338204/8c054e9e-fca7-11e5-8223-9db397b2e100.png)

**Comment by shixiaoyanjj** [comment]
PC直播：红包打点位置与实际显示位置不符
PC直播：缩放视频窗口，红包未自适应窗口显示
@nekronhuang @hzzhujf

**Comment by shixiaoyanjj** [comment]
IOS直播
 红包优惠券的文字长度适配问题
 优惠码领完后可重新获取上传的优惠码

**Comment by lihaiye** [comment]
Android直播：
红包所有文字长度适配问题-PASSED
优惠码领完后可重新获取上传的优惠码-PASSED

**Comment by Mancy1011** [comment]
红包的广告banner可以配置成只传广告图片不填外链地址
@Zard1096 @androidlgf @hzzhujf

**Comment by shixiaoyanjj** [comment]
点播红包
- [ ] PC
- [ ] IOS
- [ ] Android

**Comment by shixiaoyanjj** [comment]
**点播：**
- [ ] 重新进入页面红包显示并且开始倒计时

**Comment by Zard1096** [comment]
@shixiaoyanjj 是宇一工打点传的起始值不为0，已修复
