### ISSUE TITLE
项目概览页-地域分布图Bug

### ISSUE THREAD

**Issue by youqiongjoan** [Venvy-dev/demand#547]
项目概览-地域分布图
1）排名，缺失第10，20，30名；
2）当芒果TV数据多了后，显示有问题；
![image](https://cloud.githubusercontent.com/assets/16954468/13976936/5b645c48-f0ff-11e5-981e-c26bc62aabdb.png)

**Comment by lihaiye** [comment]
测试地址：http://test.videojj.com/console/projects/
验证已修复

别：测试环境视频播放量Top10列表中有出现404的情况，需要更新到正式环境后再验证

**Comment by iEricKoh** [comment]
@lihaiye 如果已经修复，请 close.

**Comment by lihaiye** [comment]
正式环境测试通过
