### ISSUE TITLE
追踪框移动范围较大时暂停后播放追踪框出现复制

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#553]
重现环境
>芒果TV线上

![qq 20160323183510](https://cloud.githubusercontent.com/assets/16204026/13982710/7f7286a6-f126-11e5-953f-d91999ecf112.jpg)
![qq 20160323183630](https://cloud.githubusercontent.com/assets/16204026/13982711/7fa44092-f126-11e5-94d2-a0d8cedf7bbb.jpg)

**Comment by hzzhujf** [comment]
本地测试没出现
等下次芒果线上代码更新了再回归下
芒果线上更新预计在4月中，超女直播上的时候更新

**Comment by shixiaoyanjj** [comment]
http://lingxi.mgtv.com/mangguotv_Iva.js
Iva update at: Thu Apr 28 2016 20:57:46 GMT+0800 (CST)
未重现该问题
