### ISSUE TITLE
Edge浏览器打开云窗时，云泡或其他应用浮在云窗上视频显示异常

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#561]
测试环境：
>http://tv.cztv.com/vplay/155502.html

问题描述：
>新蓝网，风行网可重现
打开云窗时，激活云泡输入框或其他应用浮在云窗上都会出现视频异常
![qq 20160324152112](https://cloud.githubusercontent.com/assets/16204026/14010879/67be6b02-f1d4-11e5-9859-2f8a208544fc.jpg)

**Comment by nekronhuang** [comment]
修复该bug会造成屏幕放大后，页面元素显示稍微模糊些
