### ISSUE TITLE
[风行网]视频重播后进入广告也会显示IVA层

### ISSUE THREAD

**Issue by lihaiye** [Venvy-dev/demand#562]
测试地址：
>http://www.fun.tv/tools/changeBranch.html   公网alpha环境
测试视频：http://www.fun.tv/vplay/g-300047/
浏览器：Chrome

问题描述：
>视频播放完后，点“重播” 会先进入广告
广告期间也会显示IVA层

![image](https://cloud.githubusercontent.com/assets/17242849/14011778/2aeefdc4-f1dc-11e5-8e6b-05b21ca1d9d3.png)

**Comment by nekronhuang** [comment]
风行方面已经修复，可再次测试线上环境
