### ISSUE TITLE
资源管理混合广告编辑必填项的限制问题

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#564]
问题描述：
>添加混合广告第一个标签页的图片，缩略图，标题，描述后其他项未填没有做判断，导致前端打开时报错

![image](https://cloud.githubusercontent.com/assets/16204026/14013307/cf5a4a3a-f1e6-11e5-9b9b-f48063e8994d.png)

@Gracebaby

**Comment by iEricKoh** [comment]
@shixiaoyanjj 麻烦重新描述一下这个 ticket 里面你想实现/修复的是什么.

**Comment by shixiaoyanjj** [comment]
#904 原型已出，按需求实现即可
