### ISSUE TITLE
[后台管理]资源管理-红包库

### ISSUE THREAD

**Issue by Gracebaby** [Venvy-dev/demand#565]
原型：
http://yx.tech.videojj.com/hongbao_console20160324/#p=红包库

**Comment by iEricKoh** [comment]
@Gracebaby 

screenshot 里面要添加的监控是 ``for 红包热点图`` 还是 `` for 品牌 logo `` ?

![screenshot from 2016-04-05 11-45-16](https://cloud.githubusercontent.com/assets/8081074/14270763/f5316364-fab6-11e5-8763-de02bbb8ba72.png)

**Comment by Gracebaby** [comment]
Sorry @iEricKoh  这边的监控最终确认不需要 请见以下图示：

口令红包
![qq20160405-1 2x](https://cloud.githubusercontent.com/assets/14867684/14273793/c205ac5a-fb3f-11e5-84e6-df669ec1900b.png)

优惠码红包
![qq20160405-2 2x](https://cloud.githubusercontent.com/assets/14867684/14273806/ce4dd80c-fb3f-11e5-8b80-59860cbb26c3.png)

**Comment by iEricKoh** [comment]
@lihaiye 今天早上你跟我交谈的问题，关于``口令红包``无法 save 成功，请你在 testing server 上面再次测试一下， thx.

**Comment by iEricKoh** [comment]
- [ ] Remove field "expiryDate"  from both create red envelope modal
- [ ] Remove field "forever" from both create red envelope modal

**Comment by lihaiye** [comment]
@iEricKoh    已经可以添加口令红包了，谢谢

**Comment by iEricKoh** [comment]
@lihaiye 谢谢。后续还有什么问题请在该 issue 里面留 comments 就好，我都看得见。

**Comment by iEricKoh** [comment]
Here's the latest versions of wireframe from @Gracebaby
- [ ] Add new field ``领取结束说明``

![86208947](https://cloud.githubusercontent.com/assets/8081074/14305318/ba47d268-fb80-11e5-8ac3-7a760018c001.jpg)

**Comment by iEricKoh** [comment]
- [ ] Change size of cover image to 60px * 80px.

**Comment by shixiaoyanjj** [comment]
资源审核页面的红包资源不能预览 @hzzhujf

**Comment by shixiaoyanjj** [comment]
问题描述：
红包资源的关联项目可修改
期望结果：
关联项目设置后应不可修改
![image](https://cloud.githubusercontent.com/assets/16204026/14312886/ee4c43fa-fc20-11e5-9e57-b6f7237eff66.png)

**Comment by summernini** [comment]
@shixiaoyanjj 关联项目的功能是否可以修改这个暂时先这样，现在不做修改，改动起来范围比较大，因为不仅是红包一个界面的事儿。

**Comment by shixiaoyanjj** [comment]
口令红包的领取结束方法未知，故领取结束说明没有实现，需要确认需求
![image](https://cloud.githubusercontent.com/assets/16204026/14316896/1942e426-fc38-11e5-8dfc-607e57707f07.png)

**Comment by shixiaoyanjj** [comment]
Pin-code文件可以重新上传，但未覆盖前一次的文件

![image](https://cloud.githubusercontent.com/assets/16204026/14318546/f5be94ca-fc3f-11e5-86d9-03b8c9094c01.png)

**Comment by iEricKoh** [comment]
@shixiaoyanjj 
> [Pin-code文件可以重新上传，但未覆盖前一次的文件](#issuecomment-206378333)

这一条是什么意思，不懂。

可以告诉我你期望的结果是什么吗？当你重新上传之后。

**Comment by shixiaoyanjj** [comment]
Pin-code文件可以重新上传，但未覆盖前一次的文件，会与之前的文件叠加，如果重复上传相同的文件，会导致数据库有两份相同的Pin-code码，影响用户领取，建议重新上传时可以覆盖前一次的文件
最终结果：由产品经理决定@Gracebaby

**Comment by iEricKoh** [comment]
Hi Xiaoyan,

现在的逻辑就是上传之后都会把之前的records删掉, 然后重新上传新的。

不知道你是如何确认数据库有两份数据的?

**Comment by shixiaoyanjj** [comment]
好，我再测试一下，谢谢

**Comment by iEricKoh** [comment]
- [ ] 添加 pincode sample 下载功能

// pin-code 发放顺序：从下往上依次发放
// pin-code 为16字符以内的英文、数字组成
// 示例

**Comment by shixiaoyanjj** [comment]
Pin-code文件重新上传后为覆盖前一次的文件，已测试通过

**Comment by Gracebaby** [comment]
@iEricKoh  优惠码红包序列号需要按顺序发放，不用插入形式，请记得修改！：）

**Comment by iEricKoh** [comment]
Hi @lihaiye @shixiaoyanjj, 
麻烦测试一下最新的 pin code 文件上传逻辑。请让我知道结果无论最后有没有问题。下午会上线该功能。

**Comment by lihaiye** [comment]
@iEricKoh 
Pin-code文件上传逻辑为：重新上传后为覆盖前一次的文件
pin-code 发放顺序：从下往上依次发放

**Comment by iEricKoh** [comment]
@lihaiye 下面这个是你的预期测试结果，对吗？

>Pin-code文件上传逻辑为：重新上传后为覆盖前一次的文件
pin-code 发放顺序：从下往上依次发放

你还需要告诉我现在 testing server 上实际的测试结果。

**Comment by lihaiye** [comment]
@iEricKoh 
实际测试结果为：
Pin-code文件上传逻辑为：重新上传后为覆盖前一次的文件
pin-code 发放顺序：从下往上依次发放

**Comment by iEricKoh** [comment]
@lihaiye 谢谢你的快速回应。

所以测试结果 ok 咯？ 当前 testing server 上关于*后台红包资源*的**创建**，**编辑**还存在其它什么*bug*或者待解决的问题吗？是否是一个可以上线的状态？

**Comment by lihaiye** [comment]
@iEricKoh @Gracebaby  目前还有以下问题：

1、红包资源下方的开关按钮功能没有实现，选择关闭后前端仍然显示红包
![image](https://cloud.githubusercontent.com/assets/17242849/14455869/71b6f66a-00d4-11e6-953f-accc56a80f19.png)
2、红包资源添加了爆光监控代码后，线上点击打开该红包控制台未收到相关统计信息
![image](https://cloud.githubusercontent.com/assets/17242849/14455909/a62b4b12-00d4-11e6-8d9a-fa1e5b8cbfb9.png)
3、红包文本内容前端显示有字数限制，需要控制台做文字输入限制（各行字数显示见图，以中文字符为标准）
![image](https://cloud.githubusercontent.com/assets/17242849/14456134/f7970ee0-00d5-11e6-8825-c8aad9b73f0e.png)

![image](https://cloud.githubusercontent.com/assets/17242849/14456150/05a4b762-00d6-11e6-94a4-a2c9c016f963.png)

**Comment by iEricKoh** [comment]
Hi @lihaiye 

> 1、红包资源下方的开关按钮功能没有实现，选择关闭后前端仍然显示红包

A: 这个需求应该不在此次修改内。

> 2、红包资源添加了爆光监控代码后，线上点击打开该红包控制台未收到相关统计信息

B: 如果监控代码的两个字段(miaozheng & admaster)，当你填写完对应的URL，后台能够保存成功，就没有问题。关于*线上点击打开该红包控制台未收到相关统计信息**，你应该询问负责各个平台的同事。

> 3、红包文本内容前端显示有字数限制，需要控制台做文字输入限制（各行字数显示见图，以中文字符为标准）

Sorry, 我没有注意到字数限制的细节。我会尝试能否在6:30pm之前实现。如果来不及，考虑到上线，这个小细节就不跟着这次 merge 上线。等到下一次上线的时候。

Thx.

**Comment by summernini** [comment]
@iEricKoh

**Comment by iEricKoh** [comment]
- [ ] Hide enable/disable button

**Comment by summernini** [comment]
@iEricKoh A:先将『开启/关闭』按钮隐藏待MQTT做好后再决定是否开放此功能 B：麻烦@lihaiye 重新建三个bug给三个前端做修改 C：字数限制修复完毕后在周四安排上线

**Comment by shixiaoyanjj** [comment]
@iEricKoh 红包提示文本的默认保存功能也在之后的版本中实现一下，谢谢

**Comment by Gracebaby** [comment]
@iEricKoh  @shixiaoyanjj  @lihaiye  红包库还存在以下问题：
1.有默认内容的输入项，当输入框获取焦点默认内容全选，可修改；而输入框的提示文字应在光标键入时，隐藏提示文字，请作区分

2.口令红包与优惠码红包提示语有所不同，请记得作区别；且部分输入项有默认提示语，请注意区分（详见以下图示）

3.弹窗请增加关闭button

4.由于前台显示需求，优惠码红包的“红包结束语”，拆分成两行填写，详见以下图示**（注：此条为新需求）**

图示（说明：框选的为默认内容输入项，请注意区分）
口令红包
![default](https://cloud.githubusercontent.com/assets/14867684/14457884/59fa6d02-00e0-11e6-80ed-7e525c6718e6.png)

优惠码红包
![default](https://cloud.githubusercontent.com/assets/14867684/14457891/675c38e0-00e0-11e6-95c1-bf5e66f07ca4.png)

有疑问，随时沟通：）

**Comment by iEricKoh** [comment]
Hi @Gracebaby 
关于第四点，拆分成两个 input box 的意图是为了多行显示对不对？
可是 textarea 不是已经有 line break 的标记了吗？这就是它跟 input box 的区别，允许输入文字的时候换行。

请让我知道是否要进行这个改动， thanks.

![video video _ _](https://cloud.githubusercontent.com/assets/8081074/14482456/91a64952-0102-11e6-8fc3-b69b99251da0.png)

````
      "redPacket": {
        "conclusion": "1st line\n2nd line",  // 这里就有 line break 的标志啊，\n
        "category": "coupon",
        "topText": "top text",
        "content": "contentc",
        "enable": true,
        "buttonText": "领取红包",
        "pics": [
          {
            "url": "http://static.cdn.videojj.com/FnMFNl6KhMvbaVFNpZKT_x9WhYSz",
            "_id": "570cc9d35bb3e6af201c2f1f",
            "id": "570cc9d35bb3e6af201c2f1f"
          },
          {
            "url": "http://static.cdn.videojj.com/FhuwGigxrrGQqBtHJk5pYM6kz57I",
            "_id": "570cc9d35bb3e6af201c2f1e",
            "id": "570cc9d35bb3e6af201c2f1e"
          }
        ]
      },
````

**Comment by Gracebaby** [comment]
Hello @iEricKoh 

使用 textarea 是有标记换行，但前端无法判定显示10个汉字字符后换行
因此作了修改，使用分行输入，每行字符限制为是10个汉字

**Comment by iEricKoh** [comment]
Hey Gradebaby,

我注意到在你最新的 wireframe 里，关于**口令**红包的那个里面，是没有``领取结束说明``这个字段的。但是在真正的 online
版本上，是存在着这个字段的。
所以跟你确认一下，口令红包里需要是有这个字段的存在吗？


​

​
Thanks,
Eric

**Comment by Gracebaby** [comment]
Hi Eric

口令红包是无“领取结束说明”的，由于口令红包是用户在第三方领取的，我们读取不到红包是否已领完，所以不需要领取完毕的相关配置，请在上线版本中去除吧：） 麻烦你了 @iEricKoh

**Comment by iEricKoh** [comment]
@Niue @Damonyg @nekronhuang @hzzhujf 

由于领取结束语变成了两个input, 也就是该字段变成了两个值，所以类型从原来的 String 变成了 [], 数组类型。

conclusion[0] = 第一行
conclusion[1] = 第二行

这个变动的话需要你们一起同步更改才能一起上线对不对？

关于该字段的更改细节请见 [da650f4](https://github.com/iEricKoh/videojj/commit/da650f4736b81bcffaf2de2ea938f5e283b39ecd)

````
conclusion: {
  type: []
}
````

**Comment by nekronhuang** [comment]
抱歉，之前没仔细看， @iEricKoh 使用textarea方案，只有PC端显示需要修改就可以了

**Comment by Gracebaby** [comment]
Sorry Eric
后台优惠码红包配置请再调整一下，“红包结束语”为默认内容输入项，当输入框获取焦点时，默认内容全选，且可修改；输入框下方也请加入提示（详见以下图示） @iEricKoh @shixiaoyanjj @lihaiye 
![qq20160414-1 2x](https://cloud.githubusercontent.com/assets/14867684/14522592/d9439f98-0261-11e6-9276-d45d0b056b5f.png)

**Comment by iEricKoh** [comment]
@shixiaoyanjj @lihaiye Hey All,  包含最新改动的版本已经在 testing server 上，麻烦你们测试。让我知道你们的回应如果有任何问题的话。

**Comment by lihaiye** [comment]
@Gracebaby 
优惠券红包：
1、新建红包资源时，**兑换说明**这项不是必填项，但是如果为空的话，前端打点后红包无法打开会报错
2、**领取结束说明**也不是必填项
请确认下这两项内容是否要改为必填项

![image](https://cloud.githubusercontent.com/assets/17242849/14525015/0a663ba6-026e-11e6-90af-db8d56c1cce5.png)

**Comment by Gracebaby** [comment]
与蘑菇再次确认后，结论为优惠码红包“兑换说明”为必填项，“领取结束说明”为选填项
麻烦Eric修改一下 @iEricKoh  @shixiaoyanjj  @lihaiye

**Comment by shixiaoyanjj** [comment]
红包结束语分行显示：
- [ ] PC
- [ ] Android
- [ ] IOS

**Comment by lihaiye** [comment]
@iEricKoh @Gracebaby 

3.弹窗请增加关闭button： **该功能未实现**
![image](https://cloud.githubusercontent.com/assets/17242849/14526000/ffeb5f76-0272-11e6-85b6-c0e21ee5cc67.png)

**Comment by lihaiye** [comment]
@androidlgf 
优惠券红包的结束语分行显示：
如果设置后台结束语时两段文字当中加了空行，界面显示也会多出一个空行，需要修改成中间不留空行

**Comment by iEricKoh** [comment]
Hi Xiaoyan,

> 红包默认提示文本的功能也在之后的版本中实现一下，谢谢

这个需求是什么？请详细描述一下， THX.

**Comment by iEricKoh** [comment]
1. Change in coupon 
  - [ ] Mark ``desc`` as required

2. Change in both token & coupon 
  - [ ] Close button is missing from modal dialog

**Comment by shixiaoyanjj** [comment]
问题描述：
>优惠券的领取结束语换行后无法输入20个字符
![image](https://cloud.githubusercontent.com/assets/16204026/14632196/f400fa9c-0649-11e6-9b1a-f53024b61e20.png)

**Comment by shixiaoyanjj** [comment]
- [ ] 上传png图片背影显示黑色，应显示透明色

![image](https://cloud.githubusercontent.com/assets/16204026/14697463/a52bcb7c-07b6-11e6-8dca-86fe96ee64f6.png)

**Comment by Gracebaby** [comment]
Hi @iEricKoh 

**以下有“芒果”那边的一个紧急修改，麻烦你尽快调整一下，谢谢：）**
“芒果”对“口令红包”及“优惠劵红包”默认红包热点图及默认提示语有新要求，详见以下图示！

**口令红包**
![qq20160427-1 2x](https://cloud.githubusercontent.com/assets/14867684/14840913/659f3cdc-0c6b-11e6-99f6-dc4670cb9b64.png)

**优惠码红包**
![qq20160427-2 2x](https://cloud.githubusercontent.com/assets/14867684/14840924/7e0721fe-0c6b-11e6-9d7d-e8d3ace331b6.png)

修改完后，请告知小乌龟，麻烦小乌龟 @shixiaoyanjj  测一下
@summernini  麻烦Summer跟一下 谢谢：）

**Comment by iEricKoh** [comment]
Hi Gracebaby,

红包热点默认图是什么？截图或者给我直接的URL. thanks.

2016-04-27 11:36 GMT+08:00 Gracebaby <notifications@github.com>:

**Comment by Gracebaby** [comment]
Hi  Eric @iEricKoh 

设计部稍后会给到“芒果”刚确认完的默认红包热点图，请注意查收邮件：）

**Comment by shixiaoyanjj** [comment]
@Gracebaby 
没有测试依据无法测试，送测请给到我设计样式，谢谢

**Comment by shixiaoyanjj** [comment]
![image](https://cloud.githubusercontent.com/assets/16204026/14975680/b8b083d4-1136-11e6-9d8b-c340c4427fb7.png)

- [x] 实现红包热点默认图样式

**Comment by shixiaoyanjj** [comment]
- [ ] 红包结束语的描述与需求不符
![image](https://cloud.githubusercontent.com/assets/16204026/14976165/e57b871a-113b-11e6-8c51-d8222f226960.png)
期望结果：
![image](https://cloud.githubusercontent.com/assets/16204026/14976168/e965d4a2-113b-11e6-906d-928ff0cd1f79.png)

**Comment by silentMood** [comment]
... sorry，更新自己fork的项目时，误操作

**Comment by iEricKoh** [comment]
@shixiaoyanjj 跟你确认一下，

> 红包结束语的描述与需求不符 

测试结果跟期望结果对比，只是多了一个``经``字是吗？

**Comment by shixiaoyanjj** [comment]
> 红包结束语的描述与需求不符 
测试结果跟期望结果对比，只是多了一个``经``字是吗？
然后还有``抢光``。

@iEricKoh 是的，产品要求与原型保持一致

**Comment by iEricKoh** [comment]
@summernini 为什么你要 reopened ???

**Comment by shixiaoyanjj** [comment]
@iEricKoh  

- [ ] 优惠券的领取结束语换行后无法输入20个字符

![image](https://cloud.githubusercontent.com/assets/16204026/14632196/f400fa9c-0649-11e6-9b1a-f53024b61e20.png)

**Comment by iEricKoh** [comment]
@shixiaoyanjj 需求就是只允许两行吧

**Comment by iEricKoh** [comment]
@shixiaoyanjj Sorry, 还是你的意思是，你不希望``回车换行``算是一个字符？

对于已经上线过的tickets, 出现问题的话，能够重新创建一个新的吗？不要 reopen 在以前旧的里面讨论, thanks.

**Comment by summernini** [comment]
@iEricKoh 我是看vigroone关的所以我才打开的，正常流程不应该是先到测试池，最终由测试人员关闭tickets吗

**Comment by iEricKoh** [comment]
我不知道这一条 > 关于“最终由测试人员关闭tickets吗”。

我知道的是现在的 tickets，一旦上线了，是会自动 close 的。对此我也觉得好奇怪，好多次看到你们重新reopen刚刚上线完成的ticket, 哪怕这些 tickets 没出现问题。

也正是由于每个tickets是自动close的，但是May 20的时候你又手动reopen, 3天之前vigroone更新了一下代码，github 认为这个 ticket 就是应该是一个 close 的状态，所以他更新之后就自动会再次close。

**Comment by summernini** [comment]
但是我也有疑问，这个tickets相关开发人员并没有vigroone，为什么是他上线代码呢？不应该是你吗

**Comment by shixiaoyanjj** [comment]
好的，我会重新提交issues
根据之前制定的流程，如果这个issues的功能上线了，应该在上线池中，会由测试人员在正式环境再次测试。

**Comment by iEricKoh** [comment]
@summernini 举个例子，

比如vigroone三天前也同时close掉了[issue #696](https://github.com/Venvy-dev/demand/issues/696).
在这个ticket里面，你可以找到下面的这条log:
> hzzhujf closed this in hzzhujf/videojj@ffd1454 on May 12.

但是之后并没出现bug或者其他什么问题，可是我看到你再次reopen:
> summernini reopened this on May 12

三天前(上周五)vigroone更新了我的代码，github 认为这个 ticket 也确实就是应该一个 closed 状态，所以github自动关闭掉它了。

------------------------------------

回答一下你刚刚的疑问：

比如我现在完成一个需求，写完代码，我会 assign 给 vigroone(帅兵) 帮我执行一个动作，这个动作我们叫做 merge PR。这个动作之所以不自己来做，是为了让别人互相监督一下看自己做的东西有没有严重的错误。

对于 testing server 来说，merged PR 完成之后，会自动上线。
对于 production server 来说， merged PR 完成之后，一般还需要@netpi手动上线。

**Comment by summernini** [comment]
恩。我明白了。在此之前有出现过一些tickets被开发误关闭的情况。所以我还以为是同一种错误现象……刚和东泽沟通了一下，他有解决方案，会在明天的技术会议上给大家解答。那现在这个tickets我就关闭了吧~
