### ISSUE TITLE
[IVA]热点标题长度超出视频边框

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#569]
问题描述：
>编辑热点时，标题长度超出编辑框，热点标题未适应边框调整显示方向

![qq 20160325133841](https://cloud.githubusercontent.com/assets/16204026/14039613/2e0e5fb4-f299-11e5-9f16-f170898e1c69.jpg)

**Comment by hzzhujf** [comment]
之前是有做12个汉字限制的，太靠右是会转向的。图中的这个bug因为芒果去掉12个汉字限制造成的。
以后这个问题可以通过运营避免。
