### ISSUE TITLE
控制台-热点列表页-操作增加两行热点点击监控

### ISSUE THREAD

**Issue by summernini** [Venvy-dev/demand#595]
页面：热点列表页面
需求：增加两行热点点击监控的输入框，分别可填写Miaozhen的热点点击监控和Admaster的热点点击监控。

@iEricKoh   Eric待红包和广告投放平台做完后再开发
@youqiongjoan @analyst004  数据统计页面里面也需要增加一列为『热点点击量』

**Comment by Gracebaby** [comment]
@iEricKoh  

> 热点列表：点击操作，“编辑热点信息”中，新增第三方“点击监控”（详见以下图示）

![qq20160511-8 2x](https://cloud.githubusercontent.com/assets/14867684/15175381/93b1e380-1798-11e6-9ec1-05c3ab93e2f2.png)

**Comment by summernini** [comment]
待东泽将数据优化功能稳定后再看是否要开发。

**Comment by summernini** [comment]
@iEricKoh 如口头沟通，明天中午前按以上需求做好给到 @hzzhujf 辛苦大家了~

**Comment by iEricKoh** [comment]
@hzzhujf @shixiaoyanjj @lihaiye 这次改动已经完成在testing server上。

**Comment by iEricKoh** [comment]
@hzzhujf 修改允许 float 输入的问题已经fixed, https://github.com/Venvy-dev/videojj/pull/565

**Comment by shixiaoyanjj** [comment]
#931 Html5已实现
请确认flash是否需要实现此功能
@summernini

**Comment by summernini** [comment]
Flash需要，暂时先让小福做 显性点热点的点击监控即可，其他类型的点击监控我另外建票

**Comment by williamling** [comment]
@lihaiye @shixiaoyanjj  #931 
flash已放到测试地址
1.热点的点击和曝光监控
2.广告 混合 投票 红包的图片曝光监控

地址 http://flash.videojj.com/test/index1.html

**Comment by lihaiye** [comment]
Flash第三方监控测试（Admaster or 秒针）：
### 点播

**广告**、**投票**、**混合**、**红包**、**片花**
- [ ] 热点曝光监控
- [ ] 热点点击监控
- [ ] 信息层曝光监控
- [ ] 广告外链监控

**云图**、**百科**、**卡牌**
- [ ] 热点曝光监控
- [ ] 热点点击监控

### 直播
**广告**、**投票*、**红包**、**云图**、**百科**
- [ ] 热点曝光监控
- [ ] 热点点击监控

**Comment by summernini** [comment]
注意 投票应该是hover事件算作click点击监控

**Comment by lihaiye** [comment]
Question：  @summernini 
**FLASH**：**红包的热点点击监控**--未实现，请确认下是否满足需求，THS~

**Comment by summernini** [comment]
@lihaiye 把红包的第三方监控问题描述清楚另外建个票吧，这个票就上线

**Comment by lihaiye** [comment]
### FLASH点播

>
红包功能由于是直播逻辑，暂未实现第三方点击监控，已单独提交ISSUES #996，不影响本ISSUES上线

**Comment by summernini** [comment]
还少 ios android修改

**Comment by Zard1096** [comment]
@hzzhujf 我获取的哪个接口，数据改变在哪里，怎么加？

**Comment by androidlgf** [comment]
@lihaiye 功能完成

**Comment by Zard1096** [comment]
@summernini 原有代码，已经完成

**Comment by summernini** [comment]
@lihaiye 麻烦再验收下感谢~

**Comment by lihaiye** [comment]
### Android点播测试：

>- [x] 广告-热点点击监控
- [x] 百科-热点点击监控
- [x] 云图-热点点击监控
- [x] 混合-热点点击监控
- [x] H5-热点点击监控
- [x] 卡牌-热点点击监控

**Comment by shixiaoyanjj** [comment]
## IOS点播测试：

>- [x] 广告-热点点击监控 统计正常
- [x] 百科-热点点击监控 统计正常
- [x] 云图-热点点击监控 统计正常
- [x] 混合-热点点击监控 统计正常
- [x] H5-热点点击监控 统计正常
- [x] 卡牌-热点点击监控 统计正常
- [x] 投票-热点点击监控 统计正常

**Comment by shixiaoyanjj** [comment]
点播已全部实现
直播功能在#996跟踪，此issues通过

**Comment by iEricKoh** [comment]
@shixiaoyanjj @lihaiye @summernini 在``通过池-可上线``看到这个ticket.

这个ticket相关的修改已经是上线的状态，上线之后已经被自动closed了。
后来有人重新reopen, 如果当前没什么问题请记得关闭。
