### ISSUE TITLE
芒果 投票结果样式更新（加广告banner）

### ISSUE THREAD

**Issue by Mancy1011** [Venvy-dev/demand#596]
> 原型20160328
![banner](https://cloud.githubusercontent.com/assets/17489618/14076513/d44ac32c-f514-11e5-99d0-f59448100abe.jpg)

**Comment by Mancy1011** [comment]
PC点播
投票前
![pc banner](https://cloud.githubusercontent.com/assets/17489618/14199184/babe0358-f814-11e5-85f6-a65c697f226f.jpg)
投票后
![pc banner](https://cloud.githubusercontent.com/assets/17489618/14199187/c4e5278a-f814-11e5-80b2-b4ebef62e981.jpg)

**Comment by hzzhujf** [comment]
创建投票时，把选择状态（全部、未开始、进行中、已结束）去掉了。默认只显示进行中的。
请在test_Iva.js上测试

**Comment by shixiaoyanjj** [comment]
test环境测试通过
Iva update at: Tue Apr 05 2016 20:11:37 GMT+0800 (CST)

**Comment by lihaiye** [comment]
@androidlgf  Android端已结束的投票，窗口显示还是可以投的状态。

**Comment by shixiaoyanjj** [comment]
IOS测试通过

**Comment by shixiaoyanjj** [comment]
PC直播
无广告banner时无默认图片
![qq 20160406155322](https://cloud.githubusercontent.com/assets/16204026/14309556/c80288d2-fc0f-11e5-9aa7-4ff7c8a392be.png)

土豆提供的默认图片如下：
![1](https://cloud.githubusercontent.com/assets/16204026/14309568/d2ba7136-fc0f-11e5-845d-e9bd3cbb4937.png)

**Comment by lihaiye** [comment]
PC端直播：
>投票云窗格式 未按照样式需求实现

![image](https://cloud.githubusercontent.com/assets/17242849/14309529/a5c31d5e-fc0f-11e5-9723-5f619f7efabc.png)

**Comment by androidlgf** [comment]
@lihaiye 修改完成

**Comment by lihaiye** [comment]
@Damonyg   
正在进行当中的投票，无法投票，打开投票窗口直接显示投票百分比
![image](https://cloud.githubusercontent.com/assets/17242849/14316718/352d8cbe-fc37-11e5-9486-9c56cb7ef28f.png)

**Comment by lihaiye** [comment]
Android端测试通过

**Comment by Mancy1011** [comment]
移动端没有广告banner时显示默认图片，同时隐藏 "GO" 按钮 @Zard1096 @androidlgf

**Comment by shixiaoyanjj** [comment]
@Mancy1011 有广告banner没有外链时，什么显示需求？

**Comment by Mancy1011** [comment]
有广告banner没有外链，不显示 "GO" 按钮 @shixiaoyanjj

**Comment by shixiaoyanjj** [comment]
PC直播test环境测试通过
没有广告banner时不显示默认图片--Passed
有广告banner无外链时，显示图片，不显示 "GO" 按钮--Passed

**Comment by lihaiye** [comment]
Android： test环境测试通过
没有广告banner时不显示默认图片--Passed
有广告banner无外链时，显示图片，不显示 "GO" 按钮--Passed

**Comment by shixiaoyanjj** [comment]
IOS： test环境测试通过
有广告banner无外链时，显示图片，不显示 "GO" 按钮--Passed
