### ISSUE TITLE
主页底部的开始使用栏，输入已注册的邮箱时建议优化提示效果

### ISSUE THREAD

**Issue by lihaiye** [Venvy-dev/demand#605]
测试地址：
>http://front.test.videojj.com/

问题描述：
>主页底部开始使用一栏，输入已注册的帐号时
提示信息“忘记密码”和“直接登陆”建议加下划线，加强可点击的提示效果

![image](https://cloud.githubusercontent.com/assets/17242849/14104773/9574eeaa-f5d9-11e5-8ee9-a3913bcf5893.png)

**Comment by WalterGuo** [comment]
测试地址：[测试](http://test.videojj.com)

**Comment by lihaiye** [comment]
http://test.videojj.com/ 测试通过
