### ISSUE TITLE
灵动介绍页bugs

### ISSUE THREAD

**Issue by zqsh1213** [Venvy-dev/demand#614]
- [x] 1.首屏大字Nothing拼写错误
- [x] 2.所有视频的背景默认图片使用全黑
- [x] 3.滚屏速度加快一倍
- [x] 4.投票页的每次点击都需要反馈（尺寸变大一些）
- [x] 5.投票页的主播界面按钮也应该每一次点击后尺寸放大
- [x] 6.windows下首屏按钮字体偏上
- [x] 7.支持买买买的图片需要替换
- [x] 8.弹幕宽度需要再增加 目前还有文字会被换行
- [x] 9.页面title改成：灵动直播互动-让直播更好玩 ʕ•̫͡•ʕ*̫͡*ʕ•͓͡•ʔ-̫͡-ʕ•̫͡•ʔ*̫͡*ʔ｜Video++智能互动视频播放器技术平台

修复完成后希望安排测试

**Comment by lihaiye** [comment]
@zqsh1213 
麻烦启子看看是否达到需求效果
测试地址：http://videojj.com/live/
