### ISSUE TITLE
[灵眸]返回上一级页面的功能未实现

### ISSUE THREAD

**Issue by lihaiye** [Venvy-dev/demand#620]
#549
测试地址：
>http://test01.videojj.com/lingmou.html

问题描述：
>原型设计中每个页面都应有返回上一个页面的按钮，该功能未实现：
1、关键词分析  界面，可 ”返回视频设置“
2、广告设置  界面，可 ” 返回关键词分析“
3、待审核 界面，可 ”返回广告设置“

![image](https://cloud.githubusercontent.com/assets/17242849/14166979/8b7de77c-f74a-11e5-8672-f5836075c33d.png)

![image](https://cloud.githubusercontent.com/assets/17242849/14167011/be8a27d4-f74a-11e5-997d-aaa9890014cd.png)

![image](https://cloud.githubusercontent.com/assets/17242849/14167018/da7d4872-f74a-11e5-923a-99ade819dc30.png)

**Comment by edward32tnt** [comment]
#658

**Comment by lihaiye** [comment]
自动打点页面完成审核后
增加按钮：重新开始，选择关键词

已实现，此单关闭
