### ISSUE TITLE
视频管理-页面 增加“节目VV”列

### ISSUE THREAD

**Issue by youqiongjoan** [Venvy-dev/demand#623]
需求来源：战旗 老郭
视频管理-页面 增加“节目VV”列，并且按节目VV数，降序排列
![image](https://cloud.githubusercontent.com/assets/16954468/14169219/31cc1cda-f759-11e5-98ab-70381937451d.png)

**Comment by analyst004** [comment]
@bpceee  添加一下我的仓库　https://github.com/analyst004/videojj.git
分支名 issue-623

**Comment by shixiaoyanjj** [comment]
test环境测试通过
