### ISSUE TITLE
编辑投票资源时广告banner和外链未同时添加可确认设置

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#629]
#596
测试环境：
>http://test.videojj.com/console/resource/votes

问题描述：
>编辑投票资源时，只添加广告banner或外链，可确认设置
在添加投票热点时导致前端报错无法显示热点

期望结果：
>当添加了广告banner时，点确认无法保存设置，必须填写外链
当添加了外链时，点确认无法保存设置，必须添加广告banner图片
如必须配置广告banner，可限制未填满无法确认设置

![image](https://cloud.githubusercontent.com/assets/16204026/14173070/629f838c-f76e-11e5-8e6a-9f29ab23af5f.png)

**Comment by hzzhujf** [comment]
对，现在就是这个逻辑

**Comment by shixiaoyanjj** [comment]
投票资源只上传『投票banner图』，不填写『外链地址』打点后报错，不显示投票
![image](https://cloud.githubusercontent.com/assets/16204026/14375729/f041b804-fd95-11e5-89ae-efa19cf72c07.png)
@hzzhujf

**Comment by shixiaoyanjj** [comment]
问题描述：有广告banner无外链时，点击广告banner仍可点击跳转
期望结果：无外链应不能点击，只显示图片

**Comment by shixiaoyanjj** [comment]
#706 需求有变，故关闭此issue
