### ISSUE TITLE
[直播]投票结果侧滑信息层未实现主题色

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#635]
测试环境：
>http://7xjfim.com2.z0.glb.qiniucdn.com/test_Iva.js
Iva update at: Thu Mar 31 2016 16:40:03 GMT+0800 (CST)

问题描述：
>控制台配置主题色，PC端直播投票结果侧滑信息层未实现配置
如图
![1](https://cloud.githubusercontent.com/assets/16204026/14176589/5f94db9a-f784-11e5-9c0a-e02437d2d91c.jpg)

期望结果：
>如图
![image](https://cloud.githubusercontent.com/assets/16204026/14176672/c0fdb96a-f784-11e5-8d5a-47db287de032.png)

**Comment by hzzhujf** [comment]
和土豆讨论，为何配合芒果，只是点播的按钮实现主题色，其他还是按照默认状态呈现。

**Comment by shixiaoyanjj** [comment]
需求改变，此bug关闭
