### ISSUE TITLE
[灵眸]登录没有权限的帐号可以完成广告投放但没有成功

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#636]
测试环境：
>http://test01.videojj.com/lingmou.html

问题描述：
>1、打开灵眸页面，没有判断当前灵眸的权限帐号（目前默认为芒果帐号不可更改）
2、登录没有权限的帐号可以完成广告投放但没有成功

期望结果：
>1、显示并可以修改灵眸广告投放的权限帐号
2、设置权限帐号后，登录没有权限的帐号无法投放广告

**Comment by edward32tnt** [comment]
#650

**Comment by lihaiye** [comment]
已增加 ：登陆界面显示是否有权限 的功能，没有权限的帐号无法使用广告投放功能。
