### ISSUE TITLE
[后台管理]资源管理-广告人物库（更新）

### ISSUE THREAD

**Issue by Gracebaby** [Venvy-dev/demand#639]
最新广告人物库原型，请见以下链接
http://yx.tech.videojj.com/ganggaorenwuku_console20160401/#p=广告人物（新）
@iEricKoh @summernini @nekronhuang 

逻辑：资源管理-广告人物库现阶段仅浮层广告可作关联

**Comment by Gracebaby** [comment]
@shixiaoyanjj  @lihaiye   以下为广告人物库更新图示，有任何疑问及时沟通：）


现阶段测试版如下图示
![qq20160405-7 2x](https://cloud.githubusercontent.com/assets/14867684/14281387/4fa89fa6-fb6b-11e5-9892-dc855b52b6e4.png)

现阶段需上线版如下图示
![qq20160405-8 2x](https://cloud.githubusercontent.com/assets/14867684/14281441/c4d99cb2-fb6b-11e5-829d-f1d7f8212f6c.png)

@summernini @iEricKoh

**Comment by shixiaoyanjj** [comment]
#751 
#542

**Comment by Gracebaby** [comment]
最新原型地址：http://yx.tech.videojj.com/console20160425/#p=广告人物库

**Comment by iEricKoh** [comment]
@Gracebaby @summernini 目前还有另外一个 [ticket](https://github.com/Venvy-dev/demand/issues/904)，先简单看了一下，发现两边的需求有重复，请你们确定以哪个为准，如果当前的这个ticket是重复的，请关闭，thanks.
