### ISSUE TITLE
视频管理-视频内热点列表 新增”热点状态“列

### ISSUE THREAD

**Issue by youqiongjoan** [Venvy-dev/demand#642]
视频管理-视频内热点列表 新增”热点状态“列
状态分为：已上线，已下线；放在”创建时间“左侧
如下图：

![image](https://cloud.githubusercontent.com/assets/16954468/14270943/b6be43da-fb25-11e5-9df3-926a3e7aa06e.png)

**Comment by summernini** [comment]
@bpceee 如果你想做成和「资源审核」页面的三种状态（已上线/已拒绝/未审核）一致也是可以。

**Comment by shixiaoyanjj** [comment]
筛选后页码未重置
![qq 20160411165358](https://cloud.githubusercontent.com/assets/16204026/14422111/973a58be-0007-11e6-8ce7-6a8b8a7e4923.jpg)

**Comment by bpceee** [comment]
@summernini 为啥reopen了？

**Comment by bpceee** [comment]
@youqiongjoan 再试下吧 我这儿找不到那么多tag的视频
