### ISSUE TITLE
投票操作成功或过期后台返回数据结构不统一

### ISSUE THREAD

**Issue by Zard1096** [Venvy-dev/demand#643]
```
{
    "status": 0,
    "msg": {
        "__v": 0,
        "_id": "56ea73481e50fc480008a20f",
        "auditStatus": 1,
        "vote": {
            "options": []
        }
        ...
    }
}
```

目前返回结果
投票成功时只返回msg中的内容,
过期(或者可能出错)则返回status:500,msg内容大概为投票已过期类似的错误.

由于会取返回数据更新,目前做法会造成iOS投过期投票崩溃。是后台调整样式还是前端根据目前后台返回数据来修改?

**Comment by summernini** [comment]
现在投票只有，投票中、投票后、投票结果三种状态，所以无论发生错误也好还是过期也好都应该直接展示投票结果的状态页

![1](https://cloud.githubusercontent.com/assets/17739064/14274255/d2430934-fb42-11e5-92bf-9dd4d2109982.png)

**Comment by summernini** [comment]
@bpceee 老毕看一下 紧急

**Comment by bpceee** [comment]
@Zard1096 前端根据目前后台返回数据来修改  

成功接口我忘了写status， 我的锅，但是！因为iva已经上线很久了。。不能改接口了。。你接吧。。

**Comment by Zard1096** [comment]
https://github.com/Venvy-dev/VenvyVideoSDK-iOS/commit/6bdf5cde038cc8d998c4b9eaa6ed8a4ed7e1dbf6

已修复 @summernini  @shixiaoyanjj
