### ISSUE TITLE
新的应用场景页面

### ISSUE THREAD

**Issue by virgoone** [Venvy-dev/demand#646]
#### 应用场景页面改版
* 样式－新的设计稿
![image](https://cloud.githubusercontent.com/assets/8540582/14275206/847c790a-fb48-11e5-9a58-e05c373e51c3.png)

**Comment by virgoone** [comment]
http://front.test.videojj.com:10081/scene

**Comment by lihaiye** [comment]
测试问题整理：
- [ ] 1、在线教育的说明内容为游戏内容，且DEMO视频中没有tag点

![image](https://cloud.githubusercontent.com/assets/17242849/15600889/6d99fde8-241f-11e6-9581-abc6f425e113.png)

- [ ] 2、视频平台的说明内容为游戏内容，且DEMO视频也是游戏直播的视频

![image](https://cloud.githubusercontent.com/assets/17242849/15600968/e4e63542-241f-11e6-8bae-3f79291cfe50.png)

- [ ] 3、垂直社区的说明内容为游戏内容，且DEMO视频也是游戏直播的视频

![image](https://cloud.githubusercontent.com/assets/17242849/15601647/23980f74-2423-11e6-80aa-77a7cd18c84c.png)

- [ ] 4、广告页面的DEMO视频，用的是体育直播当中的极限运动视频

![image](https://cloud.githubusercontent.com/assets/17242849/15602024/6a54e872-2425-11e6-928c-1bad7ec1ef60.png)

**Comment by lihaiye** [comment]
- [ ] **垂直社区**使用的是Flash-Zealer定制的DEMO视频，但这个页面DEMO用的是H5，导致所有热点信息层无法正常显示

![image](https://cloud.githubusercontent.com/assets/17242849/16104466/1ea1282a-33b4-11e6-9f73-32a29999ff09.png)

**Comment by shixiaoyanjj** [comment]
- [ ] 各大平台的ICON不够清晰，建议放大显示
![image](https://cloud.githubusercontent.com/assets/16204026/16448526/86c2c402-3e24-11e6-8006-6f7931399d03.png)

**Comment by lihaiye** [comment]
测试页面图片加载异常，暂时无法测试，报错信息如下：
![image](https://cloud.githubusercontent.com/assets/17242849/16615908/4a6d8720-43ac-11e6-9942-abca5c457a3e.png)
