### ISSUE TITLE
重力感应手机横屏时查看官网显示错误

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#647]
测试环境：
>http://videojj.com/

![image](https://cloud.githubusercontent.com/assets/16204026/14277218/d76ae0b4-fb54-11e5-903e-a6ab7eefdc1e.png)

**Comment by WalterGuo** [comment]
和土豆商量，不需要做手机横屏

**Comment by lihaiye** [comment]
确认暂时不需要做手机横屏，先关闭
