### ISSUE TITLE
[后台管理]术语需一致

### ISSUE THREAD

**Issue by Gracebaby** [Venvy-dev/demand#648]
Dear 老毕@bpceee @summernini 

 **后台管理** 术语需要统一，请将以下名词作修改

1.【项目概览】主数据显示区域，“云链总数”调整为“热点总量”
![qq20160405-3 2x](https://cloud.githubusercontent.com/assets/14867684/14277702/f6bfbc3a-fb56-11e5-8a78-ad923cdd3e46.png)

2.【数据统计】数据查询列表区域显示项，“信息类型”改为“信息层类型”
![qq20160405-4 2x](https://cloud.githubusercontent.com/assets/14867684/14277715/0470b03c-fb57-11e5-8ced-45325eeec0d5.png)

3.【热点列表】热点列表区域显示项，“热点类型”改为“信息层类型”（注：此项需要做筛选功能）
![qq20160405-5 2x](https://cloud.githubusercontent.com/assets/14867684/14277719/0e1345a0-fb57-11e5-880d-1054e567cdeb.png)

4.【视频管理】进入单视频详情页，视频内热点列表区域显示项，“显示类型”改为“热点属性”
![qq20160405-6 2x](https://cloud.githubusercontent.com/assets/14867684/14277727/154d851a-fb57-11e5-81f6-6a366e8a6b0b.png)

5.所有“xxx数”都改为“xxx量” ，如：“视频总数”即改为“视频总量”

**Comment by bpceee** [comment]
@netpi 上线后提醒我跑一个迁移脚本。

**Comment by shixiaoyanjj** [comment]
test环境测试通过

**Comment by shixiaoyanjj** [comment]
信息层类型的术语名称不准确 @Gracebaby 
![image](https://cloud.githubusercontent.com/assets/16204026/14343086/3340c89a-fcd1-11e5-8318-0c71dacf5ced.png)

**Comment by Gracebaby** [comment]
请注意！！！将“热点图标”移出信息层类型 @bpceee

**Comment by shixiaoyanjj** [comment]
test环境测试通过

**Comment by shixiaoyanjj** [comment]
test.videojj.com信息层类型的术语名称不显示
![image](https://cloud.githubusercontent.com/assets/16204026/14457020/90dc9d5a-00da-11e6-80f7-d7c75c4ad09e.png)

**Comment by bpceee** [comment]
@shixiaoyanjj @summernini 那请问以哪个为准？？

**Comment by shixiaoyanjj** [comment]
哦，明白了，sorry

**Comment by lihaiye** [comment]
http://videojj.com/console/  正式环境测试通过
