### ISSUE TITLE
灵眸登陆界面显示是否有权限

### ISSUE THREAD

**Issue by edward32tnt** [Venvy-dev/demand#650]
根据需求文档 #549 

登陆界面需要显示 是否有加轨迹权限

如果没有权限任然需要重新登陆

**Comment by edward32tnt** [comment]
目前有个需求 

需要后台提供一个jsonp 的接口来完成 账号登出功能 @netpi

**Comment by lihaiye** [comment]
http://test01.videojj.com/lingmou.html    验证 已添加相关功能
