### ISSUE TITLE
右上角增加账号切换功能

### ISSUE THREAD

**Issue by edward32tnt** [Venvy-dev/demand#651]
需求文档 #549 

在lingmou 所以也面增加账号切换功能

**Comment by edward32tnt** [comment]
需要后台 有个jsonp 的接口 登出videojj 账号 @netpi

**Comment by lihaiye** [comment]
http://test01.videojj.com/lingmou.html   测试已实现切换帐号按钮功能

**Comment by edward32tnt** [comment]
@shixiaoyanjj @lihaiye 

这个issue 需要等到 #674 上线后才能测试

**Comment by lihaiye** [comment]
http://test01.videojj.com/lingmou.html  切换帐号按钮功能验证通过
