### ISSUE TITLE
[红包]在优惠券红包编辑窗口任意输入框按回车会打开上传文件窗口

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#652]
#565

测试环境：
>http://test.videojj.com/console/resource/redPackets

问题描述：
>1、打开红包-优惠券编辑窗口
2、激活任意输入框
3、按键盘回车

![image](https://cloud.githubusercontent.com/assets/16204026/14304696/d7f1b75e-fbe7-11e5-88df-05833b8c8b45.png)

**Comment by iEricKoh** [comment]
@shixiaoyanjj 所以你是希望的结果是：回车之后，不打开 upload 的窗口？？？

**Comment by shixiaoyanjj** [comment]
@Gracebaby 大侠定下需求吧

**Comment by iEricKoh** [comment]
@shixiaoyanjj 这不是BUG. 你描述的情况是 Chrome 下的默认行为。类似你按下``Ctrl+O``, 一样会弹出让用户选择文件的窗口。

当 form(表单) 存在上传文件的组件时，回车后允许你选择文件上传。
当成功上传文件后，如果你的 form 里面存在一个 submit button, 再次回车后，会执行表单的提交。

**Comment by Gracebaby** [comment]
暂不修改 @shixiaoyanjj  @iEricKoh  谢谢：）
