### ISSUE TITLE
tag上传cdn kue阻塞问题 --> 改用阿里MNS

### ISSUE THREAD

**Issue by bpceee** [Venvy-dev/demand#656]
先加个超时？mns无法确保先后顺序。。。

**Comment by shixiaoyanjj** [comment]
测试点：
>添加热点
热点列表即时显示，状态默认已上线

- [ ] 广告
- [ ] 投票
- [ ] 卡牌
- [ ] 百科
- [ ] 人物
- [ ] 地点
- [ ] 商品
- [ ] 红包

>删除热点
热点列表即时更新，状态变为已下线

- [ ] 广告
- [ ] 投票
- [ ] 卡牌
- [ ] 百科
- [ ] 人物
- [ ] 地点
- [ ] 商品
- [ ] 红包

>热点信息
标题正确显示，投放平台正确勾选，开始时间和持续时间与热点在视频内一致

- [ ] 热点标题
- [ ] 投放平台PC
- [ ] 投放平台Mobile
- [ ] 开始时间
- [ ] 持续时间
