### ISSUE TITLE
[直播]投票侧滑信息层显示格式错误

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#660]
测试环境：
>http://yzbissb.top/mangguotv_live.html?videojjhost=test.videojj.com
Iva update at: Wed Apr 06 2016 15:31:31 GMT+0800 (CST)

![image](https://cloud.githubusercontent.com/assets/16204026/14309412/d8d9c338-fc0e-11e5-9d0b-c7613433b699.png)

**Comment by summernini** [comment]
老朱赶紧修复！今天必须搞定！

**Comment by summernini** [comment]
毅霆说已经改好了 @shixiaoyanjj 测测哈~

**Comment by shixiaoyanjj** [comment]
测试通过
Iva version：http://7xjfim.com2.z0.glb.qiniucdn.com/test_Iva.js
Iva update at: Mon Apr 11 2016 13:30:49 GMT+0800 (CST)
