### ISSUE TITLE
[灵眸]广告设置界面，混合广告页面显示为空

### ISSUE THREAD

**Issue by lihaiye** [Venvy-dev/demand#665]
测试地址：
>http://test01.videojj.com/lingmou.html

问题描述：
>广告设置界面，（帐号下有混合资源的情况下）混合广告页面显示为空

期望表现：
>混合一栏显示该帐号后台的：广告人物+广告地点+广告物品 下的资源

![image](https://cloud.githubusercontent.com/assets/17242849/14314287/fa46b3e0-fc28-11e5-81c9-290b23ac4c7b.png)

**Comment by lihaiye** [comment]
#655

**Comment by edward32tnt** [comment]
这里应该需要 蘑菇关注一下 @Mancy1011 

老朱的混合云链 打点时 是在右上角有个筛选  人物 地点 物品，

要是我们硬要把这样的结构放进来 会不会使妹子们误解

**Comment by Mancy1011** [comment]
@edward32tnt 
老朱修复了筛选功能不显示的bug……需要把“混合”拆分为“人物”、“地点”、“物品”，原型已更新 #549

**Comment by edward32tnt** [comment]
#672

**Comment by lihaiye** [comment]
http://test01.videojj.com/lingmou.html  验证通过
