### ISSUE TITLE
增加一个接口删除cookie中的token

### ISSUE THREAD

**Issue by edward32tnt** [Venvy-dev/demand#674]
增加一个接口删除cookie中的token

**Comment by edward32tnt** [comment]
@shixiaoyanjj 

测试方法：

1. 登陆一个账号
2. 访问 videojjhost.com/api/jsonp/delCookie.js
3. 查看 videojjhost.com 是否登出了[登出则测试成功]

**Comment by lihaiye** [comment]
@edward32tnt

**Comment by edward32tnt** [comment]
@lihaiye 

因为还在test.videojj.com上

**Comment by lihaiye** [comment]
Test环境测试结果：
>登陆：test.videojj.com
访问：http://test.videojj.com/api/jsonp/delCookie.js
再登陆：http://test.videojj.com/  查看，帐号成功登出

测试通过
