### ISSUE TITLE
[灵眸]在视频设置界面加APPKey

### ISSUE THREAD

**Issue by Mancy1011** [Venvy-dev/demand#675]
#549

**Comment by lihaiye** [comment]
目前只看到APPKEY输入项
![image](https://cloud.githubusercontent.com/assets/17242849/14420232/7c8cd438-fffd-11e5-9768-4bce41c37403.png)

**Comment by edward32tnt** [comment]
@netpi 需要东泽的配合 增加一个接口查看 该用户是否对该appkey 有权限

**Comment by edward32tnt** [comment]
现在最后一步会告诉你 错在哪里

**Comment by Mancy1011** [comment]
原型已更新 #549

**Comment by lihaiye** [comment]
1、其他条件填写正确的情况下：
不填写APPKEY时，点开始分析提示为：error base64 appkey :undefined
输入错误的APPKEY时，点开始分析提提示为：no power ak:NJDIqcXo
2、输入帐号没有权限的APPKEY，设置广告后点击开始投放，提示：Error: no power user : 56af2f6cfb47409e0151c861

建议将错误提示信息改为中文提示

**Comment by edward32tnt** [comment]
@Mancy1011 即使at 了 也不太容易发现这个issues 你重新建一个吧

**Comment by Mancy1011** [comment]
@edward32tnt OK。关于后端错误提示显示中文的需求之前已和东泽沟通，他建议让前端来做

**Comment by edward32tnt** [comment]
move to #782

**Comment by lihaiye** [comment]
添加APPKey功能已实现，提示信息在issues 782中跟进
