### ISSUE TITLE
[灵眸]图表支持缩放

### ISSUE THREAD

**Issue by Mancy1011** [Venvy-dev/demand#676]
#549

**Comment by lihaiye** [comment]
图表放大后，出现重置按钮，重置按钮用中文  @Mancy1011 
![image](https://cloud.githubusercontent.com/assets/17242849/14424610/9d278a6e-0014-11e6-9bca-1137a907438b.png)

**Comment by Mancy1011** [comment]
@lihaiye 原型中按钮为中文

**Comment by edward32tnt** [comment]
好的 改成了 重置

**Comment by lihaiye** [comment]
http://test01.videojj.com/lingmou.html  测试通过
