### ISSUE TITLE
[直播]投票打点成功后报错

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#677]
测试环境：
>http://7xjfim.com2.z0.glb.qiniucdn.com/test_Iva.js
Iva update at: Fri Apr 08 2016 13:40:51 GMT+0800 (CST)

问题描述：
>打点成功后刷新视频不显示热点
![image](https://cloud.githubusercontent.com/assets/16204026/14375184/622ebea8-fd91-11e5-8f79-eaf66bd40e82.png)

**Comment by hzzhujf** [comment]
打的是什么点？ @shixiaoyanjj

**Comment by shixiaoyanjj** [comment]
版本已更新，无法重现，暂时关闭
