### ISSUE TITLE
[直播]芒果测试环境剩余问题

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#694]
测试环境：
>http://honey.hunantv.com/zt/zt-happygirl/template/page-index-1.html?videojjhost=test.videojj.com#
http://7xr2th.com2.z0.glb.qiniucdn.com/mangguotv_Iva.js
Iva update at: Mon Apr 11 2016 19:09:20 GMT+0800 (CST)

问题描述：
>播放广告时会显示IVA互动层

期望结果：
>播放广告时不显示IVA互动层
![qq 20160408180125](https://cloud.githubusercontent.com/assets/16204026/14380978/5b8197a0-fdb5-11e5-852e-23f8470b53e3.jpg)

**Comment by shixiaoyanjj** [comment]
打开信息层时暂停视频，**信息层未隐藏**
继续播放，**信息层异常关闭，无接口统计showDgTime**
![image](https://cloud.githubusercontent.com/assets/16204026/14426461/bfff3548-0021-11e6-9c92-d04fcf38e170.png)

**Comment by shixiaoyanjj** [comment]
问题描述：
打开信息层后隐藏了全部热点
期望结果：
打开信息层只隐藏对应的热点

**Comment by shixiaoyanjj** [comment]
问题描述：
打开信息层后，点击视频，未关闭信息层

期望结果：
关闭信息层

**Comment by shixiaoyanjj** [comment]
问题描述：
+ 打开信息层时，信息层遮挡了播放器控制栏
期望结果：
+ 信息层打开时不影响播放器控制栏的操作

**Comment by shixiaoyanjj** [comment]
问题描述：
+ 打开信息层时，点击其他视频的热点信息层叠加
期望结果：
+ 信息层打开时关闭原来的信息层

**Comment by shixiaoyanjj** [comment]
问题描述：
+ 打开投票的信息层时，播放器控制栏无法操作
![image](https://cloud.githubusercontent.com/assets/16204026/14456179/2e570f84-00d6-11e6-9d86-c727a9ab5925.png)

期望结果：
+ 信息层打开时不影响播放器控制栏操作

**Comment by hzzhujf** [comment]
“播放广告时不显示IVA互动层”这个问题和点播一样，得芒果的技术去做。
让芒果的技术在广告之后再调用互动层。
