### ISSUE TITLE
红包 前端打点&后台设置

### ISSUE THREAD

**Issue by Mancy1011** [Venvy-dev/demand#696]
> 原型更新20160418
http://yx.tech.videojj.com/Hongbaodadian_web_20160418/%E7%BA%A2%E5%8C%85%20%E5%89%8D%E7%AB%AF%E6%89%93%E7%82%B9%E8%AE%BE%E7%BD%AE20160418.pdf

> 原型更新20160412
http://yx.tech.videojj.com/Hongbaodadian_web_20160412/%E7%BA%A2%E5%8C%85%20%E5%89%8D%E7%AB%AF%E6%89%93%E7%82%B9%E8%AE%BE%E7%BD%AE20160412.pdf

> 前端打点原型：
http://yx.tech.videojj.com/Hongbaodadian_web_20160408/%E7%BA%A2%E5%8C%85%20%E5%89%8D%E7%AB%AF%E6%89%93%E7%82%B9%E8%AE%BE%E7%BD%AE20160407.pdf

**Comment by Gracebaby** [comment]
以下为“后台红包批量打点”原型说明：

**“口令红包”及“优惠码红包”都加入批量打点功能**
场景一：选择“关联项目”
![default](https://cloud.githubusercontent.com/assets/14867684/14419047/8d3dc3e4-fff5-11e5-94e5-ccefd08046a1.png)

场景二：选择“关联项目”及“关联栏目”
![default](https://cloud.githubusercontent.com/assets/14867684/14419059/a8daa59a-fff5-11e5-8d5d-b73fcd1fecfd.png)

场景三：未关联
![default](https://cloud.githubusercontent.com/assets/14867684/14419069/c2cc1542-fff5-11e5-8216-d5c1fdef118e.png)

**Comment by iEricKoh** [comment]
@nekronhuang Hey, 以下是API，供你参考。

````
POST /api/tags/cronjob HTTP/1.1
Host: videojj.com
Content-Type: application/json
Cache-Control: no-cache
Postman-Token: 3069f0ef-d92d-453f-cadf-ef670b27e71b

{
    "id": 123456,
    "startDt": "2016-04-19 13:52:00", 
    "duration": 20
}
````

我需要的就只是 ``startDt``(*format it as YYYY-MM-DD HH:mm:ss*) 和 ``duration``(*seconds*).

除此以外， enable / disable tag 的 API 应该需要 tag 的信息吧？@netpi 看你需要什么，请你补充。

**Comment by netpi** [comment]
@iEricKoh @nekronhuang 建议
```
{
    "id": 123456,
    "startDt": "2016-04-19 13:52:00",  // 这部分建议用时间戳吧 这样处理方便些吧 @nekronhuang觉得呢
    "duration": 20
}

**Comment by nekronhuang** [comment]
@netpi @iEricKoh 
好的，补充说明一下，没有startDt就是立刻发送

**Comment by iEricKoh** [comment]
@netpi @nekronhuang  Sorry, 时间戳是什么意思？ timestamp??

**Comment by iEricKoh** [comment]
@nekronhuang 

FYI.

````
POST /api/tags/cronjob HTTP/1.1
Content-Type: application/json

{
    "id": 123456,
    "startDt": 1461049556495,
    "duration": 20
}
````

**Comment by iEricKoh** [comment]
@nekronhuang 你 post 一个 tag 的时候，有什么字段是可以让我知道该 tag 是属于红包的吗？
因为启动 job 的时候应该是需要当类型为**红包**时，才创建 job 的。

**Comment by iEricKoh** [comment]
@nekronhuang 我知道了，dgCat.

**Comment by nekronhuang** [comment]
补充说摩纳哥
`duration`单位以前的老规则是ms

**Comment by iEricKoh** [comment]
@netpi 我这里的改动完成了，等你添加 enable / disable tag 的那一部分 API.

branch: ``demand-issue-696``

**Comment by lihaiye** [comment]
@iEricKoh 
>创建新资源时无法选择关联项目，老资源关联项目也显示为空并且无法选择 
![image](https://cloud.githubusercontent.com/assets/17242849/14640310/8daa70a0-0673-11e6-93e1-b30503a54db7.png)

**Comment by iEricKoh** [comment]
@netpi 下面这段 disable tag 的代码，video 是什么？是需要打 tag 的时候传过来，还是我们查？现在我们只有 tag.

还有，如果 publish 成功的话， 参数 x 会得到什么？

````
    var mqttMsg = {
      type: 'hideTag',
      msg: {
        tagId: tagId
      }
    }
    mqttClient.publish('videojj/' + video,JSON.stringify(mqttMsg) , function (x) {
      console.log(x)
        // client.end()
    })

````

**Comment by shixiaoyanjj** [comment]
- [ ] 控制台红包展示时间结束后，热点列表中红包是已上线状态

**Comment by iEricKoh** [comment]
@lihaiye 
> 创建新资源时无法选择关联项目，老资源关联项目也显示为空并且无法选择

关于你描述的这个问题，是在什么时候发生的？能告诉我是在昨天的 7:00 pm 之后才出现的这个问题？还是之前就已经存在了？

**Comment by lihaiye** [comment]
@iEricKoh 
是昨天晚上9点多更新后出现的，现在已经OK了，谢谢~

**Comment by iEricKoh** [comment]
@lihaiye 是今天早上过来才自动好的？因为我需要排除昨晚出现问题会不会是我们合并代码时候造成的。

**Comment by lihaiye** [comment]
@iEricKoh 
是的，今天上午十点左右发现已经不存在这个问题了

**Comment by shixiaoyanjj** [comment]
红包功能需求建议：

- [ ] 区分即时红包和定时红包

- [ ] 显示定时红包的开始时间

**Comment by shixiaoyanjj** [comment]
@Mancy1011 
请确认红包打点配置的持续时间为程序写死的120秒，独立存在且无法通过控制台配置修改，包括点播和直播

**Comment by lihaiye** [comment]
@nekronhuang 
建议优下前端打点功能：
1、当打点时间为55分以后，选择定时投放给的默认开始时间 分钟为60+，建议自动转换成正常时间
2、当确认打点的时间与开始投放时间间隔少于4分钟，出现提示后 建议能自动生成新的默认开始时间

**Comment by Mancy1011** [comment]
红包打点的默认持续时间可根据控制台修改

**Comment by lihaiye** [comment]
@nekronhuang @androidlgf 
- [ ] 打点时可选择PC或Mobile显示，只勾选PC时，PC和安卓都显示；只勾选Mobile时，PC和安卓都显示红包，需做判断

**Comment by shixiaoyanjj** [comment]
- [x] 定时红包打点后刷新直接显示红包
