### ISSUE TITLE
[Flash]ZEALER 测试问题汇总

### ISSUE THREAD

**Issue by lihaiye** [Venvy-dev/demand#697]
测试地址：
>http://madoka.moe:1460/

问题整理：
>1、投票：展开选项栏后鼠标移动至投票按钮时菜单会缩回
2、信息层：打开信息层会出现信息层没有居中显示的情况【刷新页面后第一次打开信息层容易出现】
3、混合：混合广告点赞后，数字显示建议显示在点赞按钮后面
4、动效：’翻转‘特效转一圈后不再循环，需优化
5、热点：热点显示逻辑和其他端不一致：同时出现多个热点时，点击其中一个后所有热点都会隐藏【目前逻辑为：同时多个热点，点击其中一个只隐藏自己，其他热点仍然显示】
6、信息层：信息关闭按钮文字颜色太暗了一点，建议优化
7、广告信息层比例与土豆设计搞不一致，需要优化
8、投票UI还是老的，目前其他端已更新最新样式，需要优化
9、热点：热点图标和文字标题栏衔接位置，与其他端有些不一致，建议优化
FLASH：![image](https://cloud.githubusercontent.com/assets/17242849/14382702/5872ec6e-fdc2-11e5-9a25-ad2609b703c7.png)
H5：![image](https://cloud.githubusercontent.com/assets/17242849/14382670/184ede5e-fdc2-11e5-9b0f-fb236e59b35a.png)
10、混合：混合广告浮层图显示比例与后台上传的图片比例不一致

![image](https://cloud.githubusercontent.com/assets/17242849/14382354/b7f12834-fdbf-11e5-854b-cfe8365fccee.png)

![image](https://cloud.githubusercontent.com/assets/17242849/14382376/df9ee4ac-fdbf-11e5-8777-48d30d22c6b4.png)

**Comment by chndyyang** [comment]
@williamling 小福修一下样式方面的不同

**Comment by williamling** [comment]
@lihaiye  #697  
1、解决
2 这里没有重现 不知道什么原因
3、解决
4   解决
5   暂时先不管
6    解决
7   解决
8   等待新ui一起更新
9  解决
10 解决

**Comment by lihaiye** [comment]
1、投票：展开选项栏后鼠标移动至投票按钮时菜单会缩回 ---Passed
3、混合：混合广告点赞后，数字显示建议显示在点赞按钮后面---Passed
4、动效：’翻转‘特效转一圈后不再循环，需优化---Passed
6、信息层：信息关闭按钮文字颜色太暗了一点，建议优化---Passed
7、广告信息层比例与土豆设计搞不一致，需要优化---Passed
9、热点：热点图标和文字标题栏衔接位置，与其他端有些不一致，建议优化---Passed
10、混合：混合广告浮层图显示比例与后台上传的图片比例不一致---Passed
