### ISSUE TITLE
芒果-外链点击率转化高-数据排查

### ISSUE THREAD

**Issue by youqiongjoan** [Venvy-dev/demand#699]
旋风孝子20160409期，2016/4/10的外链转化率如下图
![image](https://cloud.githubusercontent.com/assets/16954468/14417170/840566bc-ffe4-11e5-8900-c9ac51883c4c.png)
麻烦查一下，是否有异常的地方。
我看了一下，视频管理中的数据，01:16:53这个点的显性点，转化率特别高
@shuizhuvenvy 小乌龟，麻烦看一下，有没有问题

**Comment by shixiaoyanjj** [comment]
点击PVC广告MP4-跳转外链，clicklink接口测试无异常
点击广告大图-跳转外链，clicklink接口测试无异常
点击查看详情按钮-跳转外链，clicklink接口测试无异常
