### ISSUE TITLE
[灵眸]相同过滤条件下，视频首次分析的片段数量与重新过滤分析的数量不一致

### ISSUE THREAD

**Issue by lihaiye** [Venvy-dev/demand#701]
#549

测试地址：
>http://test01.videojj.com/lingmou.html
视频：http://7xr9rd.dl1.z0.glb.clouddn.com/%E5%BF%AB%E6%9C%AC0319.mp4 （取最后40分钟）

问题描述：
>输入APPKEY、视频，以及分析时间段后，点击开始分析
默认分析时长超过3秒次数超过1秒的关键词结果和片段数量
重新选择过滤条件，再选回“时长超过3秒次数超过1秒”时，显示的关键词数量与开始识别的数量不一致

首次分析结果：
![image](https://cloud.githubusercontent.com/assets/17242849/14419271/3faa3e8a-fff7-11e5-88ba-8476f7230f4e.png)

重新选择过滤条件后的分析结果：
![image](https://cloud.githubusercontent.com/assets/17242849/14419367/fd853cde-fff7-11e5-9bb9-5939803bc444.png)

**Comment by edward32tnt** [comment]
由于有个帧率需要在分析以后才有 所以默认比较超过0秒 不用等分析

**Comment by lihaiye** [comment]
http://test01.videojj.com/lingmou.html    【首分分析的过滤条件更改为：时长大于0秒+次数大于1次】
验证通过
