### ISSUE TITLE
新增板块：数据统计-信息层统计

### ISSUE THREAD

**Issue by youqiongjoan** [Venvy-dev/demand#702]
需求来源：老郭-战旗
需求：需要查询每个信息层的数据表现情况

原型地址：http://yx.tech.videojj.com/Lingzhi_XinxicengTongJi_20160523/#p=信息层统计（增加可视化设计）

注意点：
1、维度：分栏目、分品牌、分时间段

@analyst004

**Comment by lihaiye** [comment]
### 数据统计-信息层统计 页面测试

**信息层概要**
- [ ] 图文显示信息层曝光量、外链点击量、外链点击率
- [ ] 选择所有栏目时，数据显示正确
- [ ] 选择指定栏目时，数据显示正常
- [ ] 选择不同时间段，数据显示正常

**统计明细**
- [ ] 选择所有栏目时+所有信息层时，数据显示正常
- [ ] 选择所有栏目+指定信息层时，数据显示正常
- [ ] 选择指定栏目+所有信息层时，数据显示正常
- [ ] 选择指定栏目+指定信息层时，数据显示正常
- [ ] 信息层选择列表可输入关键字搜索正常
- [ ] 热点类型筛选正常
- [ ] 视频类型筛选正常
- [ ] 信息层类型筛选正常

**问题：**
- [ ] 信息层播放量 应修改为”信息层曝光量“

Question-需产品确认： @youqiongjoan 
1、产品原型中：数据类型 信息层独立曝光量UV、外链曝光量、外链独立点击量UC 未实现
2、产品原型中：可选择品牌的功能未实现
3、目前实现的统计明细表内容，与产品原型设计不一致

**Comment by vickymin** [comment]
前两个个问题的产生原因为数据上暂时无法满足，第三个问题，统计明细的表内容做过修改

**Comment by lihaiye** [comment]
问题：信息层播放量 应修改为”信息层曝光量“   
不影响上线，可之后修复，在以下ISSUES跟进：#957
