### ISSUE TITLE
[灵眸]广告投放错误（APPKey），增加回到广告设置界面按钮

### ISSUE THREAD

**Issue by Mancy1011** [Venvy-dev/demand#704]
#549

**Comment by edward32tnt** [comment]
@Mancy1011 没看到什么改变 411的

**Comment by Mancy1011** [comment]
@lihaiye 20160411测试情况
1、其他条件填写正确的情况下：
不填写APPKEY时，点开始分析提示为：error base64 appkey :undefined
输入错误的APPKEY时，点开始分析提提示为：no power ak:NJDIqcXo
2、输入帐号没有权限的APPKEY，设置广告后点击开始投放，提示：Error: no power user : 56af2f6cfb47409e0151c861

建议将错误提示信息改为中文提示

----------------------------

@netpi 能否将后端的错误提示在前端显示为中文？

**Comment by Mancy1011** [comment]
由于原型更改，该issue关闭
