### ISSUE TITLE
后台编辑 广告外链必填

### ISSUE THREAD

**Issue by Mancy1011** [Venvy-dev/demand#706]
需求描述

> 广告云窗、混合云窗、云图的品牌广告，红包广告banner，在后台编辑时必须添加外链
如果没有添加外链，后台需提醒用户
百科和卡牌在后台已经实现不添加外链无法提交的功能
投票默认图片不需要添加外链

---------------

> 20160517新增 云图外链必填

**Comment by Gracebaby** [comment]
@iEricKoh  麻烦Eric在以上说到的位置 增加输入反馈：）
@shixiaoyanjj 麻烦小乌龟，稍后测试一下：）

**Comment by shixiaoyanjj** [comment]
@Gracebaby 
收到，确认可以测试了请移到测试池

**Comment by shixiaoyanjj** [comment]
#850

**Comment by summernini** [comment]
在850进行跟踪，此票关闭
