### ISSUE TITLE
投票接口使用消息队列

### ISSUE THREAD

**Issue by netpi** [Venvy-dev/demand#707]
投票接口使用消息队列插入数据库

**Comment by shixiaoyanjj** [comment]
@hzzhujf @nekronhuang 

新接口api/dgs/vote/v2

**点播**

>- [ ] 投票
- [ ] 百科点赞
- [ ] 广告点赞
- [ ] 混合人物点赞
- [ ] 混合地点点赞
- [ ] 混合商品点赞


**直播**

>- [ ] 投票
- [ ] 广告点赞
