### ISSUE TITLE
[灵眸]广告设置下增加筛选栏目的功能

### ISSUE THREAD

**Issue by Mancy1011** [Venvy-dev/demand#709]
#549

**Comment by lihaiye** [comment]
http://test01.videojj.com/lingmou.html  测试结果为：
1、广告设置页面，只显示对应项目资源
2、没有筛选栏目的功能

@Mancy1011  麻烦小蘑菇确认下需求

**Comment by Mancy1011** [comment]
@lihaiye 筛选栏目功能在原型中更新好了

**Comment by lihaiye** [comment]
@Mancy1011 
目前测试结果为：
>1、未筛选栏目时，显示的是对应APPKEY**项目下**的资源，如图1
2、筛选栏目后，显示的是帐号下**所有的资源**，包括：未填写项目的、未填写栏目的、其他栏目的，并没有做分类筛选，如图2

**需要定栏目筛选的规则**

图1：
![image](https://cloud.githubusercontent.com/assets/17242849/14808619/63c75654-0bb9-11e6-854c-c4e129b43252.png)

图2：
![image](https://cloud.githubusercontent.com/assets/17242849/14808624/6f23bb8c-0bb9-11e6-8df8-72d8eb0f1910.png)

**Comment by edward32tnt** [comment]
@lihaiye 这个功能要等到老毕的一个功能上线

**Comment by lihaiye** [comment]
http://test01.videojj.com/lingmou.html 测试通过
