### ISSUE TITLE
[直播]后台资源添加了监控代码后，打开信息层未统计到相关信息

### ISSUE THREAD

**Issue by lihaiye** [Venvy-dev/demand#711]
测试地址：
>http://yzbissb.top/mangguotv_live.html?videojjhost=test.videojj.com

问题描述：
>直播：广告、红包、投票  资源添加admaster或者Miaozhen监控代码后
线上点击打开后信息层，控制台没有收到相关统计信息

![image](https://cloud.githubusercontent.com/assets/17242849/14457241/d9ec0d0e-00db-11e6-8289-60d4f234c2e2.png)

![image](https://cloud.githubusercontent.com/assets/17242849/14457318/42e6b7f0-00dc-11e6-8f6f-d184e557c820.png)

**Comment by lihaiye** [comment]
@hzzhujf @androidlgf @Zard1096  三端直播都需要添加监控代码统计

**Comment by androidlgf** [comment]
@lihaiye 添加完成

**Comment by lihaiye** [comment]
PC端直播：信息层曝光监控统计验证通过
