### ISSUE TITLE
[资源管理]新建资源后编辑，点击确认无法保存

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#712]
测试环境：
>http://test.videojj.com/console/resource/

问题描述：
>（广告）（云图）（百科）（卡牌）（投票）（广告人物）（广告地点）（广告物品）
新建资源后编辑，点击确认提示：格式错误，无法保存
![catch 04-12-16-55-29](https://cloud.githubusercontent.com/assets/16204026/14457756/7117b2f2-00df-11e6-8596-04646808036c.jpg)

**Comment by iEricKoh** [comment]
@shixiaoyanjj 如果该问题已经fixed, 请 close.
