### ISSUE TITLE
[MQTT]测试内容

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#713]
**直播**
>广告 投票 红包

- [x] PC
- [x]  Android
- [x] IOS

**点播**
>广告 投票 百科 云图 混合 卡牌 红包

- [x] PC
- [x]  Android
- [x] IOS

**控制台**

- [x] 资源 广告 投票 百科 云图 混合 卡牌 红包 图标
- [x] 数据 视频播放量 热点展示量 热点点击量 外链点击量

**Comment by shixiaoyanjj** [comment]
##直播：
+ 新接入的用户无法看到已添加的热点

**Comment by lihaiye** [comment]
直播PC端：
>1、新建一个只有广告banner但未添加外链的投票资源，打点后不显示热点
2、将该资源添加外链后，再打点可以看到热点，但无法投票，如图：

![image](https://cloud.githubusercontent.com/assets/17242849/14460986/29418f16-00f3-11e6-8a52-cb9b025f1f56.png)

**Comment by lihaiye** [comment]
@androidlgf @Damonyg 
Andriod点播问题：
1、广告和百科点赞后，重新打开显示点赞数量为0
![image](https://cloud.githubusercontent.com/assets/17242849/14493374/b132891a-01b7-11e6-9caa-be6a8090dd7a.png)

2、三星测试机：卡牌提示内容文字格式显示需修改
![image](https://cloud.githubusercontent.com/assets/17242849/14493402/dce8c060-01b7-11e6-82f6-eb85c8b0f4dd.png)

**Comment by shixiaoyanjj** [comment]
@Zard1096 
IOS点播问题：
- [ ] 广告和百科点赞数量不增加

**Comment by Zard1096** [comment]
@shixiaoyanjj  点赞数为后台问题，已修复

**Comment by lihaiye** [comment]
PC端点播问题：

- [ ] 1、添加红包后看不到红包，刷新页面后红包出现，并且重新开始倒计时。每次拖动进度条到红包出现时间，红包都会重新出现重新计时

**Comment by shixiaoyanjj** [comment]
正式环境：

- [ ] IOS点赞数量未统计
- [ ] IOS投票数量未统计

**Comment by lihaiye** [comment]
正式环境：

- [ ] Android点赞数量未统计
- [ ] Android投票数量未统计
