### ISSUE TITLE
移动端 icon最佳显示尺寸

### ISSUE THREAD

**Issue by Mancy1011** [Venvy-dev/demand#718]
icon和播放器的比例：
红包 85/375  64/667
投票 60/375 180/667
卡牌 100/375 80/667
云图 78/375 130/667

请按以上比例，限制前端打点的最小icon尺寸
（红包打点最小尺寸 144*192）

**Comment by nekronhuang** [comment]
红包现在宽高比是3:4，但是64/85不是3:4我凌乱了。。。 @Mancy1011 @ryantudou

**Comment by nekronhuang** [comment]
修改下说明：
> 打点的最小尺寸需要根据打点时播放器的大小进行动态调整

- [ ] 红包
- [ ] 投票
- [ ] 卡牌
- [ ] 云图

**Comment by nekronhuang** [comment]
补充说明：
> 情况和移动端讨论后发现过于复杂，不能达到所有情况适配，但可以满足绝大部分情况

**Comment by nekronhuang** [comment]
移动端显示太小，提高移动端比例
`64/667` -> `69/667`
