### ISSUE TITLE
移动端播放视频的时候允许传视频名称

### ISSUE THREAD

**Issue by summernini** [Venvy-dev/demand#720]
移动端播放视频的时候允许传视频名称。接口后端有的。

**Comment by Zard1096** [comment]
@summernini 已添加
https://github.com/Venvy-dev/VenvyVideoSDK-iOS/commit/cd17990e2e52ee09095e2daf41f710a7a2ee4eb1

**Comment by summernini** [comment]
@androidlgf 防防 也加下

**Comment by androidlgf** [comment]
@summernini @lihaiye 已添加

**Comment by hzzhujf** [comment]
PC端本来就有的
