### ISSUE TITLE
新的灵悦产品介绍頁

### ISSUE THREAD

**Issue by WalterGuo** [Venvy-dev/demand#722]
设计稿
![image](https://cloud.githubusercontent.com/assets/8540582/14519408/44f0c376-0251-11e6-9700-99f8c18106c7.png)

**Comment by WalterGuo** [comment]
[测试地址](http://front.test.videojj.com:10081/player)
[上线地址](http://videojj.com/player)

**Comment by lihaiye** [comment]
测试反馈：
1、**热点特效自定义设置**  模块 下方的按钮为`添加教程`，建议修改为`查看教程`
2、**全新互动形态 革新视频营销**  模块 下方`更多精彩` 按钮点击无效
3、**全新互动形态 革新视频营销**  模块中`调研问答` 用的图片内容有错别字，是否需更换图片素材

![image](https://cloud.githubusercontent.com/assets/17242849/14876725/cb8fa6e2-0d49-11e6-9d22-78fa4c8a6013.png)

**Comment by WalterGuo** [comment]
@lihaiye 已修复 测试环境同上

**Comment by lihaiye** [comment]
http://front.test.videojj.com:10081/player/  test环境验证通过

**Comment by lihaiye** [comment]
正式环境验证通过
