### ISSUE TITLE
客户案例页面

### ISSUE THREAD

**Issue by virgoone** [Venvy-dev/demand#729]
新增一个客户案例页面

**Comment by WalterGuo** [comment]
[测试地址](http://front.test.videojj.com:10081/customer)

**Comment by lihaiye** [comment]
测试反馈：
1、顶部三个应用案例页，都是爱奇艺的同样的内容
2、顶部有多个案例页且没有左右翻页按钮的情况下，建议自动轮播
3、案例视频 `明星投票`，第一次打开时显示的是一张图片；第一个视频播完再点第二个视频显示黑屏

![image](https://cloud.githubusercontent.com/assets/17242849/14877181/877f1592-0d4d-11e6-9394-759a6b9e931c.png)

**Comment by virgoone** [comment]
视频随后替换，UI改完

**Comment by lihaiye** [comment]
- [ ] 案列互动：**互动卡牌**和**热点云链**对应的视频放反了
![image](https://cloud.githubusercontent.com/assets/17242849/15597207/8621358a-2400-11e6-8f42-db2c17b8026f.png)
