### ISSUE TITLE
[直播]暂停视频时会隐藏IVA编辑层

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#731]
测试环境：
>http://demo.tech.videojj.com/2016/04/08/Live-Temporary-Test/?videojjhost=test.videojj.com
Iva version：http://7xr51b.com1.z0.glb.clouddn.com/test_Mqtt_Iva.js
Iva update at: Thu Apr 14 2016 17:57:19 GMT+0800 (CST)

问题描述：
>打开直播视频，暂停
点击视频打开IVA编辑层，不显示
继续播放，显示IVA编辑层

期望结果：
>IVA编辑层不受暂停影响

**Comment by hzzhujf** [comment]
直播暂停需要隐藏所有热点和信息层，所以编辑者模式也会受到影响。
因为直播是实时打点的，编辑者需要在播放状态下打点才能保证内容相关，避免了这个问题。

**Comment by shixiaoyanjj** [comment]
- 开发确认直播打点必须在播放状态下进行，故关闭此issues
