### ISSUE TITLE
新增页面-今日数据

### ISSUE THREAD

**Issue by youqiongjoan** [Venvy-dev/demand#732]
分项目（例如：芒果TV）
分栏目（所有栏目及各栏目）；
分视频（所有视频及各视频）；
分品牌（所有品牌及各品牌）；
分热点（显性广告、红包、卡牌、投票、隐性广告）

**数据维度**
视频播放量、热点曝光量、热点点击量、信息层曝光量、外链点击量；
热点转化率=热点点击量/热点曝光量
外链点击率=外链点击量/信息层曝光量

**趋势图**
每5分钟更新，页面刷新后更新趋势图。

**今日统计报表部分**
分为显性（广告、红包、卡牌、投票）、隐性（广告）；按照最近1 小时-0点；倒序排列；

原型图：http://yx.tech.videojj.com/Lingzhi_Shishi_20160505/#p=今日统计
该页面与原来的数据统计页面，用tag方式进行切换；

@riverlight @analyst004

**Comment by shixiaoyanjj** [comment]
![image](https://cloud.githubusercontent.com/assets/16204026/15240198/80255f76-191a-11e6-950c-cf6fbb86e8fc.png)

**Comment by shixiaoyanjj** [comment]
![image](https://cloud.githubusercontent.com/assets/16204026/15239605/852516d2-1916-11e6-83a0-105ae6a8c464.png)
