### ISSUE TITLE
[点播]取消全屏后视频尺寸没有恢复

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#736]
#509
测试环境：
>http://yzbissb.top/mangguotv.html
http://7xr2th.com2.z0.glb.qiniucdn.com/mangguotv_Iva.js
Iva update at: Fri Apr 15 2016 18:00:40 GMT+0800 (CST)

问题描述：
>打开全屏后恢复窗口，视频尺寸异常

**Comment by hzzhujf** [comment]
这是这个测试页面的问题，已经找志博修复了。
