### ISSUE TITLE
数据统计页面-新增PC、Mobile、PC&Mobile不同平台数据

### ISSUE THREAD

**Issue by youqiongjoan** [Venvy-dev/demand#739]
数据统计页面-新增PC、Mobile、PC&Mobile不同平台数据
原型如下：
http://yx.tech.videojj.com/Lingzhi_data_20160415/#p=视频统计

![image](https://cloud.githubusercontent.com/assets/16954468/14596809/83763c2a-057b-11e6-8c8d-175aa9d2d92b.png)

**Comment by silentMood** [comment]
等待数据表及数据支持

**Comment by analyst004** [comment]
数据支持已完成，　请测试
