### ISSUE TITLE
PC端 混合信息层默认icon

### ISSUE THREAD

**Issue by Mancy1011** [Venvy-dev/demand#740]
> 人物、地点、商品默认icon
![31f8e2f38a0f9b3987a4eda932940deb](https://cloud.githubusercontent.com/assets/17489618/14596540/a763683a-0579-11e6-8a30-1c16705938c5.png)

麻烦老朱实现不同类型的混合信息层默认icon

**Comment by shixiaoyanjj** [comment]
**测试点：**

- 默认热点ICON及信息层ICON

>显性：热点ICON及信息层ICON正确显示对应的默认ICON
- [ ] 人物
- [ ] 地点
- [ ] 商品

>隐性：热点ICON正确显示白色小圆点，信息层ICON正确显示对应的默认ICON
- [ ] 人物
- [ ] 地点
- [ ] 商品

- 自定义热点ICON及信息层ICON

>显性：热点ICON及信息层ICON正确显示自定义ICON
- [ ] 人物
- [ ] 地点
- [ ] 商品

>隐性：热点ICON正确显示白色小圆点，信息层ICON正确显示自定义ICON
- [ ] 人物
- [ ] 地点
- [ ] 商品

**Comment by hzzhujf** [comment]
未来信息层类型会很多，做默认icon不现实了。如果是线上运营的项目，广告主会给icon或者运营会根据内容给icon，只有测试才会用默认icon。默认icon意义不大，所以建议统一用广告那个。

**Comment by lihaiye** [comment]
@Mancy1011 @summernini    请小蘑菇和summer定夺~~

**Comment by summernini** [comment]
目前就按老朱说的做吧，根据实际情况也确实都用广告主的logo做icon的

**Comment by shixiaoyanjj** [comment]
##Web 

- [x] WebH5显示默认ICON显示广告

![image](https://cloud.githubusercontent.com/assets/16204026/15309885/70f965d2-1c1d-11e6-83e5-d64891e1d16a.png)

##移动IOS
- [x] 移动端显示默认ICON显示人物、地点、商品默认icon
![image](https://cloud.githubusercontent.com/assets/16204026/15310455/9c7e1900-1c22-11e6-8e8f-929585c170c6.png)
