### ISSUE TITLE
片花功能

### ISSUE THREAD

**Issue by Mancy1011** [Venvy-dev/demand#744]
> 原型地址20160427
http://yx.tech.videojj.com/Pianhua_web_20160427/%E7%89%87%E8%8A%B1%E5%8A%9F%E8%83%BD20160427.pdf

> 原型地址20160422
http://yx.tech.videojj.com/Pianhua_web_20160422/%E7%89%87%E8%8A%B1%E5%8A%9F%E8%83%BD20160422.pdf

> 原型地址20160418
http://yx.tech.videojj.com/Pianhua_web_20160418/%E7%89%87%E8%8A%B1%E5%8A%9F%E8%83%BD20160418.pdf

**Comment by Mancy1011** [comment]
@Gracebaby 需要后台配置

**Comment by summernini** [comment]
@hzzhujf 请参考最新的0422的前端原型

**Comment by Gracebaby** [comment]
wireframe(console)
URL：http://yx.tech.videojj.com/console20160425/#p=视频片花库

**Comment by hzzhujf** [comment]
@summernini   说片花功能先让flash去实现

**Comment by summernini** [comment]
H5 和 flash都要开发 @hzzhujf

**Comment by iEricKoh** [comment]
@netpi  testing 无法自动 deploy, 麻烦手动一下, thanks.

**Comment by hzzhujf** [comment]
@Gracebaby  原型里控制台资源创建的对话框，少一个“描述”的输入框，因为片花没有图片可以预览，如果同名的两个片花资源没法区分，需要加描述来区分
@iEricKoh 加一下

**Comment by hzzhujf** [comment]
@shixiaoyanjj 
H5版本提交测试
测试代码：http://7xjfim.com2.z0.glb.qiniucdn.com/pianhua_Iva.js
测试环境：test.videojj.com
测试视频（这个比较短）：http://play.videojj.com/20160303/video++灵悟_mp4/video++灵悟_1080p.mp4

**Comment by shixiaoyanjj** [comment]
视频片花库测试点

**Comment by shixiaoyanjj** [comment]
片花【H5版本】

**Comment by shixiaoyanjj** [comment]
片花【Flash 版本】

**Comment by chndyyang** [comment]
http://localhost:3000/VideoJJ.swf

**Comment by lihaiye** [comment]
控制台：添加片花资源时，没有项目栏目等选择选项，需确认下是否需要添加  @Gracebaby

**Comment by iEricKoh** [comment]
@shixiaoyanjj 

> 添加片花资源，不显示默认预览图 

不是不显示。是该 dg 没有可以显示的图片。

@Gracebaby 如果需要什么默认显示的图片，请让我知道。

**Comment by lihaiye** [comment]
FLASH版本片花问题： @Mancy1011 @chndyyang 
1、打开片花后没有`返回主视频`按钮
2、添加了外链的片花，点击片花视频未跳转外链
3、（直播）片花播放完后，点击返回原视频黑屏无法播放

**Comment by Gracebaby** [comment]
Hi @iEricKoh  

- dg中无可调用图片时，使用默认预览图：） （注：请使用之前给到你的那张默认图即可）
- 新建片花时，需要增加的项为“片花描述”及“关联项目、关联品牌、关联栏目”，详见以下图示
![qq20160506-1 2x](https://cloud.githubusercontent.com/assets/14867684/15066372/2737a3da-139b-11e6-828c-767b70e82863.png)

麻烦Eric再调整一下，还有小乌龟、小叶子跟进测试一下，谢谢：）

**Comment by iEricKoh** [comment]
@WalterGuo @netpi 请 merge 掉上面的 [PR#448](https://github.com/Venvy-dev/videojj/pull/448) 然后让这些修改上 testing, thanks.

**Comment by iEricKoh** [comment]
@hzzhujf @shixiaoyanjj @lihaiye Test上已经更新了最新片花描述还有关联项目的修改，麻烦你们测试，thanks.

**Comment by iEricKoh** [comment]
Hi All,

BTW, 新增的字段``片花描述``，

````
dg: {
  desc: {
    type: String
  }
}
````
