### ISSUE TITLE
http://videojj.com/admin/#/projects 页面增加「域名」列

### ISSUE THREAD

**Issue by summernini** [Venvy-dev/demand#754]
![3 pic_hd](https://cloud.githubusercontent.com/assets/17739064/14636210/b3ab2e64-065c-11e6-84ad-b21b38b425cc.jpg)

1、在项目名后面增加一列「域名」
2、增加权限，即销售帐号登陆页面只可以看到project页面，其他页面隐藏。

优先度高，麻烦老毕今明两天搞定，谢谢啦。

**Comment by bpceee** [comment]
首先，域名是啥？我拿不到该项目域名的。
其次，销售账号是指啥？
@summernini

**Comment by summernini** [comment]
1、域名用带*号的白皮书即可
2、videoplusplus@163.com 麻烦把这个帐号添加可查看此页面的权限

**Comment by bpceee** [comment]
@netpi 把 videoplusplus@163.com 这个账号的role改成sales

**Comment by netpi** [comment]
@summernini @bpceee 加好了
