### ISSUE TITLE
投票时没有播放动效

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#762]
测试环境：
>http://demo.tech.videojj.com/2016/03/14/Test-Live-Page/?videojjhost=test.videojj.com
Iva version：http://7xjfim.com2.z0.glb.qiniucdn.com/test_Iva.js
Iva update at: Thu Apr 21 2016 10:40:37 GMT+0800 (CST)

问题描述：

- [x] 直播投票侧滑信息层进行投票时，投票没有播放动效、不显示皇冠和选项字色

>![image](https://cloud.githubusercontent.com/assets/16204026/14699878/5b3b2edc-07ce-11e6-84e2-e3903af2a2d2.png)

**Comment by shixiaoyanjj** [comment]
点播下拉栏投票时没有播放动效
>![image](https://cloud.githubusercontent.com/assets/16204026/14814414/bbfa4498-0bd8-11e6-9496-1ab0e6bdd7fe.png)

**Comment by lihaiye** [comment]
Iva version：http://7xjfim.com2.z0.glb.qiniucdn.com/test_Iva.js
Iva update at: Wed Apr 27 2016 11:59:05 GMT+0800 (CST)
验证通过
