### ISSUE TITLE
[控制台]PC端、移动端的风车ICON需要控制台可配

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#767]
- [x] IOS端的风车ICON可通过控制台配置
- [x] Android端的风车ICON可通过控制台配置

**Comment by Gracebaby** [comment]
**Dear 老毕**

## 控制台应用管理PC、iOS及Android配置都需调整一下

将“播放器设置”功能中“播放器logo”的“风车logo”选项移至“视频播放设置”的“风车功能”下方，详见下图
![qq20160422-2 2x](https://cloud.githubusercontent.com/assets/14867684/14738306/5f9bb088-08b3-11e6-882b-8cb60c2c3d42.png)

如有疑问，随时沟通：）

**Comment by bpceee** [comment]
@Gracebaby 搞定 接下来可以让各端搞了
web端@hzzhujf 手机端我也不知道@谁了

app设置多了两项：
    windmillDefault: { //windmillPic 是否用图
      type: Boolean,
      default: true
    },
    windmillPic: String,

**Comment by shixiaoyanjj** [comment]
谢谢老毕
IOS和安卓有空可以实现一下
@Zard1096 @androidlgf

**Comment by Gracebaby** [comment]
@bpceee  多谢老毕

**Comment by shixiaoyanjj** [comment]
**控制台**
- [ ] 开启风车功能，显示风车LOGO配置
- [ ] 关闭风车功能，隐藏风车LOGO配置 
- [ ] 切换默认LOGO，应用管理所有应用自动同步LOGO配置
- [ ] 上传自定义LOGO，应用管理所有应用自动同步LOGO配置

**IOS**

- [ ] 关闭风车功能，不显示风车LOGO
- [ ] 切换风车默认LOGO，播放视频正确显示默认LOGO
- [ ] 上传风车自定义LOGO，播放视频正确显示自定义LOGO

**Comment by lihaiye** [comment]
Android：

- [ ]  关闭风车功能，不显示风车LOGO
- [ ]  切换风车默认LOGO，播放视频正确显示默认LOGO
- [ ]  上传风车自定义LOGO，播放视频正确显示自定义LOGO

**Comment by lihaiye** [comment]
@Gracebaby   麻烦确认下风车默认LOGO图

**Comment by Gracebaby** [comment]
@bpceee  
相关问题：默认风车需要预览，因此请将控制台应用管理中的播放器设置预览功能修复，谢谢：） #818

**Comment by bpceee** [comment]
@hzzhujf 
logo
bigLogo
windLogo 
不存在 或者 ===""  空字符串时 表示默认

**Comment by hzzhujf** [comment]
之前logo是直接访问
http://videojj.com/api/apps/logo?appkey=base64(appkey)
的方式获取logo的
这样做的目的是可以同步
所以如果是同样的实现方式，这3个logo的默认值应该设置在后端。

**Comment by bpceee** [comment]
@hzzhujf 
logo 沿用之前方式，
bigLogo 不存在 或者 ===""  空字符串时 表示默认
windLogo 不存在 或者 ===""  空字符串时 就不显示

**Comment by bpceee** [comment]
@hzzhujf 老朱搞一下！

**Comment by bpceee** [comment]
@chndyyang 这个你也得改吧

**Comment by chndyyang** [comment]
@bpceee Flash端没有风车的，顺带说一下，之前的灵风Flash也没有的，还是感谢老毕想着我

**Comment by lihaiye** [comment]
**Android风车问题：** @androidlgf 
1、默认风车图片未替换，还是老的图片
2、使用自定义风车图片时，仍然显示默认图片

**Comment by lihaiye** [comment]
### Android端-测试通过

- 风车ICON可通过控制台配置
