### ISSUE TITLE
云窗内嵌Html5

### ISSUE THREAD

**Issue by Mancy1011** [Venvy-dev/demand#768]
适配比例
> 移动端点播/直播：200*375

> PC端点播/直播：600*300

**Comment by Gracebaby** [comment]
wireframe(console)
URL ：http://yx.tech.videojj.com/console20160425/#p=内嵌页面库

**Comment by summernini** [comment]
@iEricKoh 待DSP广告投放做完后开工这个需求，谢谢。

**Comment by summernini** [comment]
@Mancy1011 PC点播和直播的适配比例应该是不一样的吧？请修改下

**Comment by iEricKoh** [comment]
@Gracebaby 权重值除了为数字以外，有其他限制吗？比如 range,  0 ~ 9 或者 0 ~ 99 之类的 ?

![default](https://cloud.githubusercontent.com/assets/8081074/15038549/4102d6b4-12d7-11e6-80a5-252d11c89b0a.png)

**Comment by Gracebaby** [comment]
Hi  @iEricKoh  

range 设定在 0 - 100

**Comment by iEricKoh** [comment]
@Gracebaby 内嵌页面创建之后也需要添加默认的图片吗？

**Comment by Gracebaby** [comment]
@iEricKoh  内嵌页面库管理的列表缩略图，也请使用之前给到的默认图，谢谢：）

**Comment by summernini** [comment]
@Damonyg @Zard1096 @hzzhujf 麻烦开发前端的同事注意接受Eric的信息完善前端展现的内容哦~本周五需要测试通过哒，辛苦大家~

**Comment by iEricKoh** [comment]
Hey @lihaiye @shixiaoyanjj, 你们已经可以访问[这边](http://test.videojj.com/console/resource/inlines)测试该功能了。

**Comment by lihaiye** [comment]
@iEricKoh 

权重填写时提示信息需改为：**仅允许1-100**，并不包括0

![image](https://cloud.githubusercontent.com/assets/17242849/15168712/7928b8ea-1766-11e6-9333-4b40548d6cb8.png)

**Comment by iEricKoh** [comment]
@lihaiye okay. 目前UI上的东西有一部分我还在调整，我会包含修改上面你提到的问题。

所以请再跟我确认一下正确的区间，关于权重。正确的应该是下面的哪一个？按顺序1，2，3，4.

(0 ~ 100)
[0 ～ 100]
[0 ~ 100)
(0 ~ 100]

**Comment by iEricKoh** [comment]
@lihaiye Oh...Sorry...我明白你的意思了。只是修改一下**提醒消息**，我明白了。

**Comment by lihaiye** [comment]
@iEricKoh  是的， (0 ~ 100]这个是对的，另外我上个描述更新一下，权重输入还需要限制一下包含小数点的数字，只允许输入整数，谢谢。

**Comment by Gracebaby** [comment]
Hello @iEricKoh 

又来新需求了哟！内嵌页面还要增加一个内链功能，以下为图示，详见原型
![qq20160511-3 2x](https://cloud.githubusercontent.com/assets/14867684/15172462/c5a333c2-1788-11e6-845a-da328ef36ef5.png)

**console**（URL）：http://yx.tech.videojj.com/console20160506/#p=编辑内嵌页面

说明：当新建完一个内嵌页面资源后，该资源自动生成一项“内链ID”；点击列表中缩略图进入编辑，即可查看到该项（注：此项可与云图关联使用）

如有疑问，再交流：） 麻烦小叶子 @lihaiye  小乌龟 @shixiaoyanjj  技术实现后，再跟进测一下 ：）

**Comment by iEricKoh** [comment]
@Gracebaby Sorry. 除了上面提到的新增修改以外(新增一个内链ID)，我看到还多了一个**适用平台**的东西，这个也要加吗？

> 此项可与云图关联使用
这句话是什么意思？ 自动生成一项“内链ID”，这个内链ID是一个**随机新生成的ID**，而不是一个**已经存在的云图ID吧？**

所以，新增的内链ID，在 modal 里面，只是一段 text，是可以复制，展示用。而无法修改的，对吗？

另外，每次 update 一次内嵌页面，该 ID 需要每一次也更新成一个新的ID吗？

**Comment by iEricKoh** [comment]
@Gracebaby Sorry, 你的 screenshot 里面我发现还少了**添加 URL**的 button, 是不是也要去掉它然后只允许一个**内嵌页面地址**和**权重**?
 ![qq20160511-3 2x](https://cloud.githubusercontent.com/assets/14867684/15172462/c5a333c2-1788-11e6-845a-da328ef36ef5.png)

这是现在的样子:
![screenshot_2016-05-12_11-02-54](https://cloud.githubusercontent.com/assets/8081074/15202912/1c72ebf4-1831-11e6-907b-4cc9c447c316.png)

**Comment by iEricKoh** [comment]
如果button不被删除，仍然存在的话，请让我知道新增的内链ID应该存放的位置是在哪里？可能是在下图 highlight 的地方或者是在其它地方请让我知道， thanks.

![video video _ _](https://cloud.githubusercontent.com/assets/8081074/15203085/d04ee64a-1832-11e6-8d49-f24f02a1fbd9.png)

**Comment by Gracebaby** [comment]
Hello @iEricKoh  

1.关于“适用平台”是一个新增选项，需要在创建各类资源时勾选dj能使用的平台，而无需在前台创建热点时勾选 （ 相关issue： #815  ）

2.关于内链ID的说明
（1）内链ID的使用目前与云图相关，现有自动生成内链ID项的dg类型为百科，以此为例：创建关联逻辑是当创建一个百科dg后，会自动生成一个内链ID，复制ID，可在创建云图时，粘帖使用；显示逻辑是云图跳信息层再跳外链

内链ID为自动生成，且是在创建完以后随机新生成的ID
内链ID可复制、展示，但不可修改
内链ID是指dg层面的唯一ID，仅一个，且内链ID不随内嵌页面的增减或修改而变动

3.编辑内嵌页面需有“添加URL”button，sorry 遗漏了，内链ID位置也需调整，请见以下图示
<img width="734" alt="qq20160512-1 2x" src="https://cloud.githubusercontent.com/assets/14867684/15206923/300f94fe-1855-11e6-89c2-0969175a5323.png">

如有疑问再交流哦：）  @lihaiye  @shixiaoyanjj  麻烦跟进：）

**Comment by iEricKoh** [comment]
@Gracebaby 

Okay. 
**关于内链ID：**
你知道当前每一个DG(也就是一个资源)，都会有一个DG ID吗？
如果你知道的话，可以将这个ID显示出来当成内链ID吗？
还是要再另外生成一个新的ID当成内链ID？

-----------------------------------------

**关于适用平台，跟你确认一件事情：**
就是需要3个radio button, 4个checkbox，对吗？

**Comment by Gracebaby** [comment]
Hi @iEricKoh 

1.内链ID使用的就是DG ID 
2.关于“适用平台”，Summer已指派给老毕完成 ，无需理会 ：）

**Comment by iEricKoh** [comment]
@lihaiye @shixiaoyanjj 最新的改动都在 testing 上，你们可以测试。

**Comment by iEricKoh** [comment]
@lihaiye 这个 ticket 有什么问题？已经 online 了为什么还要 reopen?

**Comment by lihaiye** [comment]
@iEricKoh  那应该是在我们还没测试完的时候帅兵给关闭了，所以重新打开的~

**Comment by summernini** [comment]
@lihaiye 在846中跟进的话 此票关闭了
