### ISSUE TITLE
[点播]卡牌热点贴边打点时未完整显示热点图

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#778]
问题描述：
![image](https://cloud.githubusercontent.com/assets/16204026/14811419/9efd816a-0bca-11e6-8595-dab549447740.png)

期望结果：
>卡牌热点图完整显示

**Comment by hzzhujf** [comment]
这个我也没办法，只能靠运营控制

**Comment by lihaiye** [comment]
@summernini @Mancy1011 
需确认下这种情况是否最终通过运营来控制，3Q~

**Comment by summernini** [comment]
目前也只能这样了T T
