### ISSUE TITLE
[灵眸]APPKey错误提示改为显示中文

### ISSUE THREAD

**Issue by Mancy1011** [Venvy-dev/demand#782]
其他条件填写正确的情况下：
>1、不填写APPKEY时，点开始分析提示为：**error base64 appkey :undefined**
2、输入错误的APPKEY时，点开始分析提提示为：**no power ak:NJDIqcXo**

建议将错误提示信息改为中文提示

**Comment by edward32tnt** [comment]
@Mancy1011  这个你还是问下东泽 这个改了会影响其他端吗

**Comment by edward32tnt** [comment]
还是就在前端改了吧

**Comment by lihaiye** [comment]
http://test01.videojj.com/lingmou.html  已经修改为中文提示
