### ISSUE TITLE
前端打点样式

### ISSUE THREAD

**Issue by Mancy1011** [Venvy-dev/demand#783]
> 原型地址20160512
http://yx.tech.videojj.com/Qianduandadian_web_20160512/%E5%89%8D%E7%AB%AF%E6%89%93%E7%82%B9%E6%A0%B7%E5%BC%8F20160512.pdf

-----------------

> 原型地址20160427
http://yx.tech.videojj.com/Qianduandadian_web_20160427/%E5%89%8D%E7%AB%AF%E6%89%93%E7%82%B9%E6%A0%B7%E5%BC%8F20160427.pdf

**Comment by Mancy1011** [comment]
@hzzhujf 前端样式更改需求排后，请先完成片花和内嵌Html5功能开发

**Comment by hzzhujf** [comment]
前端打点优化，我把分类重新排了一下：
广告、百科、混合人物、混合地点、混合商品归为一类--“更多”
其它不变
更新到分支：http://7xjfim.com2.z0.glb.qiniucdn.com/pianhua_Iva.js
@Mancy1011 @shixiaoyanjj

**Comment by Mancy1011** [comment]
@hzzhujf 广告、百科、混合属于常用功能，归类为“更多”显得像是附属功能了
可以将广告、百科、混合人物、混合地点、混合商品、内嵌页面、片花都归类于“信息”

**Comment by hzzhujf** [comment]
“信息”改为“云窗”

**Comment by shixiaoyanjj** [comment]
@Mancy1011 
目前前端打点样式，请确认
![image](https://cloud.githubusercontent.com/assets/16204026/15141860/cf2688f4-16d4-11e6-9178-6f7ff5347637.png)
![image](https://cloud.githubusercontent.com/assets/16204026/15142131/3b9a508c-16d6-11e6-9c8c-e16e1ce6f0e2.png)

**Comment by Mancy1011** [comment]
@shixiaoyanjj 已确认~稍后根据目前的样式更新原型

**Comment by Mancy1011** [comment]
前端打点样式已更新，增加了抽奖功能球，将片花归类于云窗

**Comment by shixiaoyanjj** [comment]
@Mancy1011 
目前前端打点样式，请确认
![image](https://cloud.githubusercontent.com/assets/16204026/15312925/36ae6d1a-1c3a-11e6-9954-e911714b1a40.png)
![image](https://cloud.githubusercontent.com/assets/16204026/15312935/468878ac-1c3a-11e6-8985-cf0d084b22cd.png)

**Comment by Mancy1011** [comment]
@shixiaoyanjj  @hzzhujf 样式已确认，没有问题~
