### ISSUE TITLE
灵眸 package.json 升级

### ISSUE THREAD

**Issue by edward32tnt** [Venvy-dev/demand#784]
将所有使用的包都升级到最新，清理不用的包。

**Comment by lihaiye** [comment]
测试点：
1、视频设置
- [ ] APPKEY输入
- [ ] 视频URL输入
- [ ] 视频时长输入
- [ ] 分析时间选择

2、关键词分析
- [ ] 过滤条件选择
- [ ] 重新识别
- [ ] 识别结果展示
- [ ] 图表展示与放大
- [ ] 关键词选择与确认

3、广告设置
- [ ] 广告资源标题搜索
- [ ] 广告资源类别与展示
- [ ] 资源筛选栏目
- [ ] 选择广告
- [ ] 广告信息设置
- [ ] 确认投放

4、自动打点
- [ ] 打点成功后前端展示
- [ ] 打点成功后热点删除
- [ ]  打点成功后返回

5、帐号切换
- [ ] 帐号切换
