### ISSUE TITLE
增加一个用户权限，仅能看到「资源审核」和「热点列表」两页内容

### ISSUE THREAD

**Issue by summernini** [Venvy-dev/demand#786]
增加一个用户权限 即：项目运营账户
这个帐号仅可以看到「资源审核」与「热点列表」页
描述写：
项目编辑员：可以在该项目的视频中创建、修改、删除热点。可以在控制台看到数据页面。
  项目运营员：可以在该项目的视频中创建、修改、删除热点。但不可以在控制台看到数据页面。
需求来源：芒果TV @SashaHu

**Comment by SashaHu** [comment]
项目编辑员：可以在该项目的视频中创建、删除热点，并且有权查看该项目下的视频数据。
项目运营员：可以在该项目的视频中创建、删除热点，但无权查看该项目下的视频数据。

**Comment by SashaHu** [comment]
项目编辑员：可以在该项目的视频中创建、删除热点，并且有权查看该项目下的视频数据。
项目运营员：可以在该项目的视频中创建、删除热点，但无权查看该项目下的视频数据。

**Comment by shixiaoyanjj** [comment]
- [ ] 项目管理帐户下新增【设置项目运营账户】`项目运营员：可以在该项目的视频中创建、修改、删除热点，但无权查看该项目下的视频数据。`
![image](https://cloud.githubusercontent.com/assets/16204026/14974482/fb38a93e-1127-11e6-905e-263b4d27be14.png)
- [ ] 项目运营账户仅可以看到「资源审核」与「热点列表」页
