### ISSUE TITLE
官网UED

### ISSUE THREAD

**Issue by virgoone** [Venvy-dev/demand#790]
UED从wix迁移到官网平台
![image](https://cloud.githubusercontent.com/assets/8540582/14912215/4823167e-0e2d-11e6-9c23-3c0dd95fe6a9.png)
[wix地址](http://ryanluanfan.wix.com/videopls)

需要迁移部分

![image](https://cloud.githubusercontent.com/assets/8540582/14912238/6e227e00-0e2d-11e6-9a71-24b015caf961.png)
IVA templates
![image](https://cloud.githubusercontent.com/assets/8540582/14912285/b73f695e-0e2d-11e6-8d06-f80aa6db6033.png)

**Comment by virgoone** [comment]
![image](https://cloud.githubusercontent.com/assets/8540582/15570492/e7060de6-2368-11e6-8189-e3c36005aab6.png)
已上线六个页面

**Comment by lihaiye** [comment]
测试地址：http://videojj.com/
测试模块：Video++应用集市

测试内容：

- 主题
- [ ] 色彩活动
- [ ] 趣味卡通
- [ ] 科技潮品
- 功能：
- [ ]  收集卡牌
- [ ] 话题投票
- [ ] 定制红包

**Comment by lihaiye** [comment]
http://videojj.com/ued/energy/   
- [ ] 第一个图，点到第五页时，点小圆点切换页面，文字信息显示重叠
![image](https://cloud.githubusercontent.com/assets/17242849/15572574/0061e160-2374-11e6-9a18-d74f725d2907.png)

**Comment by lihaiye** [comment]
http://videojj.com/ued/cartoon/  趣味卡通页面

- [ ] 趣味卡通页面的图片都没有动效，图片轮播效果以及按钮点击效果

**Comment by lihaiye** [comment]
由于该ISSUES已经上线，先关闭。
剩余的问题在对应ISSUES中跟进
