### ISSUE TITLE
[点播]芒果前帖广告静音按钮无法点击

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#794]
测试环境：
>天天向上
http://www.mgtv.com/v/1/18/f/3126057.html
我是歌手第四季
http://www.mgtv.com/v/1/290525/f/3127163.html
妈妈是超人
http://www.mgtv.com/v/1/291337/f/3132942.html

问题描述：
>有互动层的视频前贴广告静音按钮无法点击
![qq 20160429213341](https://cloud.githubusercontent.com/assets/16204026/14917885/c6edada4-0e53-11e6-9cc4-c112b0898025.jpg)

期望结果：
>尝试了没有互动层的芒果电视剧，前贴广告静音按钮可以点击 
奇妙的时光之旅 第3集
http://www.mgtv.com/v/2/292465/f/3134671.html
![qq 20160429213829](https://cloud.githubusercontent.com/assets/16204026/14917771/397ee6f4-0e53-11e6-85ce-35500ff1d5fd.jpg)

**Comment by nekronhuang** [comment]
我先直接修改压缩文件，紧急修复。下次更新的时候更新下player代码即可
