### ISSUE TITLE
[直播]控制台热点列表相关问题&建议

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#796]
@Gracebaby 

> - [x] 后台删除直播的热点（广告，投票，红包）显示已下线，但前端未删除，应立即删除
> - [ ] 直播的热点（广告，投票，红包）持续时间结束，仍显示已上线状态，应显示已下线 #830

##  

To do #833
- [ ] 定时红包需要增加未上线状态
- [ ] 应显示定时红包和即时红包的开始时间（绝对时间）
- [ ] 定时红包的开始时间应可修改（绝对时间）
- [ ] 定时红包和即时红包的持续时间应可修改（绝对时间）

这个bug只负责第二条：
 "后台删除直播的热点（广告，投票，红包）显示已下线，但前端未删除，应立即删除",
其它请另外开！！

**Comment by bpceee** [comment]
直播的热点（广告，投票，红包）持续时间结束，仍显示已上线状态，应显示已下线
@netpi

**Comment by bpceee** [comment]
这个bug只负责第二条  "后台删除直播的热点（广告，投票，红包）显示已下线，但前端未删除，应立即删除",  其它请另外开

**Comment by shixiaoyanjj** [comment]
> 后台删除直播的热点（广告，投票，红包，百科，云窗）显示已下线，前端立即删除热点
- [x] PC
- [x] IOS
- [x] Android
