### ISSUE TITLE
数据统计-信息层曝光数较多

### ISSUE THREAD

**Issue by youqiongjoan** [Venvy-dev/demand#797]
麻烦查看一下-新蓝网-奔跑吧兄弟第四季-第3期，有没有信息层曝光异常的情况。

http://tv.cztv.com/vplay/174103.html

**Comment by shixiaoyanjj** [comment]
测试环境：
>http://tv.cztv.com/vplay/174103.html
http://7xjfim.com2.z0.glb.qiniucdn.com/xinlan_Iva.js
Iva update at: Wed Mar 30 2016 11:58:59 GMT+0800 (CST)
信息层曝光测试结果：
>
- [x] 点击广告热点，信息层clickTag接口统计正常
- [x] 点击混合人物热点，信息层clickTag接口统计正常
- [x] 点击混合地点热点，信息层clickTag接口统计正常
- [x] 点击卡牌热点，clickTag接口统计正常
- [x] hover投票banner，clickTag接口统计正常

请何大师帮忙分析数据是否有刷接口的现象 @riverlight

**Comment by youqiongjoan** [comment]
何大师，麻烦排查以下三个新蓝网的数据：
videoid：5711111e9ab95e3c0042adf6；
571a4b97dc4debd9009c797b；
57238241cf2f3e6802a1831e

**Comment by youqiongjoan** [comment]
没有发现异常
