### ISSUE TITLE
[控制台]数据统计页面：选择品牌列表内容与该项目关联品牌不一致

### ISSUE THREAD

**Issue by lihaiye** [Venvy-dev/demand#798]
问题描述：
>控制台：数据统计页面
选择品牌列表中，显示的是所有项目下的所有品牌（有些品牌在该项目下并不存在）

期望表现：
>选择品牌列表 只显示 当前项目关联品牌

![1](https://cloud.githubusercontent.com/assets/17242849/15005931/55926f34-11fd-11e6-97e3-a17f8d8c0fcc.png)

![2-](https://cloud.githubusercontent.com/assets/17242849/15006075/5e42d90a-11ff-11e6-98bd-22a3912c4780.png)

**Comment by shixiaoyanjj** [comment]
#821 重复提交，关闭此bug
