### ISSUE TITLE
[灵眸]打开切换帐号页面，点击当前帐号及返回按钮都会跳转至主页并退出当前帐号

### ISSUE THREAD

**Issue by lihaiye** [Venvy-dev/demand#799]
#549   @Mancy1011 
测试地址：
>http://test01.videojj.com/lingmou.html

问题描述：
>登陆 灵眸帐号后，点击灵眸界面右上方的`帐号切换`按钮打开切换帐号页面
点击：当前帐号栏 以及 返回按钮，都会跳转至官网登陆界面并且退出登陆

期望表现：
>1、当前帐号一栏显示，建议只做展示，不做点击跳转
2、点击”返回“，建议返回至 灵眸视频分析界面

![image](https://cloud.githubusercontent.com/assets/17242849/15010378/4a5767ac-121e-11e6-8fd4-5bfd9de883ac.png)

**Comment by Mancy1011** [comment]
切换账号界面原型如下，当前账号区域无点击效果
<img width="244" alt="2016-05-04 6 05 42" src="https://cloud.githubusercontent.com/assets/17489618/15011158/d9e1600e-1222-11e6-85ac-ff31f8efa35e.png">
点击返回按钮，返回之前的界面

**Comment by Mancy1011** [comment]
@edward32tnt 我想问一下，如果用户在关键词分析、广告设置或者自动打点界面切换账号，切换成功之后是返回之前的界面还是统一返回视频设置界面，对appkey的设置是否有影响？

**Comment by edward32tnt** [comment]
@Mancy1011 啥叫对appkey设置有影响 

@lihaiye 目前这里登陆页面有个bug 要问问帅兵和郑宇

**Comment by Mancy1011** [comment]
@edward32tnt 无论在哪个界面切换账号都是返回视频设置界面吗？如果是的话就没有问题了

**Comment by edward32tnt** [comment]
是的 

@Mancy1011

**Comment by lihaiye** [comment]
http://test01.videojj.com/lingmou.html测试通过 
点击返回，返回至视频设置界面
