### ISSUE TITLE
[灵眸]在切换或登陆帐号时，建议跳转至帐号登陆界面

### ISSUE THREAD

**Issue by lihaiye** [Venvy-dev/demand#800]
#549  @Mancy1011 
测试地址：
>http://test01.videojj.com/lingmou.html

问题描述：

> 在灵眸界面，点击`登陆Videojj帐号`或者`切换登陆帐号`时，
会先跳至登陆界面：http://videojj.com/account/login/?next=videopls.com 停留一瞬间，
再返回至主页：http://videojj.com/
这时候又需要再次点开登陆界面进行操作，比较繁琐

建议：
>在登陆帐号或切换帐号时，直接跳转至帐号登陆界面

![image](https://cloud.githubusercontent.com/assets/17242849/15010513/ebf9debe-121e-11e6-971c-77610d4fed05.png)

![image](https://cloud.githubusercontent.com/assets/17242849/15010533/0bf68546-121f-11e6-8590-4ce0a87d9693.png)

**Comment by Mancy1011** [comment]
同意，点击登陆账号或切换账号按钮，跳转至登陆界面http://videojj.com/account/login/?next=videopls.com

**Comment by edward32tnt** [comment]
振宇帅兵在这里都有可能出现bug，等他们这里都修复了就好了

@Mancy1011 @lihaiye

**Comment by lihaiye** [comment]
http://test01.videojj.com/lingmou.html
测试登陆及切换帐号跳转正常
