### ISSUE TITLE
谢哥对接百度人脸接口后续调查

### ISSUE THREAD

**Issue by edward32tnt** [Venvy-dev/demand#801]
谢哥对接百度人脸接口后续调查

对接海纳版人脸识别接口

**Comment by edward32tnt** [comment]
测试地址 test01.videojj.com

**Comment by lihaiye** [comment]
视频内场景识别，有好多重复的内容，并且识别准确率很低

![image](https://cloud.githubusercontent.com/assets/17242849/15318445/a53f1db0-1c58-11e6-9314-2594351ad3de.png)

**Comment by lihaiye** [comment]
识别视频：http://7xi4ig.com2.z0.glb.qiniucdn.com/vdemo5.mp4
算法2的识别一直处于loading中，未识别出结果
![image](https://cloud.githubusercontent.com/assets/17242849/15318666/ac3053f4-1c59-11e6-855a-126254e45c7a.png)

**Comment by lihaiye** [comment]
**视频内人物识别**，有许多与识别结果不符的：
![image](https://cloud.githubusercontent.com/assets/17242849/15319570/117a1ce6-1c5e-11e6-9fbe-ea09e7b83a9b.png)

**Comment by edward32tnt** [comment]
@lihaiye 貌似这些需要永军一起看看

**Comment by lihaiye** [comment]
和勇军确认目前已完成的只有人脸识别部分，其他识别内容还待完善
