### ISSUE TITLE
[官网]灵悦界面，下方互动介绍展示了两次

### ISSUE THREAD

**Issue by lihaiye** [Venvy-dev/demand#812]
测试地址：
>http://videojj.com/player/

问题描述：
>灵悦界面下方，`全新互动形态 革新视频营销`内容展示部分 出现了两次

**Comment by WalterGuo** [comment]
[测试地址](http://front.test.videojj.com:10081/player/)
已修复

**Comment by lihaiye** [comment]
http://front.test.videojj.com:10081/player/

**Comment by lihaiye** [comment]
http://videojj.com/player/
测试通过
