### ISSUE TITLE
视频内热点列表中显示时长请调用轨迹页面中的真实时长

### ISSUE THREAD

**Issue by summernini** [Venvy-dev/demand#817]
页面：视频管理 - 视频内热点列表 子页面
现状：显示时长 显示的是打点时设置的时长
需求：现在需要调用轨迹页面中的实际热点时长

**Comment by hzzhujf** [comment]
已经提PR了，等测试环境上线

**Comment by netpi** [comment]
@hzzhujf  817可提pr到master
