### ISSUE TITLE
[控制台]应用管理页面播放器设置中无法预览设置效果

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#818]
问题描述：
>效果预览显示优酷播放器，未加载video++播放器，无法预览效果
![image](https://cloud.githubusercontent.com/assets/16204026/15103426/d94eb286-15dd-11e6-94e3-24a2c33369c5.png)

**Comment by bpceee** [comment]
这个是解析服务器的问题，这个视频是youku上的，建议改成cdn上的
所以需要设计部搞个小一点的视频，放到cdn上（我说过很多次了啊，找圆圆）

**Comment by Gracebaby** [comment]
示例视频地址
http://vpls.oss-cn-beijing.aliyuncs.com/page/index/first/%E8%B4%AD%E7%89%A9.mp4

@bpceee  请尽快优化 ：）

**Comment by bpceee** [comment]
@Gracebaby 老朱说url不要中文

**Comment by shixiaoyanjj** [comment]
- [ ] 风车的默认ICON不正确

![image](https://cloud.githubusercontent.com/assets/16204026/15773573/37d13eac-29aa-11e6-8046-36550986ef4d.png)

期望结果：
![w1](https://cloud.githubusercontent.com/assets/16204026/15773624/909a794a-29aa-11e6-8873-79fc9f097885.png)

**Comment by shixiaoyanjj** [comment]
- [ ] 大LOGO没有默认ICON ，有疑问请联系@Gracebaby 

期望结果：
取消大LOGO的默认ICON设置，保留上传ICON功能
![image](https://cloud.githubusercontent.com/assets/16204026/15774121/4de529f8-29ad-11e6-9f22-2c8187d17f2b.png)

**Comment by shixiaoyanjj** [comment]
- [ ] 上传自定义小LOGO未即时显示预览效果，需要保存

期望结果：
即时显示预览效果

![image](https://cloud.githubusercontent.com/assets/16204026/15774232/dfac2062-29ad-11e6-86a8-87c50a572be7.png)

**Comment by shixiaoyanjj** [comment]
- [ ] 播放器皮肤切换选项无效 @Gracebaby 

![image](https://cloud.githubusercontent.com/assets/16204026/15774325/5951c2b4-29ae-11e6-8da2-b986a03a3810.png)

**Comment by bpceee** [comment]
该issue只解决无法预览问题
预览出现的问题请另外开issue

PS: 换皮肤没问题的，仔细看。
@hzzhujf 风车默认图标换下？
