### ISSUE TITLE
数据统计-上面总计部分与下面详细数据-不一致

### ISSUE THREAD

**Issue by youqiongjoan** [Venvy-dev/demand#819]
据莉敏反馈，乐视-《全员加速中2》，这个栏目下面一共有2个视频都是5月8日下午15：00上线的；这个上下数据不匹配；

有大量未知数据，请排查原因

**Comment by shixiaoyanjj** [comment]
![image](https://cloud.githubusercontent.com/assets/16204026/15143634/4c3cbe64-16dd-11e6-9778-0fb63d100b73.png)

新增未知筛选项，确保数据总和可对应
