### ISSUE TITLE
数据统计-选择品牌列表中出现其他项目的品牌列表

### ISSUE THREAD

**Issue by youqiongjoan** [Venvy-dev/demand#821]
例如：在芒果TV项目下，存在乐视项目的品牌，如下图：
![image](https://cloud.githubusercontent.com/assets/16954468/15109432/ed87ef76-160d-11e6-9603-d8a1a7d1666d.png)

![image](https://cloud.githubusercontent.com/assets/16954468/15109472/223f036c-160e-11e6-942d-28efc42c88c4.png)
与芒果TV-项目设置中的不一致

@Gracebaby

**Comment by shixiaoyanjj** [comment]
http://test.videojj.com/，测试未通过

**Comment by lihaiye** [comment]
http://test.videojj.com/console  test环境测试通过
