### ISSUE TITLE
[控制台]test.videojj.com测试环境登录退出页面的问题

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#824]
期望结果：

- 从登录页面 http://test.videojj.com/account/login/ 登录 http://test.videojj.com/console/ 成功后
- 退出登录，应跳转http://test.videojj.com/account/login/ 页面

**Comment by Gracebaby** [comment]
@bpceee  Dear 老毕 

请完善一下，麻烦啦：）

**Comment by shixiaoyanjj** [comment]
@Gracebaby @bpceee 
- [ ] 未登录时，前往test任意页面，建议跳转http://test.videojj.com/account/login/
- [ ] 登录时，前往http://test.videojj.com/account/login/页面，建议跳转http://test.videojj.com/console/

**建议测试环境替换所有跳转http://test.videojj.com/的页面**

**Comment by bpceee** [comment]
@shixiaoyanjj 都有哪些情况呢？请列举！不然做不了。

**Comment by Gracebaby** [comment]
Hi @bpceee 

场景如下：
打开以下地址 `test.videojj.com`时，首先应判断是否登录
情况一：已登录，就跳转至 `http://test.videojj.com/console/`
情况二：未登录，就跳转至`http://test.videojj.com/account/login/` 

现输入`test.videojj.com` ，直接跳转至` 404 `页面，请优化，谢谢：）

优化后，麻烦小乌龟 @shixiaoyanjj  测试，多谢：）

**Comment by lihaiye** [comment]
测试通过，已按需求实现
