### ISSUE TITLE
控制台播放器设置上传图片添加重置功能

### ISSUE THREAD

**Issue by hzzhujf** [Venvy-dev/demand#829]
如下图
![image](https://cloud.githubusercontent.com/assets/6982728/15202627/a600c600-182e-11e6-9c7b-189711be7546.png)
小LOGO、大LOGO、风车LOGO，设置了之后，不能重置为空。
@Gracebaby  加一下重置功能
@bpceee  实现一下

**Comment by Gracebaby** [comment]
老朱 已加入了删除功能哦！ @hzzhujf  可以解决重置问题：）
