### ISSUE TITLE
[点播]投票信息层显示透明效果

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#832]
**期望结果：**

>
- [ ] 根据设计需求，点播投票信息层应全部显示不透明效果

![qq 20160419134057](https://cloud.githubusercontent.com/assets/16204026/15207143/b0352170-1856-11e6-992b-5e3552cd7f7c.jpg)

**Comment by hzzhujf** [comment]
让心荷和芒果的双瑛沟通过了，这个可以不用改
