### ISSUE TITLE
[移动端]芒果需求：百科图片滚动时，小圆点选中颜色需修改

### ISSUE THREAD

**Issue by lihaiye** [Venvy-dev/demand#838]
问题描述：
>百科图片滚动时，小圆选中颜色目前为蓝色
芒果要求更改为：白色或者是芒果主题色

![image](https://cloud.githubusercontent.com/assets/17242849/15245998/75ca8b1a-193c-11e6-8cfe-0bcfb292518a.png)

**Comment by Mancy1011** [comment]
已和CC沟通，小圆为白色带描边

**Comment by lihaiye** [comment]
@Zard1096 @Damonyg 麻烦羊羊和刚刚做修改

**Comment by shixiaoyanjj** [comment]
- [ ] IOS实现主题色
- [ ] Android实现主题色
