### ISSUE TITLE
[后台管理]资源管理-广告云窗测试

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#839]
#751[后台管理]资源管理-广告云窗

问题描述：
>配置TVC广告，不显示广告预览图
![image](https://cloud.githubusercontent.com/assets/16204026/15246052/c8c4224a-193c-11e6-8bb4-b6ec6ef9908d.png)

![image](https://cloud.githubusercontent.com/assets/16204026/15245995/71cf7e62-193c-11e6-82d9-5a8d49327ea2.png)

**测试点：**
`操作：新建广告>创建新广告`

- [x] 配置有商品图的TVC广告，显示广告预览图
- [x] 配置无商品图的TVC广告，显示广告预览图

**Comment by shixiaoyanjj** [comment]
问题描述：
>广告云窗未按新需求实现可勾选功能
![image](https://cloud.githubusercontent.com/assets/16204026/15246238/c73beee8-193d-11e6-8535-8adb0e77f042.png)

**Comment by shixiaoyanjj** [comment]
问题描述：
>选择引用广告资源关联广告后，返回上一步，选择创建新广告仍显示引用广告的窗口

重现步骤：
>1、在广告云窗库创建广告
2、选择“引用广告资源”进入下一步，关联广告后返回上一步
3、选择“创建新广告”进入下一步，**仍显示引用广告资源关联的窗口**

![image](https://cloud.githubusercontent.com/assets/16204026/15282382/85496e2c-1b75-11e6-954b-028f756b0645.png)

**Comment by iEricKoh** [comment]
> 选择引用广告资源关联广告后，返回上一步，选择创建新广告仍显示引用广告的窗口

该问题已修复

**Comment by iEricKoh** [comment]
@shixiaoyanjj 

> 选择引用广告资源关联广告后，返回上一步，选择创建新广告仍显示引用广告的窗口

该问题已修复
