### ISSUE TITLE
test环境下与正式环境-视频统计内-热点统计数据不一致

### ISSUE THREAD

**Issue by youqiongjoan** [Venvy-dev/demand#844]
![-572dffab1f639c4500e43598](https://cloud.githubusercontent.com/assets/16954468/15285176/4e2d1a0c-1b88-11e6-84ef-23f9c706e973.jpg)
![-572dffab1f639c4500e43598](https://cloud.githubusercontent.com/assets/16954468/15285174/4c2a3b4a-1b88-11e6-9e0e-b6c28fb0a612.jpg)

VideoID：572dffab1f639c4500e43598

**Comment by analyst004** [comment]
对比测试所需的URL
http://test.videojj.com/console/projects/566638eebb54b35300809730/videos/572dffab1f639c4500e43598
http://videojj.com/console/projects/566638eebb54b35300809730/videos/572dffab1f639c4500e43598
