### ISSUE TITLE
【控制台】图片上传区域需要增加删除功能；部分资源需要默认图

### ISSUE THREAD

**Issue by Gracebaby** [Venvy-dev/demand#848]
Dear 老毕 @bpceee 

控制台添加图片删除及选择默认图功能

1.【资源管理】所有资源上传图片处，加入“删除”button
2.【资源管理】中“投票云窗库”的“投票banner图”以及“红包库”的“红包热点图”，需要有默认图的勾选功能
详见以下图示
投票云窗库：
![qq20160516-1 2x](https://cloud.githubusercontent.com/assets/14867684/15289413/937c6dd0-1ba4-11e6-8efb-85eec702e29d.png)

红包库（口令红包/优惠码红包）：
![qq20160516-2 2x](https://cloud.githubusercontent.com/assets/14867684/15289447/d4a39b94-1ba4-11e6-95f4-c952a5e82f82.png)

如有疑问，随时交流哟：） 实现后，麻烦小乌龟 @shixiaoyanjj  进行测试 ：）

**Comment by shixiaoyanjj** [comment]
红包热点图未实现默认和自定义勾选功能，请完成后重新送测

**Comment by shixiaoyanjj** [comment]
![image](https://cloud.githubusercontent.com/assets/16204026/15314338/d4aa37de-1c43-11e6-9e32-2f5966522d0a.png)
@Gracebaby @bpceee 
修改删除按钮太丑，建议优化

**Comment by shixiaoyanjj** [comment]
@bpceee @Gracebaby 
测试环境中红包热点图未实现默认和自定义勾选功能，请完成后重新送测
![image](https://cloud.githubusercontent.com/assets/16204026/15383864/ec287804-1dc8-11e6-8726-a5a4fbc081d6.png)

**Comment by shixiaoyanjj** [comment]
BUG详见 #851
