### ISSUE TITLE
[点播]关闭信息层showDgTime接口统计两次

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#849]
测试环境：
>http://tv.cztv.com/vplay/155502.html
http://7xjfim.com2.z0.glb.qiniucdn.com/xinlan_Iva.js
Iva update at: Fri May 13 2016 16:57:26 GMT+0800 (CST)

问题描述：
>关闭信息层后，showDgTime接口统计两次
![image](https://cloud.githubusercontent.com/assets/16204026/15310915/9fd08df4-1c27-11e6-874e-97b1b0ebbaa4.png)

**Comment by hzzhujf** [comment]
已修复，已更新线上

**Comment by shixiaoyanjj** [comment]
Iva update at: Fri May 27 2016 11:00:08 GMT+0800 (CST)

**Comment by lihaiye** [comment]
Iva update at: Thu Jun 02 2016 15:40:50 GMT+0800 (CST)

正式环境测试通过
