### ISSUE TITLE
【资源管理】新建云图云窗“跳转外链、内链ID

### ISSUE THREAD

**Issue by Gracebaby** [Venvy-dev/demand#850]
Dear @bpceee 
### 新建/编辑云图时，请将“跳转链接（内链ID）项”设置为必填！
图示如下：
![qq20160517-6 2x](https://cloud.githubusercontent.com/assets/14867684/15313125/c5a7dc62-1c3b-11e6-8982-0ddf27fc7824.png)

谢谢：）请尽快修改哦！
实现后，麻烦小乌龟测试 @shixiaoyanjj

**Comment by Gracebaby** [comment]
## 后台资源管理各类型资源创建/编辑时，必填项说明：

### 广告云窗：
1.新建
> 无侧边栏

- [ ] 名称
- [ ] 广告贴图 或 TVC
- [ ] 广告链接地址

> 有侧边栏

- [ ] 名称
- [ ] 广告贴图 或 TVC
- [ ] 广告链接地址
- [ ] 商品图
- [ ] 标题
- [ ] 描述
- [ ] 适用平台

2.引用

- [ ] 广告资源
- [ ] 适用平台

### 云图云窗：

- [ ] 图片
- [ ] 备注
- [ ] 跳转链接/ 内链ID
- [ ] 适用平台

### 百科云窗：

- [ ] 标题
- [ ] 图片（自动获取，需选择）
- [ ] 描述（自动获取）
- [ ] 链接（自动获取）
- [ ] 跳转外链按钮文字（自动获取）
- [ ] 适用平台

### 卡牌云窗：

- [ ] 卡牌组标题
- [ ] 卡牌组描述
- [ ] 按钮标题
- [ ] 按钮URL
- [ ] 适用平台

### 投票云窗：

- [ ] 投票banner图
- [ ] 投票样式
- [ ] 投票问题
- [ ] 选项答案
- [ ] 适用平台

- **当需要加入广告后，以下项也必填**

- [ ] 广告banner图
- [ ] 外链

### 广告人物（同广告地点、广告物品）：

> 组合形式分别为（人物1/人物2、人物1+人物2、人物1/人物2+广告、人物1+人物2+广告）

人物1/人物2

- [ ] 人物图
- [ ] 人物缩略图
- [ ] 人物标题
- [ ] 人物描述
- [ ] 人物外链地址
- [ ] 适用平台

人物1+人物2
- [ ] 人物1图
- [ ] 人物1缩略图
- [ ] 人物1标题
- [ ] 人物1描述
- [ ] 人物1外链地址
- [ ] 人物2图
- [ ] 人物2缩略图
- [ ] 人物2标题
- [ ] 人物2描述
- [ ] 人物2外链地址
- [ ] 适用平台


- **当选择加入轮播广告时，以下项为必填项**

人物1/人物2+广告
- [ ] 人物图
- [ ] 人物缩略图
- [ ] 人物标题
- [ ] 人物描述
- [ ] 人物外链地址
- [ ] 广告图
- [ ] 广告缩略图
- [ ] 广告标题
- [ ] 广告描述
- [ ] 广告链接
- [ ] 适用平台

人物1+人物2+广告
- [ ] 人物图
- [ ] 人物缩略图
- [ ] 人物标题
- [ ] 人物描述
- [ ] 人物外链地址
- [ ] 广告图
- [ ] 广告缩略图
- [ ] 广告标题
- [ ] 广告描述
- [ ] 广告链接
- [ ] 适用平台
- **当选择加入浮层广告时，以下项也为必填项（注：现在此项逻辑未按原型实现，需完善）**

- [ ] 广告贴图


- **当选择引用DSP广告时，以下项也为必填项（注：现在此项逻辑未按原型实现，需完善）**

- [ ] 关联DSP广告

### 红包库（口令红包、优惠劵红包）：

> 口令红包

- [ ] 红包热点图
- [ ] 品牌lLOGO
- [ ] 红包标题（部分默认提示语）
- [ ] 红包口令
- [ ] 按钮文字（默认提示语）
- [ ] 兑换说明（默认提示语）
- [ ] 广告图
- [ ] 广告链接
- [ ] 适用平台

> 优惠劵红包

- [ ] 红包热点图
- [ ] 品牌lLOGO
- [ ] 红包顶部文本（部分默认提示语）
- [ ] 红包文本（部分默认提示语）
- [ ] 红包内容
- [ ] 序列号文件
- [ ] 按钮文字（默认提示语）
- [ ] 兑换说明
- [ ] 广告图
- [ ] 广告链接
- [ ] 红包结束语（默认提示语）
- [ ] 领取结束说明（默认提示语）
- [ ] 适用平台

### 片花

- [ ] 标题
- [ ] 片花地址
- [ ] 适用平台

### 内嵌云窗

- [ ] 标题
- [ ] 内嵌页面地址
- [ ] 权重
- [ ] 适用平台


@shixiaoyanjj  小乌龟以上是现阶段各资源必填项，请参考，有疑问随时交流：）

**Comment by bpceee** [comment]
@Gracebaby 吐血 不如把非必填的告诉我？

**Comment by Gracebaby** [comment]
@bpceee    我是给小乌龟测试用的好么 你吐什么血 喝回去 吼吼吼

**Comment by shixiaoyanjj** [comment]
@Gracebaby 按新需求再次确认后送测

**Comment by summernini** [comment]
大侠新开 此票关闭
