### ISSUE TITLE
[控制台]资源图片增加修改删除功能测试 #848

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#851]
#848

- [x] 广告云窗库：广告图
- [x] 广告云窗库：商品图
- [x] 云图云窗库：图片
- [x] 卡牌云窗库：广告图
- [x] 卡牌云窗库：卡牌图
- [x] 投票云窗库：投票banner图（自定义）
- [x] 投票云窗库：广告banner图
- [x] 混合广告库：1图
- [x] 混合广告库：1缩略图
- [x] 混合广告库：2图
- [x] 混合广告库：2缩略图
- [x] 混合广告库：广告图
- [x] 混合广告库：广告缩略图
- [x] 混合广告库：广告贴图
- [x] 红包库-优惠券：红包热点图（自定义）
- [x] 红包库-优惠券：品牌LOGO
- [x] 红包库-优惠券：广告图
- [x] 红包库-口令：红包热点图（自定义）
- [x] 红包库-口令：品牌LOGO
- [x] 红包库-口令：广告图
- [x] 热点图标库：图标

**Comment by shixiaoyanjj** [comment]
- [ ] 投票云窗库：删除投票banner图（自定义）后可保存设置
![image](https://cloud.githubusercontent.com/assets/16204026/15313403/87c15296-1c3d-11e6-9dda-d68bd2f652d9.png)

**Comment by Gracebaby** [comment]
@bpceee  

> Q1.最新需求：加入`投票按钮`文字可配置功能，默认显示“投票”，可自定义修改
> Q2.请完善输入项，字数限制提示

![qq20160520-3 2x](https://cloud.githubusercontent.com/assets/14867684/15423820/dda69d94-1eb1-11e6-92fb-e306eb1701aa.png)

实现后，请小乌龟 @shixiaoyanjj  跟进测试，多谢：）

**Comment by shixiaoyanjj** [comment]
- [ ] 红包热点图提示遮挡了默认选项

![image](https://cloud.githubusercontent.com/assets/16204026/15464653/2e63b750-2103-11e6-8e4d-621bf84d3a3e.png)

**Comment by Gracebaby** [comment]
@bpceee  

[红包库]

- 完善红包热点图未填提示“请上传红包热点图”
- 由于提示语遮挡选项，请将选项与上传图片区域，保持一定距离，确保选项可作修改（如下图）
![qq20160523-1 2x](https://cloud.githubusercontent.com/assets/14867684/15465968/d9c88f16-2109-11e6-81aa-7540a755faef.png)

**Comment by shixiaoyanjj** [comment]
![image](https://cloud.githubusercontent.com/assets/16204026/15662342/34e33cb6-2722-11e6-8e7c-16a33fbc890e.png)
优惠券红包改了，口令红包没改，测试不通过
其他都改好了，加油
