### ISSUE TITLE
广告云窗和片花增加内链ID展示

### ISSUE THREAD

**Issue by hzzhujf** [Venvy-dev/demand#855]
百科云窗有内链ID展示，如下图
![image](https://cloud.githubusercontent.com/assets/6982728/15346525/85a9578e-1ceb-11e6-8e50-279ed407363e.png)
请在广告云窗和片花也添加内链ID展示，现在有些需求需要内链到这两个云窗

**Comment by summernini** [comment]
等eric把虚拟货架后台弄好做这个

**Comment by iEricKoh** [comment]
@hzzhujf @summernini 

所以结论就是在以下*三个*资源里添加一个``内链ID``的字段是吗？ 以及该``内链ID``显示出来readonly的值就是该DG的DG ID，是吗？

1. 广告云窗库
2. 百科云窗库
3. 片花库

**Comment by hzzhujf** [comment]
@iEricKoh 对的

**Comment by hzzhujf** [comment]
@iEricKoh 
![image](https://cloud.githubusercontent.com/assets/6982728/15349418/2a143d34-1d05-11e6-8528-07708aa8ecdc.png)
在创建卡牌时，原来的“按钮URL“做成”跳转链接（或内链ID）“，支持http链接或者mongoid，如云图
![image](https://cloud.githubusercontent.com/assets/6982728/15349420/2eb09cd4-1d05-11e6-950f-05cdff75c472.png)
这个需求是这周五要上的，请在明天上线前完成。

**Comment by iEricKoh** [comment]
@hzzhujf Hey, 广告云窗库增加内链ID显示的change已经在[testing](http://test.videojj.com/console/resource/)上。

**Comment by iEricKoh** [comment]
@hzzhujf Hey, 卡牌云窗库的修改，把按钮URL改成跳转链接（或内链ID）的改动已经在[testing](http://test.videojj.com/console/resource/cards)上。

![video video _ _](https://cloud.githubusercontent.com/assets/8081074/15384089/77519748-1dca-11e6-8d44-5757da89b352.png)

**Comment by shixiaoyanjj** [comment]
控制台的资源已显示内链ID，但前端未实现，故无法测试，需完整开发后再进行送测

**Comment by hzzhujf** [comment]
前端已经实现

**Comment by shixiaoyanjj** [comment]
## PC端Html5
- [ ] 云图跳转广告-
- [x] 云图跳转百科
- [x] 云图跳转片花
- [x] 云图跳转内嵌H5

- [ ] 卡牌跳转广告
- [ ] 卡牌跳转百科
- [x] 卡牌跳转片花
- [ ] 卡牌跳转内嵌H5

**Comment by hzzhujf** [comment]
修复在http://7xjfim.com2.z0.glb.qiniucdn.com/test_Iva.js

**Comment by shixiaoyanjj** [comment]
PC端目前实现的功能已验证，未实现的功能无法测试，此issues待定
