### ISSUE TITLE
[控制台]资源库创建卡牌保存设置时提示“格式错误”

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#856]
![image](https://cloud.githubusercontent.com/assets/16204026/15347129/2a36c73c-1cf1-11e6-8ff6-1818076bec99.png)

**Comment by iEricKoh** [comment]
@shixiaoyanjj 应该是https://github.com/Venvy-dev/demand/issues/842的改动导致的。

所以除了卡牌以外，麻烦你再测试一下资源管理页面其他资源的创建是否正常。

**Comment by lihaiye** [comment]
其他资源库创建正常： @iEricKoh @shixiaoyanjj 
>广告云窗库
云图云窗库
百科云窗库
投票云窗库
广告人物库
广告地点库
广告商品库
红包库
热点标题库
片花库
内嵌云窗库
