### ISSUE TITLE
[乐视点播]打开信息层会同时展开右侧列表

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#857]
测试环境：
>http://www.le.com/ptv/vplay/25370404.html
热点时间：`00:09:35` `00:17:50`
http://js.letvcdn.com/lc07_js/201603/21/11/37/letv_Iva.js
Iva update at: Mon Mar 21 2016 10:10:28 GMT+0800 (CST)

问题描述：
>收起右侧列表后，打开热点信息层，右侧列表自动展开
![image](https://cloud.githubusercontent.com/assets/16204026/15347669/5e4ee7c0-1cf6-11e6-9c74-9261c4a320e7.png)

**Comment by hzzhujf** [comment]
即使没有互动层，在右侧栏隐藏状态下，点击播放器区域，右侧栏也会出现。
