### ISSUE TITLE
[乐视点播]打开信息层时切换视频背景模糊未清

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#858]
测试环境：
>http://www.le.com/ptv/vplay/25370404.html
热点时间：`00:09:35` `00:17:50`
http://js.letvcdn.com/lc07_js/201603/21/11/37/letv_Iva.js
Iva update at: Mon Mar 21 2016 10:10:28 GMT+0800 (CST)

问题描述：
>打开热点信息层，点击打开右侧列表任意视频，信息层关闭但背景模糊状态未清除
![image](https://cloud.githubusercontent.com/assets/16204026/15347955/d33826d0-1cf8-11e6-8c0b-123c6bd6db99.png)

**Comment by nekronhuang** [comment]
我修复了，老朱推上线以后@下测试

**Comment by hzzhujf** [comment]
线上验证，已经修复
