### ISSUE TITLE
收集卡牌出片花#855

### ISSUE THREAD

**Issue by hzzhujf** [Venvy-dev/demand#865]
收集完卡牌，点击链接，出片花。
现在卡牌资源的链接支持外链和内链。
测试代码：http://7xjfim.com2.z0.glb.qiniucdn.com/card2trailer_Iva.js
测试地址：test.videojj.com

**Comment by shixiaoyanjj** [comment]
- [ ] 卡牌展示，showtag统计正确
- [ ] 点击卡牌，clicktag统计正确
- [ ] 点击内链按钮打开片花，clicklink统计正确
- [ ] 打开片花时卡牌信息层关闭，showdgtime统计正确
- [ ] 关闭片花，showdgtime统计正确

注：卡牌跳转内链的片花不能填写外链URL
