### ISSUE TITLE
[灵眸]视频设置界面，输入一个视频地址分析时提示请填写正确的Url

### ISSUE THREAD

**Issue by lihaiye** [Venvy-dev/demand#867]
#864 
测试地址：
>http://test01.videojj.com/lingmou.html

问题描述：
>视频设置界面，输入一个（除快本视频）视频地址（http://7xr5j6.com1.z0.glb.clouddn.com/zjws-wpdwp.mp4）
点开始分析，提示：请填写正确的Url

![image](https://cloud.githubusercontent.com/assets/17242849/15417613/85e47724-1e8a-11e6-8000-f505ca43ed3e.png)

**Comment by edward32tnt** [comment]
@lihaiye 

mongotv 空间下的域名是 http://7xr9rd.dl1.z0.glb.clouddn.com/
你这个的 域名是 http://7xr5j6.com1.z0.glb.clouddn.com/
