### ISSUE TITLE
[后台]热点列表页面，可编辑热点的开始时间&出现时间为负数 #767

### ISSUE THREAD

**Issue by lihaiye** [Venvy-dev/demand#868]
测试地址：
>http://test-04.videojj.com/console/

问题描述：
>打开控制台：热点列表 页面，点击编辑按钮 打开：热点编辑页面
**开始时间**&**持续时间**，可修改为负值

![image](https://cloud.githubusercontent.com/assets/17242849/15419508/e99b4da2-1e98-11e6-9849-3c6d6c3acabe.png)

**Comment by lihaiye** [comment]
http://test.videojj.com/console/
测试结果为：
编辑热点 开始时间&持续时间时不可以输入负值，但是可以输入0

@Gracebaby 麻烦大侠确认一下，是否要限制为输入大于0的数字

**Comment by Gracebaby** [comment]
@bpceee 

- `开始时间`及`持续时间`请修改为精确到秒
- 持续时间限制为大于等于5s，当输入小于5s以下数值，显示提示“持续时间需大于等于5s，请重新输入！"

**Comment by lihaiye** [comment]
**测试结果：**

- 开始时间及持续时间请修改为精确到秒--**PASSED**

- **持续时间限制为大于等于1s--未实现**

>**热点列表页面**，编辑热点持续时间可以填0，需修改为大于等于1S
**应用管理-热点设置页面**，热点显示时间可设置为0，需要修改为大于等于1S

@bpceee 麻烦老毕修改后送测，TKS~

**Comment by lihaiye** [comment]
>**应用管理-热点设置**页面：**热点显示时间** 仍可设置为0，需要修改为 大于等于1S

![image](https://cloud.githubusercontent.com/assets/17242849/16330139/aec9bf8c-3a19-11e6-9bc5-80d766d0d53c.png)

**Comment by lihaiye** [comment]
http://test-04.videojj.com/console/  测试通过

**Comment by lihaiye** [comment]
http://dev.videojj.com/ 测试通过
