### ISSUE TITLE
七喜定制

### ISSUE THREAD

**Issue by hzzhujf** [Venvy-dev/demand#869]
定制代码：http://7xjfim.com2.z0.glb.qiniucdn.com/qixitest_Iva.js
appkey：410idWDt
video：http://play.videojj.com/20151119/yingyong_gg1_mp4/yingyong_gg1_720p.mp4?v-2
我已经建好了一个广告和一组卡牌

**Comment by shixiaoyanjj** [comment]
## 广告tag `00：25`'
 广告云窗功能逻辑正确未出现异常

- [ ] 热点曝光，showtag正确统计
- [ ] 点击热点，clicktag正确统计
- [ ] 点击外链（大图，小图，查看详情），clicklink正确统计
- [ ] 关闭信息层，showdgtime正确统计

## 卡牌tag `00：37` `00：46` `00：52`
卡牌云窗功能逻辑正确未出现异常

- [ ] 热点曝光，showtag正确统计
- [ ] 点击热点，clicktag正确统计
- [ ] 点击片花内链，clicklink正确统计
- [ ] 关闭信息层，showdgtime正确统计
- [ ] 关闭片花返回视频，showdgtime正确统计

**Comment by shixiaoyanjj** [comment]
![image](https://cloud.githubusercontent.com/assets/16204026/15570111/f46a968e-2366-11e6-96ff-6e6b6747234e.png)
关闭信息层，showdgtime统计了两次
