### ISSUE TITLE
[芒果]关闭信息层，showDgTime接口统计两次

### ISSUE THREAD

**Issue by lihaiye** [Venvy-dev/demand#871]
测试地址：
>http://www.mgtv.com/v/1/290853/f/2960626.html
Iva update at: Thu May 05 2016 12:17:54 GMT+0800 (CST)

问题描述：
>热点展示时间：00:04:38
关闭信息层时，showDgTime接口统计两次

![image](https://cloud.githubusercontent.com/assets/17242849/15459975/a15cdc9e-20dd-11e6-9412-5ed0aed48055.png)

**Comment by hzzhujf** [comment]
已经修复，等下次芒果线上更新再验证吧。更新的时候我会通知你 @lihaiye

**Comment by lihaiye** [comment]
线上环境验证通过
