### ISSUE TITLE
[控制台]广告云窗资源页面右上角没有关闭X按钮

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#872]
#751 
原型地址：
>http://yx.tech.videojj.com/guanggaoyunchuang_console20160419/#p=广告云窗库

![image](https://cloud.githubusercontent.com/assets/16204026/15462760/6aeb36c8-20f7-11e6-874c-5bec3cdc27a1.png)

**Comment by iEricKoh** [comment]
这是UI/UX不是bug...

有时间的时候我会fixes.

**Comment by iEricKoh** [comment]
related ticket -> https://github.com/Venvy-dev/demand/issues/751

**Comment by iEricKoh** [comment]
@shixiaoyanjj Hey, 请告诉我你想要在哪些阶段的 modal 添加丢失掉的关闭 icon, 当你在创建/编辑广告的时候。

一共三个地方，是需要全部都加吗还是个别地方，请告诉我， thanks.

1. 创建 - 第一步
![1](https://cloud.githubusercontent.com/assets/8081074/15562240/1d1c0bb2-2330-11e6-8614-cde27ee96195.png)

2. 创建 - 第二步
![2](https://cloud.githubusercontent.com/assets/8081074/15562239/1cf23396-2330-11e6-82a5-34e9736e58bc.png)

3. 编辑
![3](https://cloud.githubusercontent.com/assets/8081074/15562238/1cbdb56c-2330-11e6-9baa-cb532333ee87.png)

**Comment by shixiaoyanjj** [comment]
@iEricKoh 按产品需求实现，谢谢
原型地址：
>http://yx.tech.videojj.com/guanggaoyunchuang_console20160419/#p=广告云窗库

**Comment by iEricKoh** [comment]
wontfix
