### ISSUE TITLE
今日统计-新增维度“信息层互动量”

### ISSUE THREAD

**Issue by youqiongjoan** [Venvy-dev/demand#876]
原型地址：http://yx.tech.videojj.com/Lingzhi_Shishi_20160523/#p=今日统计
界面上有三处更新的地方：
1、数据总量
2、图表
3、数据明细

信息层互动量：目前统计的是信息层类型-投票的Vote的总数

@vickymin 前端有新增部分
@analyst004

**Comment by lihaiye** [comment]
test.videojj.com测试通过
