### ISSUE TITLE
视频管理-页面优化

### ISSUE THREAD

**Issue by youqiongjoan** [Venvy-dev/demand#883]
请将视频管理-详情页面，进行页面优化，如下URL
http://videojj.com/console/projects/564d93bfe2b63738009d9ea1/videos/57451e5f72dc1c9d01fd05e3

建议与数据统计页面风格一致

**Comment by lihaiye** [comment]
测试地址：http://test.videojj.com/console
视频管理子页面测试内容：

- [ ] 数据显示模块增加背景颜色
- [ ] 时间筛选调整至界面右上角，时间显示及筛选后数据显示正常

**Comment by lihaiye** [comment]
项目概览页面：
测试环境视频播放量Top10列表中有出现404的情况，需要更新到正式环境后再验证
