### ISSUE TITLE
[控制台]新建混合广告只填第一和第三个窗口的内容会提示格式错误

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#886]
测试环境：
>http://test.videojj.com/console/resource/hybridFigures

问题描述：
>添加广告人物资源
填写以下数据后保存，提示：格式错误
人物1图
人物1缩略图
人物1标题
人物1描述
人物1链接
广告图
广告缩略图
广告标题
广告描述
广告详情链接
![qq 20160525155226](https://cloud.githubusercontent.com/assets/16204026/15532136/bd9cd792-2290-11e6-863c-626e5ca1380f.png)
![qq 20160525155207](https://cloud.githubusercontent.com/assets/16204026/15532154/d5117fd6-2290-11e6-9e14-3c69eaec1707.jpg)

**Comment by bpceee** [comment]
修#842出的问题，已在842上搞定
