### ISSUE TITLE
【资源管理】投票类资源，新增“投票按钮”文本自定义功能

### ISSUE THREAD

**Issue by Gracebaby** [Venvy-dev/demand#890]
@bpceee  

> Q1.最新需求：加入`投票按钮`文字可配置功能，默认显示“投票”，可自定义修改
> Q2.请完善输入项，字数限制提示

![qq20160520-3 2x](https://cloud.githubusercontent.com/assets/14867684/15423820/dda69d94-1eb1-11e6-92fb-e306eb1701aa.png)

实现后，请小乌龟 @shixiaoyanjj  跟进测试，多谢：）

**Comment by bpceee** [comment]
@hzzhujf  如果dg里有btnTitle，那么就是自定义按钮名，没有的话还是“投票”

**Comment by shixiaoyanjj** [comment]
选项字数限制为8个字，与需求不符
![image](https://cloud.githubusercontent.com/assets/16204026/16402317/1b8dedd0-3d1e-11e6-9c0d-e990a6bbcf32.png)

**Comment by summernini** [comment]
1、需求来源不明确，本次不做修改
2、影响线上熊猫、Zelar等项目，故不做修改。

此票关闭
