### ISSUE TITLE
[点播]芒果预览小窗显示互动层信息

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#903]
测试环境：
>http://www.mgtv.com/v/1/18/f/3191252.html
时间点：`04：22`

问题描述：
>1、打开芒果视频开始播放
2、在时间点显示前下拉页面，显示芒果预览小窗
3、到展示时间时显示热点

期望结果：
>预览小窗不显示互动层

BUG截图：
![qq 20160601154148](https://cloud.githubusercontent.com/assets/16204026/15702006/13ac2064-2810-11e6-9a12-9710f2038e6a.jpg)

**Comment by hzzhujf** [comment]
更新线上了

**Comment by shixiaoyanjj** [comment]
- [ ] 广告热点
- [ ] 隐性追踪热点
- [ ] 投票banner
