### ISSUE TITLE
数据统计-今日数据-可以选择“所有栏目”&“所有视频”的数据

### ISSUE THREAD

**Issue by youqiongjoan** [Venvy-dev/demand#907]
可以选择“所有栏目”&“所有视频”下的数据
![image](https://cloud.githubusercontent.com/assets/16954468/15741626/1440d640-28ed-11e6-9f12-3fd4d39709ec.png)

@vickymin

**Comment by lihaiye** [comment]
测试地址：http://test.videojj.com/console/
测试页面：数据统计-今日统计 页面

- [ ] 栏目选择中，可选择‘所有栏目’
- [ ] 选择‘所有栏目’时，可选择‘所有视频’
- [ ] 选择‘所有栏目’+‘所有视频’，数据显示正常
- [ ] 选择‘所有栏目’+单个视频，数据显示正常

**Comment by lihaiye** [comment]
由于芒果项目视频量过大：数据统计页面读取 所有栏目+所有视频，由会导致页面崩溃
目前暂时优化为：
打开今日统计页面时，默认显示为“所有栏目’+‘所有视频’的数据，但是视频选择中不加载‘所有视频’的选项
