### ISSUE TITLE
灵眸toB 视频分析&后台

### ISSUE THREAD

**Issue by Mancy1011** [Venvy-dev/demand#909]
> 20160622 设计稿
http://yx.tech.videojj.com/LingmoutoB_videoanalytics_UI_20160622/
> 20160622 原型修改：增加卡片式列表、分析结果展示页
http://yx.tech.videojj.com/LingmoutoB_videoanalytics_web_20160622/

------------------

> 20160608 原型修改：添加视频任务，区分手动添加和批量上传
http://yx.tech.videojj.com/LingmoutoB_videoanalytics_web_20160608/#p=首页-登录账号

-----------------

> 原型地址 20160606
http://yx.tech.videojj.com/LingmoutoB_videoanalytics_web_20160606/#p=首页-登录账号

--------------------

> 原型地址 20160603
http://yx.tech.videojj.com/LingmoutoB_videoanalytics_web_20160603/#p=登陆账号

**Comment by summernini** [comment]
@virgoone

**Comment by virgoone** [comment]
测试地址：http://test01.videojj.com/lingmou/

**Comment by summernini** [comment]
以 #990 为准，此票关闭
