### ISSUE TITLE
[控制台]数据统计-今日统计界面，信息层互动量有概率不增加

### ISSUE THREAD

**Issue by lihaiye** [Venvy-dev/demand#912]
#881
测试项目：新蓝网
测试视频：http://tv.cztv.com/vplay/180375.html  【《奔跑吧兄弟》-第5期】
video ID:5735f73b81fe103e00e7e752
投票tag点时间：00:00:00、00:02:41、00:07:19、00:10:40等

问题描述：
>数据统计-今日统计页面，在线上视频投票以后，信息层互动量显示未增加

![image](https://cloud.githubusercontent.com/assets/17242849/15774784/d4f109a0-29b0-11e6-8e09-e867b6f938d7.png)

**Comment by lihaiye** [comment]
正式环境上测试该问题仍然存在

**Comment by vickymin** [comment]
该问题是由于前端track造成，待解决后，再进行测试

**Comment by lihaiye** [comment]
线上测试信息层互动量增加正常
