### ISSUE TITLE
创建一种给平台测试用的权限

### ISSUE THREAD

**Issue by summernini** [Venvy-dev/demand#914]
后台：资源管理页面仅可看到：百科，投票，卡牌，红包，混合云窗；并且项目看板可看到关联哪些项目，但无法点击进入；
前端：仅显示百科，投票，卡牌，红包，混合云窗 这五个球。

在芒果这个项目下，打点不需要审核

**Comment by bpceee** [comment]
@summernini  如何“将此帐号设置成 无需审核？”

**Comment by bpceee** [comment]
@summernini 把芒果那个项目控制台url地址告诉我一下吧

**Comment by summernini** [comment]
http://videojj.com/console/projects/566638eebb54b35300809730

**Comment by bpceee** [comment]
上线后塞条数据
db.porjectusers.insert({projectOwner: ObjectId("5665571d65259f4600b4b51c"), user: ObjectId("5755156ee9d9f0cc5dde32d7"), project:ObjectId("566638eebb54b35300809730"), role: "mongoOperator"})

**Comment by bpceee** [comment]
@hzzhujf 
getCurrentUser 接口返回 role: "mongoOperator" 则该帐号是芒果的打点帐号。。

**Comment by hzzhujf** [comment]
前端应该还有广告类型，混合类型是3种（混合人物，混合地点，混合商品）
测试代码：http://7xjfim.com2.z0.glb.qiniucdn.com/914_Iva.js
测试环境：test.videojj.com

**Comment by lihaiye** [comment]
**控制台**
测试地址：http://test.videojj.com/console/
测试帐号：791261819@qq.com 密码： mgtv2016

资源管理页面：
- [ ] 只显示：百科、投票、卡牌、红包、混合（包含广告人物、广告地点、广告物品）资源
- [ ] 百科云窗库添加资源正常
- [ ] 投票云窗库添加资源正常
- [ ] 卡牌云窗库添加资源正常
- [ ] 红包云窗库添加资源正常
- [ ] 混合云窗云窗库添加资源正常（包含广告人物、广告地点、广告物品）

项目看板：
- [ ] 正常显示关联项目
- [ ] 点击关联项目无法进入

**Comment by lihaiye** [comment]
**前端**
测试地址：http://z-tron.cn/play/page/TestPlayer.html/?videojjhost=test.videojj.com
IvaJs：http://7xjfim.com2.z0.glb.qiniucdn.com/914_Iva.js
测试帐号：791261819@qq.com 密码： mgtv2016

点播：

- [ ] 打点时仅显示：百科、投票、卡牌、红包、混合云窗（包含广告人物、广告地点、广告物品）
- [ ] 百科打点正常
- [ ] 投票打点正常
- [ ] 卡牌打点正常
- [ ] 红包打点正常
- [ ] 混合云窗打点正常（包含广告人物、广告地点、广告物品）

**问题**：

- [ ] 前端打点时显示广告资源，但需求中未包含广告资源

![image](https://cloud.githubusercontent.com/assets/17242849/15851682/63acbabe-2cd0-11e6-882c-6ce5a4b5b615.png)

**Comment by summernini** [comment]
@SashaHu 心荷那边刚收到新的客户需求是增加『广告云窗』 @bpceee 麻烦老毕添加下吧，谢谢~

**Comment by bpceee** [comment]
@summernini 这个需求项目所有的issue都是公开访问的，所以不要写帐号密码等敏感信息。。
又敏感信息就发邮件给我和相关测试人员吧

**Comment by netpi** [comment]
@bpceee 请提pr到master

**Comment by lihaiye** [comment]
### 正式环境
控制台：已实现
前端打点：暂未实现，需要等老朱更新

**Comment by lihaiye** [comment]
心荷确认：该帐号 控制台-资源管理页面，还需要显示：热点图标库 @summernini @bpceee 
麻烦老毕再加一下，辛苦了

**Comment by hzzhujf** [comment]
芒果线上更新

**Comment by lihaiye** [comment]
前端打点正式环境验证通过
Iva update at: Tue Jun 14 2016 20:42:48 GMT+0800 (CST)

**Comment by lihaiye** [comment]
控制台-正式环境
已显示：热点图标库
