### ISSUE TITLE
[芒果TV]傲游云浏览器切换成兼容模式后，不显示IVA层

### ISSUE THREAD

**Issue by lihaiye** [Venvy-dev/demand#916]
测试地址：
>http://www.mgtv.com/v/1/18/f/3235550.html
浏览器：傲游云v4.4.8.1000

问题描述：
>傲游云浏览器，切换成**兼容模式后，不显示IVA层**
切换成极速模式后，正常显示IVA层

![image](https://cloud.githubusercontent.com/assets/17242849/15820497/58a13618-2c1c-11e6-8dd0-f109221fd875.png)

**Comment by hzzhujf** [comment]
这个页面有设置如果是用IE兼容模式，会用支持的最高版本的IE内核去解析。
但是海叶的遨游用的是IE7的内核，不支持Iva。这个是浏览器的问题，暂时不知道怎么解决。
