### ISSUE TITLE
[控制台] 风车的默认ICON不正确

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#917]
- [x] 风车的默认ICON不正确

![image](https://cloud.githubusercontent.com/assets/16204026/15773573/37d13eac-29aa-11e6-8046-36550986ef4d.png)

期望结果：
![w1](https://cloud.githubusercontent.com/assets/16204026/15773624/909a794a-29aa-11e6-8873-79fc9f097885.png)

**Comment by hzzhujf** [comment]
测试代码：http://7xjfim.com2.z0.glb.qiniucdn.com/test_Iva.js
测试环境：test.videojj.com
