### ISSUE TITLE
[控制台]大LOGO没有默认ICON未取消 #767

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#918]
http://test-04.videojj.com
要测的时候告诉我，我给你切环境！-- 毕鹏程

- [x] 大LOGO没有默认ICON ，有疑问请联系@Gracebaby 

期望结果：
>取消大LOGO的默认ICON设置，保留上传ICON功能
![image](https://cloud.githubusercontent.com/assets/16204026/15774121/4de529f8-29ad-11e6-9f22-2c8187d17f2b.png)

**Comment by shixiaoyanjj** [comment]
- 添加大LOGO图片后，点击保存按钮，图片被清空

测试不通过

**Comment by lihaiye** [comment]
http://test-04.videojj.com/

测试通过

**Comment by lihaiye** [comment]
http://dev.videojj.com/   测试通过

**Comment by lihaiye** [comment]
正式环境测试通过
