### ISSUE TITLE
【控制台】资源管理中有内链ID的资源类型加入“复制ID”button（优化）

### ISSUE THREAD

**Issue by Gracebaby** [Venvy-dev/demand#921]
Hi @iEricKoh

请在`广告云窗、百科云窗、 视频片花`资源类型的**“内链ID”**选项后加入**“复制ID”button**

以下为已实现示例，同此即可：
<img width="641" alt="qq20160607-3 2x" src="https://cloud.githubusercontent.com/assets/14867684/15845974/2b2934a8-2cab-11e6-95fb-17f1a1651949.png">

麻烦小乌龟 @shixiaoyanjj   实现后跟进测试：）

**Comment by iEricKoh** [comment]
resolved.
