### ISSUE TITLE
【控制台】新增预览功能

### ISSUE THREAD

**Issue by Gracebaby** [Venvy-dev/demand#922]
Hi Eric @iEricKoh 

目前控制台主要有`资源审核`、`热点列表`、`资源管理` 3个版块需要加入预览，详见原型

原型地址：http://yx.tech.videojj.com/console20160520/#p=热点管理

如有疑问，随时沟通：） 麻烦小乌龟 @shixiaoyanjj  跟进测试

**关联** #401

**Comment by hzzhujf** [comment]
这个做到cytron里吧
