### ISSUE TITLE
【控制台】资源管理迁移至项目资源

### ISSUE THREAD

**Issue by Gracebaby** [Venvy-dev/demand#926]
测试地址：http://test-04.videojj.com/

Dear 老毕 @bpceee 

### **迁移资源涉及到的逻辑**

将`资源管理`中的资源作如下判断：

> 当该账号仅有一个项目时

- 已关联项目的资源，按所关联的项目分配；
- 未关联项目的资源，全部归于该项目中；

> 当该账号有多个项目，包括被授权的项目时

- 已关联项目的资源，按所关联的项目分配；
- 未关联项目的资源，请列出账号，由运营检查后，作关联或删除操作；

### **迁移资源涉及到的UI**

> 初始状态

- 将`资源管理`固定至侧边主导航的底部，不随导航进度条的滚动而改变

> 交互逻辑

- 点击`资源管理` ，向上滑动，展示所有资源类型，点击“返回”button，向左收起，再向下滑动，返回主导航（初始状态）
- 当进入`资源管理`后，默认打开`广告云窗`类资源，当点击“返回”button后，默认打开主导航的`项目总览`

如有疑问，随时沟通：)  完成后，请小乌龟 @shixiaoyanjj  跟进测试 么么哒

关联  #901 

PS: 热点图标也要和项目相关了

**Comment by summernini** [comment]
@hzzhujf 届时前端应该也没有「我的资源」选项了

**Comment by bpceee** [comment]
没原型，拒绝合作

**Comment by Gracebaby** [comment]
@bpceee  依然能好好合作，请呼唤我，我们f2f交流 😄 

以下为图示，仅供参考：
![image](https://cloud.githubusercontent.com/assets/14867684/16186243/fa1a7fba-36fb-11e6-9b3b-b6ea3260d430.png)

**Comment by bpceee** [comment]
@Gracebaby @summernini @shixiaoyanjj #816 上改了很多资源相关的东西，应该在这个之前上线吧？

**Comment by bpceee** [comment]
@hzzhujf 新建资源链接改成类似这样的：console/projects/55c1d80a958842b46ccee1df/resource_pictures#new

**Comment by hzzhujf** [comment]
测试代码：http://7xjfim.com2.z0.glb.qiniucdn.com/926_Iva.js
测试环境：test.videojj.com

**Comment by shixiaoyanjj** [comment]
测试代码：http://7xjfim.com2.z0.glb.qiniucdn.com/926_Iva.js
测试环境：http://test-04.videojj.com/

## 测试结果
>打开互动编辑框，点击新建资源
- [ ] 云图
- [ ] 卡牌
- [ ] 投票
- [ ] 红包
- [ ] 片花
- [ ] 广告
- [ ] 百科
- [ ] H5内嵌
- [ ] 人物
- [ ] 商品
- [ ] 地点

问题描述：
@hzzhujf 
- 点击片花的新建链接打开了新建云图页面
- 点击卡牌的新建链接打开了新建云图页面

**Comment by hzzhujf** [comment]
* 点击片花的新建链接打开了新建云图页面
* 点击卡牌的新建链接打开了新建云图页面
* 热点图标的新建链接打开了项目看板页面
修复，测试代码和测试地址不变
@shixiaoyanjj

**Comment by shixiaoyanjj** [comment]
- [ ] 前端打点页面取消「我的资源」选项

**Comment by hzzhujf** [comment]
- [ x ] 前端打点页面取消「我的资源」选项

**Comment by shixiaoyanjj** [comment]
## Html5

- [ ] 相同项目下不同帐号创建热点图标同步显示

## Flash

- [ ] 相同项目下不同帐号创建热点图标同步显示
