### ISSUE TITLE
[控制台]应用管理页面默认LOGO效果预览未刷新  #767

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#930]
http://test-04.videojj.com

测试环境：
>控制台-应用管理-设置

问题描述：
>上传自定义LOGO后切换默认LOGO，效果预览未刷新默认LOGO

![qq 20160608113008](https://cloud.githubusercontent.com/assets/16204026/15884602/518300d2-2d84-11e6-8c7e-18212a18c280.jpg)

期望结果：
>

- [x] 播放器LOGO：上传自定义LOGO后切换默认LOGO，效果预览刷新默认LOGO
- [x] 风车LOGO：上传自定义LOGO后切换默认LOGO，效果预览刷新默认LOGO

**Comment by shixiaoyanjj** [comment]
## 播放器LOGO（小LOGO）

- [ ] 上传自定义LOGO，未刷新预览效果，应即时刷新预览效果
- [ ] 上传自定义LOGO后保存，切换默认LOGO，未刷新预览效果，应即时刷新预览效果

测试未通过@bpceee @Gracebaby

**Comment by bpceee** [comment]
@shixiaoyanjj @Gracebaby 
小图标预览这个问题，这个没办法了
只能取消保存按钮，自动保存

**Comment by bpceee** [comment]
@hzzhujf 
new Iva() 没有重新加载logo
可以去 http://test-04.videojj.com 里的app setting里测下

**Comment by lihaiye** [comment]
http://test-04.videojj.com/

测试通过

**Comment by lihaiye** [comment]
http://dev.videojj.com/  测试通过

**Comment by lihaiye** [comment]
http://videojj.com/ 测试通过
