### ISSUE TITLE
优化灵知-VideoJJ前端-数据统计部分-趋势图

### ISSUE THREAD

**Issue by youqiongjoan** [Venvy-dev/demand#932]
优化“数据统计”&“今日统计”页面中，趋势图的样式：
1）从目前的一个趋势图，拆分成两个“热点转化效果分析”、“信息层转化效果分析”；
2）“热点转化效果分析”中的数据维度：视频播放量、热点曝光量、热点点击量、热点转化率
注：热点转化率=热点点击量/热点曝光量，保留两位小数；
3）“信息层转化效果分析”中的数据维度：信息层曝光量、外链点击量、外链点击率
注：外链点击率=外链点击量/信息层曝光量
4）“数据统计”中，趋势图的横坐标轴为“分天”；“今日统计”中，横坐标轴为“分小时”；
5）趋势图的左侧的刻度为各个曝光量、点击量的；右侧的刻度是转化率的；

原型地址：
http://yx.tech.videojj.com/Lingzhi_2.0_20160608/#p=基础统计

**Comment by lihaiye** [comment]
### 数据统计页面：
- [ ] 显示趋势图：热点转化效果分析、信息层转化效果分析
- [ ] “热点转化效果分析”显示数据：视频播放量、热点曝光量、热点点击量、热点转化率显示正确
- [ ] “信息层转化效果分析”显示数据：信息层曝光量、外链点击量、外链点击率显示正确
- [ ] 热点转换率=热点点击量/热点曝光量，保留两位小数，计算正确
- [ ] 外链点击率=外链点击量/信息层曝光量，计算正确
- [ ] 选择不时时间段，图表信息显示正常
- [ ] 选择不同栏目、视频及品牌数据显示正常

### 数据统计-实时数据（今日统计）页面：

- [ ] 显示趋势图：热点转化效果分析、信息层转化效果分析
- [ ] “热点转化效果分析”显示数据：视频播放量、热点曝光量、热点点击量、热点转化率显示正确
- [ ] “信息层转化效果分析”显示数据：信息层曝光量、外链点击量、外链点击率显示正确
- [ ] 选择不同栏目、视频及品牌数据显示正常

### 视频管理子页面：
- [ ] 显示趋势图：热点转化效果分析、信息层转化效果分析
- [ ] 选择不时时间段，图表信息显示正常

**Comment by lihaiye** [comment]
问题：
- [ ] 数据统计-实时数据页面，选择指定栏目+指定视频时，图表中不显示热点转化率和外链点击率
![image](https://cloud.githubusercontent.com/assets/17242849/16076811/da1a72a6-3327-11e6-9650-fa00f9b48450.png)

**Comment by vickymin** [comment]
修复了两个问题，麻烦重新测试
- 由于缓存原因，切换不同项目的实时数据，数据会产生错误
- 风行网无法获取数据

**Comment by lihaiye** [comment]
**测试结果：**
1、切换不同项目的实时数据，数据显示正常-PASSED
2、由于风行网管理员帐号已更换，test环境上未更新最新的风行网数据，需要正式环境才能验证
