### ISSUE TITLE
优化灵知-VideoJJ前端-今日统计-漏斗图

### ISSUE THREAD

**Issue by youqiongjoan** [Venvy-dev/demand#933]
为了增强可视化效果，对“今日统计”页面进行优化：
![image](https://cloud.githubusercontent.com/assets/16954468/15885885/8f580f62-2d8c-11e6-8b23-521d4d5efad0.png)

**Comment by vickymin** [comment]
由于页面展示原因，该issue会与issue-936一同处理

**Comment by vickymin** [comment]
原型：http://yx.tech.videojj.com/Lingzhi_2.0_20160608/#p=基础统计
