### ISSUE TITLE
 优化灵知-VideoJJ前端-今日统计-圆环图

### ISSUE THREAD

**Issue by youqiongjoan** [Venvy-dev/demand#936]
为了展现出，每种信息层类型的热点曝光量、热点点击量、外链点击量的占比，今日统计增加“圆环图”：

1）不同信息层类型用不同色块表示；
2）外环：热点曝光量%；中环：热点点击量%；内环：外链点击量%；
3）当鼠标hover到某个色块时，会同时显示同一类型的，三个数据；

**Comment by vickymin** [comment]
由于页面展示原因，该issue会与issue-933一同处理

**Comment by vickymin** [comment]
原型：http://yx.tech.videojj.com/Lingzhi_2.0_20160608/#p=基础统计
