### ISSUE TITLE
[控制台]上传自定义图片后点击自定义选项，图片被清空 #767

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#937]
http://test-04.videojj.com/

问题描述：
>上传自定义图片后，再次点击自定义选项，图片被清空

期望结果：
>自定义图片上传后，未点击删除，不清空上传图片

## 投票
![image](https://cloud.githubusercontent.com/assets/16204026/15891935/88c5271c-2da9-11e6-82c0-29b1d9a0ed57.png)

## 红包
![image](https://cloud.githubusercontent.com/assets/16204026/15891959/9da7f308-2da9-11e6-90b3-2791197c433b.png)

**Comment by lihaiye** [comment]
### 测试结果：
>**红包**：上传自定义图片后，再次点击自定义选项，图片被清空

测试未通过

**Comment by shixiaoyanjj** [comment]
http://test-04.videojj.com/测试通过

**Comment by lihaiye** [comment]
http://dev.videojj.com/ 测试通过

**Comment by lihaiye** [comment]
正式环境测试通过
