### ISSUE TITLE
[风行]热点展示暂停视频后拖动视频进度，热点不再显示

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#947]
测试环境：
>http://www.fun.tv/vplay/g-211936.v-717118/
时间点：07：00

问题描述：
>热点展示时，暂停
拖动视频进度
热点不再显示

**Comment by williamling** [comment]
@shixiaoyanjj  风行技术没有给我消息 我已经和他说了 等他们下次更新
