### ISSUE TITLE
[官网]FAQ页面改版

### ISSUE THREAD

**Issue by virgoone** [Venvy-dev/demand#954]
![image](https://cloud.githubusercontent.com/assets/8540582/16067584/88bea0ee-32f0-11e6-812d-45f19a2287c1.png)

**Comment by virgoone** [comment]
@794485409 @shixiaoyanjj 测试地址：[http://front.test.videojj.com:10081/faq](http://front.test.videojj.com:10081/faq)

**Comment by shixiaoyanjj** [comment]
测试通过

**Comment by lihaiye** [comment]
http://videojj.com/faq/已上线，测试通过
