### ISSUE TITLE
[控制台]视频内热点列表的信息层类型不显示投票和红包类型

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#955]
测试环境：
>http://test.videojj.com/

问题如图
![image](https://cloud.githubusercontent.com/assets/16204026/16075391/618cce5c-3321-11e6-979e-0fddcadbeccb.png)

**Comment by bpceee** [comment]
有啊

**Comment by lihaiye** [comment]
http://dev.videojj.com/ 测试通过

**Comment by lihaiye** [comment]
http://videojj.com/   测试通过
