### ISSUE TITLE
[后台-数据]数据统计页面，切换统计时间段后图表显示异常

### ISSUE THREAD

**Issue by lihaiye** [Venvy-dev/demand#956]
问题描述：
>数据统计页面：
先选择显示7天的数据，然后切换成30天，将趁势图表中下方的拖动条拖至7天以前的范围；
再选择7天，图表会显示为空
（点击图表下方后会恢复正常显示）

期望表现：
>切换至不同的时间段数据时，显示对应时间段默认的图表

![image](https://cloud.githubusercontent.com/assets/17242849/16076939/6e65c87a-3328-11e6-8146-65e67e3a2f02.png)

**Comment by vickymin** [comment]
应该是highcharts的问题，待解决

**Comment by lihaiye** [comment]
http://test-07.videojj.com/  测试通过

**Comment by lihaiye** [comment]
http://dev.videojj.com/console 测试通过
