### ISSUE TITLE
信息层数据统计 － 信息层下拉列表中包含了不属于本项目的信息层

### ISSUE THREAD

**Issue by analyst004** [Venvy-dev/demand#960]
![image](https://cloud.githubusercontent.com/assets/2767633/16104064/7361df3e-33b0-11e6-94ac-c7e94eabe365.png)

**Comment by lihaiye** [comment]
**测试结果：**
资源未关联项目时，不在任何项目信息层列表中显示
资源关联对应项目时，只在对应项目下显示，其他项目下不显示

**Comment by lihaiye** [comment]
http://videojj.com/ 测试通过
