### ISSUE TITLE
[后台-数据]实时统计界面选择指定栏目时数据不会变更，建议优化

### ISSUE THREAD

**Issue by lihaiye** [Venvy-dev/demand#964]
问题描述：
>数据统计-实时数据页面：
打开时默认显示为：所有栏目+所有视频的数据内容
选择指定栏目后，未选择视频的情况下，数据信息不会变更【由于实时统计 缺少 指定栏目下所有视频 数据统计】

建议：
>增加：指定栏目下所有视频的实时数据
在实时数据页面勾面指定栏目后，下方数据同时变更

![image](https://cloud.githubusercontent.com/assets/17242849/16110532/d32bbd92-33e0-11e6-91b0-33470647a2b6.png)

**Comment by vickymin** [comment]
该问题已有issue: Venvy-dev/demand#951
