### ISSUE TITLE
[官网]广告主页面

### ISSUE THREAD

**Issue by virgoone** [Venvy-dev/demand#969]
![image](https://cloud.githubusercontent.com/assets/8540582/16143105/2f2688ae-349d-11e6-958b-acbcef7a0a3c.png)
![image](https://cloud.githubusercontent.com/assets/8540582/16143112/33ef6144-349d-11e6-8156-3af2e72142f3.png)

**Comment by virgoone** [comment]
[测试地址](http://front.test.videojj.com:10081/vdap/)

**Comment by lihaiye** [comment]
测试地址打开的是灵知数据页面，需确认测试地址 @virgoone

**Comment by virgoone** [comment]
@lihaiye 已更新

**Comment by lihaiye** [comment]
### 问题汇总：

- [ ] 1、优秀案例中，互动A/B剧、趣味卡牌、个性海报、创意滚动的DEMO视频与标题不符

![image](https://cloud.githubusercontent.com/assets/17242849/16640692/d5d08878-442c-11e6-84d4-fa594c48db74.png)
- [ ] 2、 行业案例列表中，新蓝网和Zealer所对应的广告品牌有误，都显示为康师傅

![image](https://cloud.githubusercontent.com/assets/17242849/16640773/7ddd3020-442d-11e6-9fe5-fccd31bed7fe.png)
- [ ] 3、顶部的下载按钮点击无效

![image](https://cloud.githubusercontent.com/assets/17242849/16640825/f652b250-442d-11e6-9b64-68fa6114a465.png)
- [ ] 4、内容介绍中，示例图都未包含热点和信息层的展示
- [ ] 5、**话题投票**内容，示例图片使用的是品牌广告语示例图

![image](https://cloud.githubusercontent.com/assets/17242849/16640931/b122306a-442e-11e6-9f70-e982134bd9bf.png)
- [ ] 6、广告页面曝光，所以类型百分比都显示为：56%

![image](https://cloud.githubusercontent.com/assets/17242849/16640987/ffe38f6e-442e-11e6-962f-a08155638c23.png)

**Comment by lihaiye** [comment]
### 剩余问题：
1、内容介绍中，示例图片中都没有热点和信息层相关的展示
2、广告页面曝光，两个百分比都显示为：56%，需确认是否正常
