### ISSUE TITLE
【后台-数据】数据统计页面，芒果项目筛选栏目时会出现页面崩溃

### ISSUE THREAD

**Issue by lihaiye** [Venvy-dev/demand#993]
问题描述：
>芒果项目-数据统计页面：
筛选 栏目时，多次筛选后，会出现面页面崩溃的情况

![image](https://cloud.githubusercontent.com/assets/17242849/16291803/702bbde8-393d-11e6-9a8e-acac9daeae82.png)

![image](https://cloud.githubusercontent.com/assets/17242849/16291785/30803cbe-393d-11e6-9c7d-d9aac375ffc1.png)

**Comment by vickymin** [comment]
由于视频列表的问题，正式环境不会出现该问题，会尽快解决

**Comment by lihaiye** [comment]
http://test-07.videojj.com/  测试通过

**Comment by lihaiye** [comment]
http://dev.videojj.com/console 测试正常
