### ISSUE TITLE
【控制台】优化资源管理-复制资源

### ISSUE THREAD

**Issue by Gracebaby** [Venvy-dev/demand#998]
## 新增各类型资源复制功能

说明：
复制——仅复制内容，生成新dgID；交互实现逻辑为点击复制button，生成一个复制资源，从原dg缩略图左侧，滑出复制的dg（详见以下图示）

![image](https://cloud.githubusercontent.com/assets/14867684/16335553/de821f1a-3a39-11e6-883f-909be5f02c8f.png)

@summernini   请Summer分配技术实现，谢谢：）

**Comment by summernini** [comment]
@Mancy1011 蘑菇麻烦看下这条需求，是否有必要添加在新的控制台中？（videoos控制台）

**Comment by Mancy1011** [comment]
复制资源功能已添加到原型#1.1
